### ISSUE TITLE
Collation failure on Wasmi

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#101]
**Traceback**

```
Proposing failed: Execution(Wasmi(Memory("trying to access region [1048576..1048660] in memory [0..0]")))
```

**Description**
* Maybe it's connected to https://github.com/paritytech/cumulus/issues/95.

During massive collation testing with 30 collators, block producing stuck on `2076` block with the error above.

**Comment by bkchr** [comment]
This is printed by a collator?

**Comment by akru** [comment]
I see it on both: collator and polkadot nodes, probably it printed on polkadot side.

**Comment by bkchr** [comment]
Do you use the parachain from this repo or did you build one on your own? Could I get the database of the parachain and the relay chain + instructions on how to launch the network?

**Comment by akru** [comment]
I've made my own using a test parachain collator form this repo.

It located here: https://github.com/airalab/robonomics/tree/robonomics-parachain

**Instruction**

1. `cargo build --release`
2. `./target/release/robonomics -d parachain --chain parachain --port 30363`

**Databases**

* [polkadot-db.tar.xz](https://ipfs.io/ipfs/QmTZQQa8QABzGeEf5ruHKZe947y2aiuHa7Sh8u14KtRMjX)
* [parachain-db.tar.xz](htts://ipfs.io/ipfs/QmbFW21i6AdMmNShSp98PaviS4BJ2Kw9YsRHL1hQ3U8v2u)

**Polkadot traceback**
By the way, this error fixed over the time on collator, but stay on polkadot logs:

```
polkadot[5099]: 2020-05-18 05:03:50 Starting parachain attestation session on top of parent 0x9279db6f790bd6cb8180e7f053096fe52ac676e867ee32d5927d729269243aad. Local parachain duty is Some(LocalDuty { validation: Parachain(Id(1000)), index: 0 })
polkadot[5099]: 2020-05-18 05:03:51 ✨ Imported #62578 (0x9279…3aad)
May 18 05:03:54 robonomics-parachain-01 polkadot[5099]: 2020-05-18 05:03:54 Encountered consensus error: ClientImport("Client(Execution(Wasmi(Memory(\"trying to access region [1048576..1048588] in memory [0..0]\"))))")
polkadot[5099]: 2020-05-18 05:03:55 💤 Idle (35 peers), best: #62578 (0x9279…3aad), finalized #62574 (0x514b…e05a), ⬇ 1.8MiB/s ⬆ 3.3MiB/s
polkadot[5099]: 2020-05-18 05:04:00 Encountered consensus error: ClientImport("Client(Execution(Wasmi(Memory(\"trying to access region [1048576..1048588] in memory [0..0]\"))))")
```

**Comment by bkchr** [comment]
So, I tried it and could not reproduce this :(

**Comment by akru** [comment]
No problem, I’ll back when it happens again, thank you!
