### ISSUE TITLE
Strange cache issue with validation_data

### ISSUE THREAD

**Issue by GopherJ** [paritytech/cumulus#1073]
https://github.com/parallel-finance/parallel/blob/04ab24aa83c9252400e740da72f112c62249e152/runtime/vanilla/src/lib.rs#L1547

this always gives `relaychain_block_number: 0` in `on_initialize` hook, but it can be read correctly from polkadotjs apps

**Comment by GopherJ** [comment]
Assuming this is another cache issue

**Comment by bkchr** [comment]
So this can be closed?

**Comment by GopherJ** [comment]
hi @bkchr  sorry to close this a bit late, yes
