### ISSUE TITLE
Parachain not producing blocks

### ISSUE THREAD

**Issue by ascjones** [paritytech/cumulus#1111]
I've done a bisect and starting with https://github.com/paritytech/cumulus/commit/571b20f95e04d734db5fc0f46f9053260067f883 (https://github.com/paritytech/cumulus/pull/1101) the `sync_blocks_from_tip_without_being_connected_to_a_collator` test hangs with the parachain best block stuck at #0. See recent CI failures e.g. https://gitlab.parity.io/parity/cumulus/-/jobs/1458936 

/cc @cheme

**Comment by cheme** [comment]
My companion did update parity-db, but also the substrate and polkadot branch reference.

There is little chance it is paritydb related (if test run on rocksdb, would be good to run them on paritydb too, but I am not sure they use rocksdb).

So my commit was the 22 march, and previous polkadot branch the 12 march.
Culprit should be either in substrate in the range of 89fcb3e4f62d221d4e161a437768e77d6265889e to 715d004061cccbe900d9b2e6d3d624087a34eeef
or polkdot in the range 975e780ae0d988dc033f400ba822d14b326ee5b9 to ea2e07b5d53d868c705d4e92ae4cfdf7f42c6841

But looking at zombienet failure there is good chance https://github.com/paritytech/substrate/commit/dfb2a8cc35244a688e0b052eafb96c6e534ca5a4 fixes it, or I hope so.

**Comment by bkchr** [comment]
@ascjones downgraded ParityDB and that fixed it. Didn't we observed problems with the parachain db and it using paritydb? I could imagine that this explains why the Parachain is not producing any blocks.

**Comment by cheme** [comment]
I got user having issue, on a freshly synced db, did some test last week, but probably in a wrong direction, I was more expecting the issue to be related to using paritydb as parachain db, and ends up finding nothing conclusive in this area (but I was on a db that was still using a previous version of the chain).
Just to be sure @bkchr, you just downgrade parity-db to 0.3.8?

**Comment by ascjones** [comment]
> @ascjones downgraded ParityDB and that fixed it. Didn't we observed problems with the parachain db and it using paritydb? I could imagine that this explains why the Parachain is not producing any blocks.

To be clear I just reverted https://github.com/paritytech/cumulus/commit/571b20f95e04d734db5fc0f46f9053260067f883, which as you say also includes updates to the polkadot and substrate branch references.

**Comment by ascjones** [comment]
Yes works for me now too :+1:
