### ISSUE TITLE
Statemine metadata for genesis block gives only 4 pallets

### ISSUE THREAD

**Issue by eldargab** [paritytech/cumulus#1112]
Hello!

I noticed, that `state_getMetadata` rpc call for genesis block returns metadata with only 4 pallets. 

To reproduce you can run the following script on [polkadot.js.org](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemine-rpc.dwellir.com#/js)

```js
let metadata = await api.rpc.state.getMetadata('0x48239ef607d7928874027a43a67689209727dfb3d3dc5e5b03a39bdc2eda771a')
console.log(metadata.asV12.modules.length)
```

**Comment by joepetrowski** [comment]
Indeed, it started as a humble Shell.
https://github.com/paritytech/cumulus/blob/release-statemint-shell/polkadot-parachains/shell/src/lib.rs#L231L238
