### ISSUE TITLE
Persist relay parent block hash

### ISSUE THREAD

**Issue by 4meta5** [paritytech/cumulus#1121]
Moonbeam wants to use the relay parent block hash as an input for our parachain VRF. 

AFAICT the relay chain parent block hash is not stored or exposed anywhere in cumulus. @bkchr can this data be added to the relay state proof or how should it be included?

**Comment by bkchr** [comment]
Could you not also use the storage root of the relay parent? We don't pass the relay parent hash and that would be a little be too complicated. We could include the parent hash of the relay parent block in the state proof, but I think that the storage root should probably be suffice? 

If yes, you can get access to it through `on_validation_data` of `ParachainSystem`.

**Comment by 4meta5** [comment]
> Could you not also use the storage root of the relay parent?...but I think that the storage root should probably be suffice?

Is the storage root guaranteed to be different/unique for every relay parent block? If so, this will work for us.

**Comment by bkchr** [comment]
Yes it should be different for each relay chain block.
