### ISSUE TITLE
Fix multiple collator setup

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#113]
Running multiple collators lead to problems of collators not receiving Parachain blocks on time. This needs to be investigated and fixed.

**Comment by JoshOrndorff** [comment]
Is it the same issue from #27 ?

**Comment by bkchr** [comment]
I think it looks similar.

**Comment by bkchr** [comment]
To update this. I think one problem is that we currently only update the best block when we import our own block. This is clearly wrong. The best block should be determined by looking into the relay chain. 

So, the idea now is to only update the best block when we import a relay chain block. Otherwise we just will import blocks, don't update the best and don't send a notification.
