### ISSUE TITLE
Governance V2 on CGP

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/cumulus#1143]
Statemint/e runtimes make use of several origins assuming an `ExecutiveBody` on its parent chain, e.g.

```rust
pub type AssetsForceOrigin =
	EnsureOneOf<EnsureRoot<AccountId>, EnsureXcm<IsMajorityOfBody<KsmLocation, ExecutiveBody>>>;
```

With the introduction of https://github.com/paritytech/substrate/issues/10252 / https://github.com/paritytech/polkadot/pull/5205, we will need to map these Root/Executive Body calls to [new origins](https://github.com/paritytech/polkadot/pull/5205/files#diff-92cee7509a74d01aace1ebc1f74fda5d762f949f4add75a08892cbbe48a04345R88).

**Comment by muharem** [comment]
@joepetrowski wonder which origins from Gov v2 we wanna map into AssetsForceOrigin?
The last link in the issue is probably broken

**Comment by muharem** [comment]
see your comment 
https://github.com/paritytech/cumulus/pull/1316#discussion_r885635629

**Comment by joepetrowski** [comment]
- `AssetsForceOrigin`: `Root`
- `CollatorSelectionUpdateOrigin`: `StakingAdmin` (same as [`SlashCancel`](https://github.com/paritytech/polkadot/blob/release-v0.9.31/runtime/kusama/src/lib.rs#L598))
- `ControllerOrigin`: Perhaps use [`WhitelistOrigin`](https://github.com/paritytech/polkadot/blob/release-v0.9.31/runtime/kusama/src/governance/mod.rs#L71), (perhaps `Controller` should be renamed to `XcmQueueOrigin`?)

@gavofyork WDYT?

**Comment by muharem** [comment]
I am scoping what needs to be done to make such a mapping from new origins, will post it here later.

**Comment by muharem** [comment]
Discussed in DM with @joepetrowski 
We propose the ControllerOrigin privileges for xcmp queue to be given to Fellows origin from Relay Chain

**Comment by joepetrowski** [comment]
I believe these are all sorted now. Will expect new issues if there are any operational problems.
