### ISSUE TITLE
Block production stuck

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#119]
**Backtrace**

After one day the latest version of parachain block production stuck with error:

```
Verification failed for block 0x53ec2277af2c11036a35dbe743605fb851881318df1998e934cae8c765c7a2d1 received from peer: 12D3KooWLAG1N4LSNiEbCmvAu94ByZoZMTNPWPHzKJF5B15CaCKE, "Execution: Memory: trying to access region [1048576..1048604] in memory [0..0]"
``` 

when I fetch parachain from scratch I get:
```
2020-06-15 18:42:26 Proposing failed: UnknownBlock("Expect block number from id: BlockId::Hash(0x9c0041f7d6616f81d49079fc0af9ba91caa9b9bfb20ce2cf1885371dc51b2f07)")
```

Collator source code available at https://github.com/airalab/robonomics/blob/df3ca25348905bb578e59dd15b634d824ab79516/bin/node/cli/src/parachain/collator.rs

Public node available at https://parachain.robonomics.network

**Comment by bkchr** [comment]
> `2020-06-15 18:42:26 Proposing failed: UnknownBlock("Expect block number from id: BlockId::Hash(0x9c0041f7d6616f81d49079fc0af9ba91caa9b9bfb20ce2cf1885371dc51b2f07)")`

Probably related to:
https://github.com/paritytech/cumulus/issues/113

**Comment by akru** [comment]
Yes, could it happens in low memory environment?

Probably yes, I’ve multi-collator testnet.

**Comment by bkchr** [comment]
I don't think that this is related to low memory envrionments.

**Comment by bkchr** [comment]
Please try again with this pr: https://github.com/paritytech/cumulus/pull/133

**Comment by akru** [comment]
@bkchr Thank you very much, I'll try soon

**Comment by akru** [comment]
@bkchr, unfortunately, used substrate branch is incompatible with `libp2p-0.20`:
```
   Compiling sc-telemetry v2.0.0-rc4 (https://github.com/paritytech/substrate?branch=cumulus-branch#f59ac8b0)                  error[E0599]: no method named `and_then` found for struct `libp2p_websocket::framed::WsConfig<libp2p_dns::DnsConfig<libp2p_tcp:
:TcpConfig>>` in the current scope                                                                                               --> /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/f59ac8b/client/telemetry/src/worker.rs:92:6
   |                                                                                                                           
92 |                 .and_then(|connec, _| {
   |                  ^^^^^^^^ method not found in `libp2p_websocket::framed::WsConfig<libp2p_dns::DnsConfig<libp2p_tcp::TcpConfig>>`
   |                                                                                                                           
  ::: /home/akru/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-websocket-0.20.1/src/framed.rs:43:1
```

**Comment by bkchr** [comment]
@akru Try again. There was an issue with a libp2p release, that was purged and should be solved by now.

**Comment by akru** [comment]
@bkchr great, it’s build well, I’ll launch it in multicollator environment.

**Comment by bkchr** [comment]
Would be nice to get feedback :) I think it should be fixed now :)

**Comment by akru** [comment]
Well, I've to [upgrade](https://github.com/airalab/robonomics/commit/1994a0328143fcd9037e3691038d51807d22b09b) node to the latest cumulus, unfortunately, the collator didn't start to produce blocks.

@bkchr Could you suggest to me some debug tricks of collator block producing traces.

**Comment by bkchr** [comment]
You also updated the relay chain?

**Comment by bkchr** [comment]
Please run with `cumulus-collator=tracing`

**Comment by akru** [comment]
@bkchr great, thank you! Block production started using latest `v0.8.13` Westend runtime, but proposed blocks doesn't included in relay chain. Should I do something else?

**Comment by akru** [comment]
I've just got block producing but `best` ins't changed.
```
2020-07-04 19:03:26 🙌 Starting consensus session on top of parent 0x0c2e6c58ca455a96adace2fc233119ec841a9dd41a367a08219d1fb510fecf4b
2020-07-04 19:03:26 Starting parachain attestation session on top of parent 0x116712e6fe9fbc465d83aa902009ba6d58c7894d164f5cc77ec58785f9a26372. Local parachain duty is None
2020-07-04 19:03:26 🎁 Prepared block for proposing at 1 [hash: 0xe94d2dde23a2e6e8270230f00d99e97164903b81cd6a5c06ccb58a6898ecef88; parent_hash: 0x0c2e…cf4b; extrinsics (2): [0xd3fb…a9c1, 0x3189…9c0a]]
2020-07-04 19:03:26 ✨ [Parachain] Imported #1 (0xe94d…ef88)
2020-07-04 19:03:29 💤 [Parachain] Idle (0 peers), best: #0 (0x0c2e…cf4b), finalized #0 (0x0c2e…cf4b), ⬇ 0 ⬆ 0
2020-07-04 19:03:29 💤 [Relaychain] Idle (2 peers), best: #1221 (0x1167…6372), finalized #1219 (0x0f2f…1160), ⬇ 1.2kiB/s ⬆ 0.7kiB/s
```

**Comment by bkchr** [comment]
But you have produced a block 🤔  Anything special in the relay chain logs?

**Comment by akru** [comment]
Nothing special, should I focus on some traces? Is `best` block related to relay chain?

**Comment by bkchr** [comment]
If the relay chain does not include the parachain block, the best can not change.

Can you please run with -lvalidation=trace on the relay chain and post the logs?

You habe 2 relay chain validators running?

**Comment by akru** [comment]
Ah, yes, it works well with 3 active relay chain validators. Thank you!
