### ISSUE TITLE
Not all parachain logs properly prefixed

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#120]
In #109 @cecton introduced prefixed for log messages to make it clear whether a log was coming from the relay chain or the parachain. This is a hugely useful feature :partying_face: Some logs are still not properly prefixed. I just got this log from the test collator.

```
2020-06-15 14:48:36 Starting parachain attestation session on top of parent 0x1c97041364ad482843411b61709606b126cf3a4b1628423dfdb7f59b1c6c6527. Local parachain duty is None
```

**Comment by JoshOrndorff** [comment]
Also got this log without a prefix. I think they both come from parachain?

```
2020-06-15 15:43:58 Bootnode with peer id `12D3KooWF9dnrcjQ43e2ASgPVy5DXtYpEG3JwHxGx3gudTxBVmXn` is on a different chain (our genesis: 0xf677…0fce theirs: 0x4ed0…5c89)
```

**Comment by bkchr** [comment]
Yeah we are aware and that is the reason the original issue is still open: https://github.com/paritytech/cumulus/issues/19

So, I close this.

**Comment by bkchr** [comment]
> Also got this log without a prefix. I think they both come from parachain?
> 
> ```
> 2020-06-15 15:43:58 Bootnode with peer id `12D3KooWF9dnrcjQ43e2ASgPVy5DXtYpEG3JwHxGx3gudTxBVmXn` is on a different chain (our genesis: 0xf677…0fce theirs: 0x4ed0…5c89)
> ```

If you only have one Collator, it comes from the relay chain.
