### ISSUE TITLE
Community Parachains Repo

### ISSUE THREAD

**Issue by gilescope** [paritytech/cumulus#1217]
We would like to complete the split of collator and runtimes and move the community parachains into a separate repo with this dir layout:

- pallets
- primitives
- scripts
- runtimes
  - templates
    - parachain-template
    - shell
    - seedling
  - assets
    - statemine
    - statemint
  - governance
  - nursery
    - canvas-kusama
    - rococo-parachain

Potentially we do this in several stages / PRs: 
- [ ] chainspecs are embedded in nodes currently. BLOCKER?
- [ ] create uninitialised new github repo
- [ ] move the repo as is.
- [ ] alter CI scripts to skip any collator related building, cull collator code and pull in cumulus as a dep.
- [ ] alter CI scripts to refer to `main`, rename `master` to `main`.
- [ ] package SRtool into github action (so it can handle new layout).
- [ ] move about the directories to the agreed layout.
- [ ] add parachain-info.json files to provide data on target relay chain, has sudo, xcm support?, etc.

**Comment by joepetrowski** [comment]
I would change `common-good-parachains` to `parachain-runtimes` as it's up to governance what becomes a common good. Otherwise I think it looks reasonable.

**Comment by joepetrowski** [comment]
Plan is to stay in Cumulus. Closing for now and will open a new issue or PR with some directory tidying.
