### ISSUE TITLE
Is `rococo-parachain` necessary?

### ISSUE THREAD

**Issue by NachoPal** [paritytech/cumulus#1222]
Coming from: https://github.com/paritytech/cumulus/pull/1223

I would like to understand what is the role of `rococo-parachain`. I think `parachain-template` should be sufficient and the way to go if you want to tests/tinker/build a parachain.

It seems to me that having both runtimes coexisting is redundant. `rococo-parachain` configuration is closer to what we (the Common Goods parachains team) want to achieve (a parachain template ready to interact with a Relay chain and its Common Good parachains), however I think that logic should go to the template. Furthermore, right now it is unclear to me what configuration `parachain-template` is following.

I would like to propose removing `rococo-parachain` unless there is a reason for keeping both runtimes. It will be also one runtime less to maintain.

**Comment by NukeManDan** [comment]
https://github.com/paritytech/cumulus/pull/1223#issuecomment-1112495530
> This template is used to start most parachain projects from, and thus is intended to be minimal AKAIU, thus adding more functionality here, especially divergent from the [substrate template](https://github.com/paritytech/substrate/tree/master/bin/node-template), isn't ideal.
> 
> If common good chains need a more purpose built template, I would think it should live independent from the soverign template (we have now) if significantly different. Especially in the XCM configuration, because this template should never be set such that a soverign chain basing off the settings here unchanged could allow for the same trust with the relay and other siblings. Issues happened in this light, addressed in https://github.com/paritytech/cumulus/pull/696 (at least this was attempted, not merged now I see grimacing )

**Comment by bkchr** [comment]
> a parachain template ready to interact with a Relay chain and its Common Good parachains

I don't really get why we need a template for everything. These should be tutorials and not just random templates. In the end there would be thousands of templates, while they actually just have 2-3 xcm things configured differently.

**Comment by hbulgarini** [comment]
@PierreBesson is `rococo-parachain` used in the testnets?

**Comment by bkchr** [comment]
Tick/Trick/Track are currently based on `rococo-parachain`. 

>  of the CLI with something like --chain staging-parachain to build "dumb parachains" chainspecs and replace the tick, trick and track raw chainspecs.

Yeah that could be done.

**Comment by hbulgarini** [comment]
> Tick/Trick/Track are currently based on rococo-parachain.
@bkchr are we still using Tick/Trick/Track? If we do, then we will keep parachain runtime. If not, i would say that we might remove it.

**Comment by PierreBesson** [comment]
Yes we are using Tick parachains for testing parachain scalability in our Versi internal network. We could replace them by a different runtime without much effort. However Tick parachains are very convenient for us because they don't need any injected aura keys to produce blocks.

**Comment by hbulgarini** [comment]
Ok, perfect. Based on this discussion `rococo-parachain` is still needed. Please be aware that as part of polkadot-parachains folder restructuring (#1240), this parachain will be moved to `testing` folder.
