### ISSUE TITLE
`polkadot-parachains` folder restructuring.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/cumulus#1240]
In order to enhance the developer experience and documentation for engineers working with the parachains living under  [polkadot-parachains](https://github.com/paritytech/cumulus/tree/master/polkadot-parachains), a new folder called `parachain-runtimes` will be created with the following structure:

- parachain-runtimes
    - chain-specs (formerly known as `res`) 
    - common
        - utilities (common shared code / libraries)
        - <del>tests ( folder containing unit tests for different functionalities )</del> Moved to`polkadot-parachain` folder
    - pallets
        - specific pallets for parachains (e.g. collator-selection)
    - <del>src (entry point folder for commands/services etc )</del> Moved to `polkadot-parachain` folder
    - starters
        - shell (can be used to launch an "empty" runtime that can be upgraded via a downward message)
        - seedling (runtime with sudo to register prior to migrating a solo-chain into a parachain)
        - <del>scaffold (formerly known as `parachain-template`, a scaffold/template for teams to start from when developing a runtime)</del>  [Discussion](https://github.com/paritytech/cumulus/issues/1240#issuecomment-1120853289)
    - testing
        - pen-pal (parachain runtime ready with the necessary XCM setup to test interactions with Statemine/Statemint)
        - rococo-parachain (used for creating Tick/Trick/Track parachains). Discussion #1222
    - assets
        - statemine
        - statemint
     - contracts
        - substrate-contracts
    - governance (as an example of a potential common good parachain dedicated to governance)
        - kusama-gov
        - polkadot-gov
    - etc...

Also based as a result of a diagnostic of the existing parachains on the folder, Wesmint would be removed since we would be deploying the Statemint runtime directly on Westend.

Every parachain runtime should include a rust doc with the purpose of it.

@joepetrowski

**Comment by gilescope** [comment]
Would like penpal not hyphenated but it's all fine with me.

**Comment by bkchr** [comment]
> starters
> 
>     * shell (can be used to launch an "empty" runtime that can be upgraded via a downward message)
> 
>     * seedling (runtime with sudo to register prior to migrating a solo-chain into a parachain)
> 
>     * scaffold (formerly known as `parachain-template`, a scaffold/template for teams to start from when developing a runtime)

Why should this entire stuff be moved there? I mean I get that `shell` and `seedling` are already there as a runtime, but the template is an entire node. Not sure this makes sense.

**Comment by hbulgarini** [comment]
> Why should this entire stuff be moved there? I mean I get that shell and seedling are already there as a runtime, but the template is an entire node. Not sure this makes sense.

OK. Fair enough. We will not move the `parachain-template` into the `polkadot-parachains` folder and it can remain as it is with no changes.
