### ISSUE TITLE
Can't parse chain spec with `forkBlocks` or `badBlocks`

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#126]
In #122 I added the ability to pass a json chainspec to the embedded relay-chain node. While this feature basically works, it does not parse chain specs created by polkadot `91f3e68` (tip of `cumulus-branch` at time of writing).

It fails to parse the `forkBlocks` and `badBlocks` fields. Removing these fields allows the file to parse without error and the embedded node to peer with the relay chain validators.

I discovered this when updating the cumulus workshop. Detailed writeup at https://github.com/JoshOrndorff/cumulus-workshop/blob/master/1-prep/2-chain-spec.md#create-your-own

**Comment by bkchr** [comment]
Yeah, I have seen this also some time, but did not yet looked into it.

**Comment by JoshOrndorff** [comment]
Haven't seen this one in a while. I'll go ahead and close it.
