### ISSUE TITLE
Port `state-machine` to `no-std`

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#129]
Instead of rewriting parts of the logic in `state-machine` again in Cumulus (like how it is done currently), we should directly use `state-machine` to make use of the same logic.

This will require that `state-machine` compiles for `no-std`. Or even better, we start by splitting the logic out of `state-machine` to make it more modular.

**Comment by cheme** [comment]
If nobody is working on it, I will try to expose part of state machine for cumulus. I will not include child trie for now, because as mentioned in #37 this would requirers to have witness of child trie added, so keeping that for future.

**Comment by bkchr** [comment]
Can you elaborate a little more what your plan on this would be?

I already thought about this and think this issue should be started by cleaning the `state-machine` crate a little bit. Aka moving stuff into new crates, like the `BasicExternalities` and `TestExternalities`.  `changes-trie` should also be moved into its own crate IMHO.

**Comment by cheme** [comment]
Plan here is just to switch trie_backend and overlay change to no_std and add a new WitnessBackend or WitnessExternalities (then make also state machine Backend or even Externalities trait no_std) that will be very similar to cumulus WitnessStorage (containing only a trie backend and a change overlay).
So in cumulus use directly this WitnessBackend and remove WitnessStorage and associated trait.

So I did not plan to move things around, just have a part of state-machine no_std compatible.

**Comment by bkchr** [comment]
There is already the proof backend? We should be able to use this?

**Comment by cheme** [comment]
Oh, I guess the trait that need implementation is more Externalities (we want to have the write operation like set_storage), not Backend, so proof backend do not have these (only Ext is actually using the OverlayedChanges so the WitnessBackend code should mostly reuse Ext implementation of externalities (without trace, panic handler, and child trie).

**Comment by bkchr** [comment]
You should be able to just use `ProvingBackend` as backend for `Ext` and than we should have all the functionality we require.
