### ISSUE TITLE
Validators should validate blocks from secondary collators

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#130]
Currently it seem that validators only validate blocks from primary collators. This needs to be fixed, as you can use this to block other collators from producing blocks. Even if the primary collator is not sending any block at all, a secondary one doesn't get the chance to send a block.

More a Polkadot issue, but still good to keep it here.

**Comment by JoshOrndorff** [comment]
Dumb question: What makes a collator a Primary collator? Is it the individual validator that considers a collator Primary? Or do all validators agree which collator is the primary one?

**Comment by bkchr** [comment]
AFAIR the first one that connects.

But this system does not makes that much sense. In the future when we have some sort of bundling between collators and validators, it will make sense.

**Comment by bkchr** [comment]
Fixed by https://github.com/paritytech/polkadot/pull/1353
