### ISSUE TITLE
Statemint: Accept Native Assets of Other Parachains

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/cumulus#1317]
Applications (or other parachains themselves) may have reason to use their native asset on Statemint, but so far Statemint only recognises the native asset of its parent (DOT/KSM) and assets registered under `pallet-assets`.

Other parachains have already passed a spam-protection mechanism, namely securing a lease via auction. They should be able to use their assets on Statemint. This could mean either reserving some namespace within `AssetId`s, or simply adding another instance of the Assets pallet where `AssetId = ParaId`. The other para would act as the reserve and Statemint could mint backed assets under the separate pallet.

**Comment by xlc** [comment]
But parachains may have multiple assets. `AssetId = ParaId` won't work. And how about ERC20 assets user deployed in EVM? Or only 1 native asset per parachain is going to be supported?

**Comment by joepetrowski** [comment]
> Or only 1 native asset per parachain is going to be supported?

I wrote the issue as a general idea, not as a specification. I'm all ears :)

> how about ERC20 assets user deployed in EVM?

This I would be more hesitant about TBH. I think the native token of a chain should basically get a "free pass" as having passed a spam prevention mechanism. But if users can permissionlessly and without deposit mint assets on an EVM, then it'd be easy to spam Statemint. For these assets, it could be better for them to claim a normal asset ID and put down a deposit.

**Comment by xlc** [comment]
Unless you enforce only X assets per chain, otherwise, it is impossible to tell if an asset is worth anything. So yeah we need an asset registry (which we have at least 7 different versions out there https://github.com/paritytech/substrate/discussions/11530).

**Comment by joepetrowski** [comment]
Done using `ForeignAssets` https://github.com/paritytech/cumulus/pull/2540
