### ISSUE TITLE
Script for registering a Parachain

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#134]
For launching a test net, we need a script that helps our devops. The script should take the following arguments:

- Genesis state of the Parachain
- Wasm file of the Parachain
- Number of tokens for the Parachain account
- Parachain id
- Sudo account private key

The script should do the following:

- Register a Parachain using the Sudo account
- Deposit given amount of tokens into the parachain account

**Comment by cecton** [comment]
Ok I finally have it :tada: but I don't think I should write a JS script/cli for this. It is not worth it and will only add maintenance.

Here is the procedure:

1. Install polkadot-js-api

    ```
    npm install -g @polkadot/api-cli
    ```

    In CI you might want this to be installed userspace. For that you just need to drop the `-g` of the command and the program will be installed in the current directory in `node_modules/.bin/polkadot-js-api`

2. Register a parachain

    ```
    polkadot-js-api \
        --ws ws://127.0.0.1:9944 \
        --sudo \
        --seed "//Alice" \
        tx.registrar.registerPara \
            100 \
            '{"scheduling":"Always"}' \
            @/path/to/cumulus_test_parachain_runtime.compact.wasm \
            "0x000000000000000000000000000000000000000000000000000000000000000000d2e4b74d003416349b6c34024d59b6243cbed4977baa3678fe81802a957a795703170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400"
    ```

    **Parameters:**

    `--ws ws://127.0.0.1:9944`: host address
    `--seed "//Alice"`: keyring uri with whom to make the transaction
    `100`: parachain ID
    `@/path/to/cumulus_test_parachain_runtime.compact.wasm`: runtime WASM file (needs to be prefixed by `@` so it knows it's a file the read)
    `0x00000000...cf4c11131400`: genesis state

3. Deposit given amount of tokens

    ```
    polkadot-js-api \
        --ws ws://127.0.0.1:9944 \
        --sudo \
        --seed //Alice \
        tx.balances.setBalance \
            5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL \
            1000000000000000 \
            1000000000000000
    ```

    **Parameters:**

    `--ws ws://127.0.0.1:9944`: host address
    `--seed "//Alice"`: keyring uri with whom to make the transaction
    `5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL`: account of the beneficiary
    `1000000000000000`: free amount (1000 multipliyed by 10^12)
    `1000000000000000`: reserved amount (1000 multipliyed by 10^12)

cc @evaldofelipe

**Comment by bkchr** [comment]
Please put this into a script and create a pr :)

**Comment by cecton** [comment]
I don't think they want a script that does npm install for them... or do you have reasons to want a script? (like it is easier for us to change without requesting for a change?)

**Comment by bkchr** [comment]
I did not say that there should be any "npm intall"

I just want a script:

```register-parachain wasm genesis id tokens```

That does these 2 steps together. Alone for having it usable for my own tests

**Comment by cecton** [comment]
Ok sorry, I do it right away

**Comment by cecton** [comment]
@evaldofelipe in case you do want a script you can find it there: https://github.com/paritytech/cumulus/blob/master/scripts/register_parachain.sh
