### ISSUE TITLE
Can authorities not store two copies?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/cumulus#1387]
I found `aura-ext` impls:

```rust
    #[pallet::hooks]
    impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
        fn on_finalize(_: BlockNumberFor<T>) {
            // Update to the latest AuRa authorities.
            Authorities::<T>::put(Aura::<T>::authorities());
        }

        fn on_initialize(_: BlockNumberFor<T>) -> Weight {
            // Fetch the authorities once to get them into the storage proof of the PoV.
            Authorities::<T>::get();

            T::DbWeight::get().reads_writes(2, 1)
        }
    }
```

Can it be changed as follows:
```rust
	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		fn on_initialize(_: BlockNumberFor<T>) -> Weight {
			// Fetch the authorities once to get them into the storage proof of the PoV.
			let _ = Aura::<T>::authorities();

			T::DbWeight::get().reads_writes(2, 1)
		}
	}
```

And then we should use the `aura` pallet storage to run `execute_block`

It seems that there are no need to store twice ?

> Serves as cache for the authorities.
The authorities in AuRa are overwritten in on_initialize when we switch to a new session, but we require the old authorities to verify the seal when validating a PoV. This will always be updated to the latest AuRa authorities in on_finalize.

I know the docs, but it seems that the `execute_block` do not need to do in such way.

<del>We can put `aura-ext` pallet in front of `aura` pallet if some aura will be changed by `on_initialize`. </del>
By default, authority set only will be changed after `on_initialize` and before `on_finalize`.

We could always get the current block authority set. And the pallet order is not important.
If authority set changed in current block, it's ok, because we always use `aura` stroage  before `execute_block`

**Comment by bkchr** [comment]
> So the `PoV` only need the old authorities(before execute tx). So we just put the aura authorities into PoV during`on_initilize` seem is enough.

Exactly :) So, we can close this? :)

**Comment by yjhmelody** [comment]
> > So the `PoV` only need the old authorities(before execute tx). So we just put the aura authorities into PoV during`on_initilize` seem is enough.
> 
> Exactly :) So, we can close this? :)

I could create a PR to do it.

**Comment by bkchr** [comment]
To do what?

**Comment by yjhmelody** [comment]
> To do what?

Improve the `aura-ext` code ?

**Comment by bkchr** [comment]
You are very unspecific on what you want to do. Maybe you write it down exactly. "improve the aura-ext code" could mean anything. 

Your assumption that the authorities are only changed after `on_initialize` of every pallet has run, is also not correct. The point here being that we need to ensure that we read the data before we it is set and that is currently not possible in any different way.

**Comment by yjhmelody** [comment]
Yeah, you're right. But if `on_initialize` of `aura-ext` run before other pallets. It's enough to do just getting authorities  when `on_initialize`. Not other storage needed here.

**Comment by bkchr** [comment]
Yeah, but you can not know this and for now I like to play safe until we have a better solution.

**Comment by yjhmelody** [comment]
Yeah, I closed it. Thanks.
