### ISSUE TITLE
Support purging sibling blocks

### ISSUE THREAD

**Issue by crystalin** [paritytech/cumulus#1393]
Currently there is the issue when importing many blocks at the same height for parachain that will trigger a "too many siblings" error when importing new ones.

A usual solution for blockchain is to revert the last block(s) to get rid of them. However this is not always possible  in the parachain scenario, because those siblings blocks are not marked as "best" (which would require the relaychain to include them). So the parachain best is the last "included" block, which can also be the last "finalized" block, preventing the parachain to revert their blocks.

Ideally we would either:
1. Offer a command to purge siblings
2. Make revert support current siblings blocks.

**Comment by mmyyrroonn** [comment]
@crystalin Hi, I met this issue on our rococo testnet. Any solution for this issue right now? Do I need to upgrade to the v0.9.27 and purge the siblings?

**Comment by bkchr** [comment]
Easiest is to upgrade to get this fix. Or to delete your db.

**Comment by mmyyrroonn** [comment]
> Easiest is to upgrade to get this fix. Or to delete your db.

Thank you! let me try. 😄
