### ISSUE TITLE
docker error: could not compile `polkadot-service`.

### ISSUE THREAD

**Issue by whalelephant** [paritytech/cumulus#140]
Hi, 

I am trying to use the script/build_polkadot.sh to create the dockers for the relay chain nodes. 

However, the docker was unable to compile with the following message
```
The command '/bin/sh -c curl https://sh.rustup.rs -sSf | sh -s -- -y &&         export PATH=$PATH:$HOME/.cargo/bin &&         scripts/init.sh &&         cargo build --$PROFILE' returned a non-zero code: 101
```

Thanks!

**Comment by bkchr** [comment]
Hey, without the compile error we can not help you.

But please try again today.

**Comment by whalelephant** [comment]
Hi, here is the error, and yes will try again today. thanks!


error: could not compile `polkadot-service`.

Caused by:
  process didn't exit successfully: `rustc --crate-name polkadot_service --edition=2018 service/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="av_store"' --cfg 'feature="consensus"' --cfg 'feature="db"' --cfg 'feature="default"' --cfg 'feature="full-node"' --cfg 'feature="polkadot-network"' -C metadata=3ab2ded4eacd03d3 -C extra-filename=-3ab2ded4eacd03d3 --out-dir /polkadot/target/release/deps -L dependency=/polkadot/target/release/deps --extern frame_benchmarking=/polkadot/target/release/deps/libframe_benchmarking-b84f931ad5dfade1.rmeta --extern system_rpc_runtime_api=/polkadot/target/release/deps/libframe_system_rpc_runtime_api-9ae5521c721f9e5b.rmeta --extern futures=/polkadot/target/release/deps/libfutures-3c68364bc5730d12.rmeta --extern hex_literal=/polkadot/target/release/deps/libhex_literal-feff90488848b93f.rmeta --extern kusama_runtime=/polkadot/target/release/deps/libkusama_runtime-c3b8537bc77d6a09.rmeta --extern lazy_static=/polkadot/target/release/deps/liblazy_static-14afa302397059c5.rmeta --extern log=/polkadot/target/release/deps/liblog-6c1ada0480168a85.rmeta --extern pallet_babe=/polkadot/target/release/deps/libpallet_babe-495a4ddc5a29c0af.rmeta --extern im_online=/polkadot/target/release/deps/libpallet_im_online-aa8b57a2c19cc034.rmeta --extern pallet_staking=/polkadot/target/release/deps/libpallet_staking-41dc35c98b0a8e8d.rmeta --extern pallet_transaction_payment_rpc_runtime_api=/polkadot/target/release/deps/libpallet_transaction_payment_rpc_runtime_api-5a2b4cb44469f1d0.rmeta --extern codec=/polkadot/target/release/deps/libparity_scale_codec-f03743df6b592452.rmeta --extern parking_lot=/polkadot/target/release/deps/libparking_lot-fdb4434d4bf54542.rmeta --extern av_store=/polkadot/target/release/deps/libpolkadot_availability_store-f9c4f5b1f201e9fb.rmeta --extern polkadot_network=/polkadot/target/release/deps/libpolkadot_network-c696137a25709d9b.rmeta --extern polkadot_primitives=/polkadot/target/release/deps/libpolkadot_primitives-cca0b3dadf962c60.rmeta --extern polkadot_rpc=/polkadot/target/release/deps/libpolkadot_rpc-dc44238158c5c19d.rmeta --extern polkadot_runtime=/polkadot/target/release/deps/libpolkadot_runtime-6a6ff6a2fcf858ef.rmeta --extern consensus=/polkadot/target/release/deps/libpolkadot_validation-7f8f5e7151c3395c.rmeta --extern authority_discovery=/polkadot/target/release/deps/libsc_authority_discovery-082b5d049a24a417.rmeta --extern sc_block_builder=/polkadot/target/release/deps/libsc_block_builder-f36fe36b6547bab0.rmeta --extern sc_chain_spec=/polkadot/target/release/deps/libsc_chain_spec-ea39469cba2d49e9.rmeta --extern sc_client_api=/polkadot/target/release/deps/libsc_client_api-02f4580d05a75dec.rmeta --extern sc_client_db=/polkadot/target/release/deps/libsc_client_db-e914dc79db575bd1.rmeta --extern sc_consensus=/polkadot/target/release/deps/libsc_consensus-38051c2364da5cde.rmeta --extern babe=/polkadot/target/release/deps/libsc_consensus_babe-6cababa7cec80c73.rmeta --extern sc_executor=/polkadot/target/release/deps/libsc_executor-697aa1c863461f88.rmeta --extern grandpa=/polkadot/target/release/deps/libsc_finality_grandpa-855b650428368be9.rmeta --extern sc_keystore=/polkadot/target/release/deps/libsc_keystore-1e7a7f1d1a768e3d.rmeta --extern sc_network=/polkadot/target/release/deps/libsc_network-74e26178464f2759.rmeta --extern service=/polkadot/target/release/deps/libsc_service-4653ad5578040bae.rmeta --extern telemetry=/polkadot/target/release/deps/libsc_telemetry-bc8e37f50451aef0.rmeta --extern sc_transaction_pool=/polkadot/target/release/deps/libsc_transaction_pool-fd39dbf803753ce0.rmeta --extern serde=/polkadot/target/release/deps/libserde-8c004d52d1c1ceea.rmeta --extern slog=/polkadot/target/release/deps/libslog-889d6dfcb4d0b63b.rmeta --extern sp_api=/polkadot/target/release/deps/libsp_api-f6731a41541d2f4f.rmeta --extern authority_discovery_primitives=/polkadot/target/release/deps/libsp_authority_discovery-6fcf2da68f8d10f3.rmeta --extern sp_block_builder=/polkadot/target/release/deps/libsp_block_builder-29b7214631780ab1.rmeta --extern sp_blockchain=/polkadot/target/release/deps/libsp_blockchain-6a62b2c989e1253b.rmeta --extern consensus_common=/polkadot/target/release/deps/libsp_consensus-ec5faa9c28ab5f41.rmeta --extern babe_primitives=/polkadot/target/release/deps/libsp_consensus_babe-9e6a11f41ff4037f.rmeta --extern sp_core=/polkadot/target/release/deps/libsp_core-292c51ebd0cd81a5.rmeta --extern grandpa_primitives=/polkadot/target/release/deps/libsp_finality_grandpa-1c490c7df586f7cc.rmeta --extern inherents=/polkadot/target/release/deps/libsp_inherents-9f655cac6b5e0088.rmeta --extern sp_io=/polkadot/target/release/deps/libsp_io-906a1b4818ab3e95.rmeta --extern sp_offchain=/polkadot/target/release/deps/libsp_offchain-0deca09089359e7a.rmeta --extern sp_runtime=/polkadot/target/release/deps/libsp_runtime-4ecc512bd1948820.rmeta --extern sp_session=/polkadot/target/release/deps/libsp_session-3ac3516190b34b77.rmeta --extern sp_transaction_pool=/polkadot/target/release/deps/libsp_transaction_pool-8540ee23221f015a.rmeta --extern sp_trie=/polkadot/target/release/deps/libsp_trie-5d75cb04edd560e3.rmeta --extern prometheus_endpoint=/polkadot/target/release/deps/libsubstrate_prometheus_endpoint-a9b64f8702e1907a.rmeta --extern westend_runtime=/polkadot/target/release/deps/libwestend_runtime-8db546e5b1451c38.rmeta -L native=/polkadot/target/release/build/clear_on_drop-f82193298852a185/out -L native=/polkadot/target/release/build/jemalloc-sys-4d5eb43e14c02ce4/out/build/lib -L native=/polkadot/target/release/build/ring-7c2c8fe5d5ab2d41/out -L native=/polkadot/target/release/build/libz-sys-b422d1d5ddc45dd8/out/build -L native=/polkadot/target/release/build/substrate-wasmtime-runtime-2124180b4a6839c7/out -L native=/polkadot/target/release/build/zstd-sys-f1778825db718a8a/out -L native=/polkadot/target/release/build/librocksdb-sys-77bfe83d988c4c83/out -L native=/polkadot/target/release/build/librocksdb-sys-77bfe83d988c4c83/out` (signal: 9, SIGKILL: kill)

**Comment by bkchr** [comment]
This means that you probably not have enough main memory for compiling the project. Add some swap to make it compile.

**Comment by whalelephant** [comment]
got it thanks!

**Comment by zhangtianai** [comment]
Did you compile it successfully?

**Comment by whalelephant** [comment]
hey @zhangtianai yes. This went away went allow docker memory to 6GB

**Comment by zhangtianai** [comment]
Operating environment：
AWS
`General purpose | t2.xlarge | 4 | 16`
My running steps are
steps 1:
`./build_docker.sh`
steps 2:
`./build_polkadot.sh`
steps 3:
`./dc.sh`
Is this step right？What are your steps？

**Comment by zhangtianai** [comment]
```
/usr/bin/yarn -> /usr/lib/node_modules/yarn/bin/yarn.js
/usr/bin/yarnpkg -> /usr/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.5
added 1 package in 0.317s
yarn global v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@polkadot/api-cli@0.10.0-beta.14" with binaries:
      - polkadot-js-api
Done in 9.75s.
Removing intermediate container aeccfca66805
 ---> ee17fa58d1d5
Step 11/21 : COPY --from=builder     /paritytech/cumulus/target/release/rococo-collator /usr/bin
 ---> 9fd58d8f8ddd
Step 12/21 : COPY ./docker/scripts/inject_bootnodes.sh /usr/bin
COPY failed: stat /var/lib/docker/tmp/docker-builder122293895/docker/scripts/inject_bootnodes.sh: no such file or directory

real    44m52.691s
user    0m0.413s
sys     0m0.228s
```

**Comment by zhangtianai** [comment]
How to solve？

**Comment by zhangtianai** [comment]
```
Step 6/21 : WORKDIR /paritytech/cumulus
 ---> Using cache
 ---> bd5ab1d977d8
Step 7/21 : COPY . .
 ---> Using cache
 ---> bb71ff2df51a
Step 8/21 : RUN cargo build --release -p rococo-collator
 ---> Using cache
 ---> 6c08ee7653b0
                                                                                                                                                 
Step 9/21 : FROM debian:buster-slim as collator
 ---> c7346dd7f20e
Step 10/21 : RUN apt-get update && apt-get install jq curl bash -y &&     curl -sSo /wait-for-it.sh https://raw.githubusercontent.com/vishnubob/w
ait-for-it/master/wait-for-it.sh &&     chmod +x /wait-for-it.sh &&     curl -sL https://deb.nodesource.com/setup_12.x | bash - &&     apt-get in
stall -y nodejs &&     npm install --global yarn &&     yarn global add @polkadot/api-cli@0.10.0-beta.14
 ---> Using cache
 ---> ee17fa58d1d5
Step 11/21 : COPY --from=builder     /paritytech/cumulus/target/release/rococo-collator /usr/bin
 ---> Using cache
 ---> 64d2b088d72e
Step 12/21 : COPY /root/cumulus/docker/scripts/inject_bootnodes.sh /usr/bin
ERROR: Service 'genesis_state' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder589416622/root/cumulus/docker/scripts/inject_
bootnodes.sh: no such file or directory
```
