### ISSUE TITLE
Forward block producer to the runtime

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#142]
As with `Babe`/`Aura`, we should forward the block author to the runtime.

This should only be used when we don't use `Babe`/`Aura`. We would forward the block author using an inherent digest to the runtime.

**Comment by bkchr** [comment]
For an example on how digests work, we can have a look at Babe: https://github.com/paritytech/substrate/blob/master/primitives/consensus/babe/src/digests.rs

[Here](https://github.com/paritytech/substrate/blob/master/client/consensus/babe/src/lib.rs#L511) it is generated while building a block. This would need to be adapted, because we currently don't work with the `Slot` interface.

The digest would need to be passed to the runtime [here](https://github.com/paritytech/cumulus/blob/master/collator/src/lib.rs#L294) (the `Default::default()` needs to be replaced).

On the runtime side we would need to add a pallet that supports the `FindAuthor` trait like [here](https://github.com/paritytech/substrate/blob/e68e3a377530d8502f22be38b0b46ba192690ef9/frame/babe/src/lib.rs#L347).

**Comment by bkchr** [comment]
What I don't know, which key we want to use to identify the block author. Normally I would say that we create a new application key, as it is done for `Aura`/`Babe`. But we also need some sort of "connection" (especially to be sure that both keys are controlled by the same party) between the block author and collator key. For `Babe`/`Aura` we would put the collator key into the session keys and would have the connection in this way, because one account would be in control of these keys.

With the open collator set this is different, because we basically don't require that a collator is registered, at least as far as I know. However, we could also just add support for this and require collators to at least register on chain. If we would require a registration on chain, this could also be used for the pre-validation phase that was discussed recently CC @rphmeier

**Comment by rphmeier** [comment]
If there is no registered validator set that is fine, I guess we'd want to use the collator key itself, wouldn't we? I think we should allow the open collator set but also have the option to plug into `session` or something that handles collator set changes. Then the `CollatorId` can be one session key and the block author key can be another session key. And we can associate them by index in the validator set

**Comment by bkchr** [comment]
> If there is no registered validator set that is fine, I guess we'd want to use the collator key itself, wouldn't we?

Yeah that is right. However, in Substrate we always have application specific keys. But yeah, if we make the key generic, it should probably work to use the `CollatorId` and also enable other uses cases where the collator set is more restricted.

When we have `Babe`/`Aura` we will not require this feature here anyway, as they already support to determine the block producer.

**Comment by JoshOrndorff** [comment]
An open collator set is similar to a PoW chain where anyone can permissionlessly mine. In both Kulupu, and the Bitcoin-like substrate chain, there is a CLI option for miners to specify the address to which mining rewards should be paid and then it is injected via an inherent (inherent digest would also work).
