### ISSUE TITLE
Improving the Polkadot  "source" release branch creation process

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/cumulus#1449]
When a new Polkadot release is created, teams would like to update their parachains accordingly. 

Can we improve the process so that as soon as a Polkadot release is created, a corresponding Polkadot release branch is also created? What would the work for that entail?

I am happy to help. Some questions I have:
1. What does creating a Polkadot release branch on Cumulus consist of?
-  Is it a matter of updating Substrate dependencies, if so, then I can help with this (or is there more to it?)

Stakeholders here are parachain teams that use Cumulus and developers that are working with `substrate-parachain-template`.

**Comment by chevdor** [comment]
To get started, here are a few points I have in mind.

The first question is where to cut. We need to see if this is acceptable to take master _as soon as _ a new polkadot release lands. It is probably not the case and if not, the start of that process probably needs to be manual.

Once we know where to "cut", there will be a `diener` run and a cargo update.

**Comment by NukeManDan** [comment]
Under what conditions would the head of master not work? For example: a polkadot release that was stalled for many days or weeks, while more changes are happening to cumulus.

Other than failing to build with the upstream dependencies set to the release tag/branch, what could signal a problem?

**Comment by bkchr** [comment]
@coderobe said that they (release eng) would take over the branch creation.
