### ISSUE TITLE
Multicollator mode issue

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#146]
**Traceback**

Attached to https://github.com/airalab/robonomics/issues/60

**Description**

After some time of working in multicollator mode (about 15-20) collators the block production stop with errors in relay chain validators above.

Used 
* cumulus: master
* Polkadot: cumulus-branch

**Comment by bkchr** [comment]
We now also run into the same problem. I assume you have no idea on how to trigger this? :sweat_smile:

**Comment by akru** [comment]
Basically, it's a composite issue,
the first one is a synchronization issue, as I can see many collators have different chain height, it makes the process of finding the best height difficult, in my opinion.
The second, I got a couple of reports of crashes: https://github.com/airalab/robonomics/issues/58, https://github.com/airalab/robonomics/issues/60, and https://github.com/airalab/robonomics/issues/62. It looks like issues connected to network latency, maybe some checks and delays solves it. So, I'm not so close with cumulus internals to understand well what's happening here.

I'll relaunch parachain and let you known results this week. Please keep in touch. @bkchr

**Comment by bkchr** [comment]
To give you an update, I could reproduce this. This looks like a really nasty bug and I'm working on it, sadly I can not give any eta.

**Comment by akru** [comment]
@bkchr thank you very much, looking forward to any updates!

**Comment by bkchr** [comment]
@akru https://github.com/paritytech/cumulus/pull/159 this should hopefully fix it for now, however I still don't have a proper solution.

**Comment by akru** [comment]
Thank you @bkchr, looking forward to try it

**Comment by akru** [comment]
So, I can say that block stuck issue resolved with the latest master, great!

But synchronization issues stay happens, for example on [public node](https://parachain.robonomics.network) every 1-2 minutes happens delay for 10-15 blocks. As a result, any trivial actions with the parachain make troubles for the end-user.

@bkchr could you suggest some debuggin steps to explain this issues in technical details?

**Comment by bkchr** [comment]
@akru The synchronization issues? Could you provide me with logs of these issues? (Please in a new issue) I'm happy with normal logs to see if this is related to the issue linked below. And if you can run it with `-lsync=trace`, that would be even more helpful.

I'm already aware of one issue when syncing: https://github.com/paritytech/cumulus/issues/147

This will be one of the next tasks.

Regarding this issue, I now finally found the underlying problem and I'm just preparing to open the pr in Substrate to fix this issue :)

**Comment by akru** [comment]
@bkchr Thank you very much! Thats wonderful news. So, I'll relaunch node with synchronization tracing turned on.

**Comment by akru** [comment]
@bkchr Unfortunately I got similar behavior again on code with your fixes: https://github.com/airalab/robonomics/issues/67

What do you think about it?

**Comment by bkchr** [comment]
Hey, yeah I have seen similar errors already. But I'm not sure where they come from :/

However this is quite different to the one you reported here, because the new one is a storage root mismatch on import which you can also get on a "normal" blockchain. Did you updated your runtime in some way and the issue reporter used an older node version?

**Comment by akru** [comment]
@bkchr issue reporter uses latest version, runtime upgrades wasn’t applied yet. So, currently I use cumulus at 9603b2fe5f2ea2955a4a8a34742c58e8a4f9bc54. Any changes coming around it in latest commits?

**Comment by bkchr** [comment]
Nothing that should cause this AFAIK.

Is this reproducible?

**Comment by akru** [comment]
@bkchr I’ll let you known when can reproduce it.
