### ISSUE TITLE
Telemetry cannot be used for parachain and for relaychain at the same time

### ISSUE THREAD

**Issue by cecton** [paritytech/cumulus#149]
This is a limitation in substrate. The telemetry must be initialized only once.

Related to https://github.com/paritytech/substrate/pull/6666 (this is not a fix as this doesn't allow using the telemetry on the parachain and the relaychain at the same time)

**Comment by cecton** [comment]
Partial fix has been merged to substrate: https://github.com/paritytech/substrate/pull/6666

This will allow enabling the telemetry for the parachain but not for the relaychain OR: for the relaychain but not for the parachain.

(This fix is not on cumulus yet, need to update substrate)

**Comment by cecton** [comment]
I looked at the code and I don't think there is a way to distinguish between the telemetry of the para chain and the relay chain as logs are global and everything is sent to the telemetry worker (relay and para chain logs).

There are 2 ways we can go from there:
1. **Enforce 1**: We decide to forbid initializing multiple telemetries in substrate (panicking with a clear and understandable error message saying that only one node can initialize the telemetry)
2. **Multiplex**: We decide to allow multiple telemetries but all the recipients will receive the exact same logs

There might a a third way: we remove the use of set_global_logger and we pass a logger instance everywhere and adapt the code accordingly. It's probably as massive as it sounds.

**Comment by cecton** [comment]
Ah I just found #154 

So we should take option 3 and there is a feature for that. Cool!

**Comment by bkchr** [comment]
> There might a a third way: we remove the use of set_global_logger and we pass a logger instance everywhere and adapt the code accordingly. It's probably as massive as it sounds.

This one

**Comment by cecton** [comment]
Related to #19 : I guess if we have a specific logger instance per node we can easily improve the prefixing

**Comment by bkchr** [comment]
Logging without a singleton is a pain in the ass.
