### ISSUE TITLE
--parachain-id is required even if the parachain id is in the spec file already

### ISSUE THREAD

**Issue by cecton** [paritytech/cumulus#157]
When we deployed trick and track all the nodes were not using the correct parachain ID. I added `--parachain-id 110` (or 120) and that fixed it. We shouldn't need to do that as the parachain id is already known.

**Comment by bkchr** [comment]
Fixed by: https://github.com/paritytech/cumulus/commit/e3d98e67e9d22d7536bc3e9c5f7c3da4deed8dd5
