### ISSUE TITLE
Stop Producing Block

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/cumulus#1571]
See https://github.com/darwinia-network/darwinia-parachain/issues/128.

I'm not sure if this is a bug. But this actually happened on our Kusama parachain.

**Comment by bkchr** [comment]
If you have more than one node on your Parachain this can not happen: https://github.com/paritytech/cumulus/pull/927

Pov recovery should restore the block and distribute it in the network.

**Comment by AurevoirXavier** [comment]
But we have 3 collator nodes. 1 offline, 2 online.

**Comment by bkchr** [comment]
> And two other collators online but can not produce blocks.

Same applies for collators. Collators are also running pov recovery. So this happened to your chain and it is now bricked? Or what? 

Could you maybe give some more explanation on what happened.

**Comment by AurevoirXavier** [comment]
It bricked.

I have to call the offline validator to reboot his node. After that, the chain recovered.

I don't have more information now.

If I reencounter the problem, I'll reopen this issue.

**Comment by bkchr** [comment]
How many nodes did you had running as this collator failed? How many collators? And on what version are these nodes? Did you had any error logs from pov recovery?

**Comment by AurevoirXavier** [comment]
3 nodes, all of them are collators.
Version is polkadot-v0.9.17.

Sorry, I don't have the old logs.

---

Now we have upgraded to polkadot-v0.9.25.
Let's wait and see.
This might be resolved.
