### ISSUE TITLE
Implement proper testing for not validator mode

### ISSUE THREAD

**Issue by cecton** [paritytech/cumulus#168]
We need a test that will ensure that the relay chain blocks are produced properly in not validator mode.

For that we can run a polkadot node and a not-validator cumulus process. Relay chain blocks should be produced.

**Comment by rphmeier** [comment]
Why have you chosen this test for non-validator mode?

Validators in Cumulus don't produce relay-chain blocks anyway. It's the relay-chain validators who do that. I would expect that the only thing a non-validator needs to do is synchronize the chain.

**Comment by bkchr** [comment]
Yeah, the pr description is not correct. What she wanted to say is that a collator running in non-validator mode should be able to sync blocks from the tip of the parachain. However, that requires that there is a second collator that is running in validator mode.

**Comment by cecton** [comment]
Closed by #167 5bbab68f0208e4573b16c87ee622209350bb96e6
