### ISSUE TITLE
babe replace aura

### ISSUE THREAD

**Issue by wetalice** [paritytech/cumulus#1692]
I want to make the block generation more random, so I want to replace the aura consensus with babe. can you provide template?

**Comment by bkchr** [comment]
BABE is not supported by Parachains. We will also not bring support for BABE. When Sassafras is ready, this will be supported by Parachains.

If you need some randomness in the collator selection, take a look at: https://github.com/PureStake/nimbus

**Comment by zxshask** [comment]
> BABE is not supported by Parachains. We will also not bring support for BABE. When Sassafras is ready, this will be supported by Parachains.
> 
> If you need some randomness in the collator selection, take a look at: https://github.com/PureStake/nimbus

I think it might be cooler if the parachain supports babe. Why not consider replacing Aura with babe?

**Comment by bkchr** [comment]
Because there will be Sassafras, no need for BABE.

**Comment by zxshask** [comment]
> Sassafras

I'm very interested in Sassafras. Can you tell me what it is and when it will be developed?

**Comment by zxshask** [comment]
> Because there will be Sassafras, no need for BABE.

I'm very interested in Sassafras.could you tell me what it is and when it will be developed?

**Comment by bkchr** [comment]
https://research.web3.foundation/en/latest/polkadot/block-production/SASSAFRAS.html

**Comment by JimYam** [comment]
> https://research.web3.foundation/en/latest/polkadot/block-production/SASSAFRAS.html

Perfect. When exactly will development be completed.

**Comment by bkchr** [comment]
It is being worked on. Maybe next year for parachains.
