### ISSUE TITLE
Collator build fails on the first run

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#174]
On the `rococo_v1` tag (and probably on master) when I do a clean checkout and build the collator with `cargo build --release -p rococo-collator`, the command fails with the following ([full error](https://gist.github.com/JoshOrndorff/a845f1fd7b8464f0e1d2fae1df16a9cc)):

```
error: failed to run custom build command for `westend-runtime v0.8.22 (https://github.com/paritytech/polkadot?branch=rococo-branch#e9164236)`
```

Running the exact same command without changing anything succeeds the second time.

**Comment by bkchr** [comment]
Hey, I need more output. I never had such a problem :)

**Comment by JoshOrndorff** [comment]
The full output is here https://gist.github.com/JoshOrndorff/a845f1fd7b8464f0e1d2fae1df16a9cc

**Comment by bkchr** [comment]
Yeah that is a bug in the `wasm-builder`, which I still don't know on how to solve it..

**Comment by cecton** [comment]
I'm so used to it I don't even see it anymore

**Comment by JoshOrndorff** [comment]
This issue is now preventing the docker image from building in the cumulus workshop. Is there a workaround? The best thing I can think of is to run `cargo build --release` three times in the `Dockerfile`. That's how I get around it locally.

**Comment by riusricardo** [comment]
> run `cargo build --release` three times in the `Dockerfile` 

Is this a magic spell @JoshOrndorff ?

**Comment by bkchr** [comment]
I really need to fix this. I already invested some thoughts and maybe just should get started and try my ideas.

**Comment by tolak** [comment]
Did you sovled it? My VSCode always show me this error and it looks like makes the rust-analyzer extension  stop working

**Comment by bkchr** [comment]
Nope still exists.

**Comment by cecton** [comment]
Wow solved?! :tada: GREAT!!!
