### ISSUE TITLE
Fix pov-recovery zombienet test

### ISSUE THREAD

**Issue by skunert** [paritytech/cumulus#1744]
The test as it is currently on master is missing `--disable-block-announcements` on the charlie node. However, adding this flag makes the test flaky. 

Todos: 
- Disable block announcements on charlie
- Investigate issues with pov-recovery, why is it sometimes failing?

**Comment by bkchr** [comment]
Was this done now with the merged PR?

**Comment by skunert** [comment]
One more thing to do, I would like to verify that after the fixes pov-recovery test also works properly with rpc collators. Will experiment and after another PR close this issue.
