### ISSUE TITLE
Enabling Offchain workers in  cumulus/substrate parachain template

### ISSUE THREAD

**Issue by rafat** [paritytech/cumulus#1849]
I know the way to enable Offchain workers in a solo chain is to edit the service.rs as per the documentation and it works perfectly. I have tried to make equivalent changes to the service.rs in my parachain but offchain_workers function is never triggered. Can anyone tell me if there is a way to make it happen for a parachain because I can't quite figure out all the configuration changes that need to be done in this case ? I am running the parachain with the --offchain-worker=always flag as well but the offchain worker hook is never called.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/e7cb51b325c19012cc5c269105c43717093f45b0/bin/node/cli/src/service.rs#L368-L375

Add this code to your project.
