### ISSUE TITLE
Log filtering for the Polkadot node

### ISSUE THREAD

**Issue by rphmeier** [paritytech/cumulus#19]
The logs of the embedded Polkadot node are interleaved with the logs of the Cumulus node. There should be some filtering applied so that we see mostly the logs of the Cumulus node and only warnings / periodic status updates from the Polkadot chain.

**Comment by bkchr** [comment]
An easy starting point would be to create a custom informant that logs the Parachain/Polkadot together.

**Comment by bkchr** [comment]
We should extend the `informant` in Substrate to accept a prefix. The prefixes in our case would be something like: `Parachain` and `RelayChain`. The prefix is set by the user of the crate on initialization. The prefix should be an `Option<String>`. After these changes are done, we implement the changes in Cumulus and make sure that we initialize the informant for the relay chain and the parachain.

**Comment by bkchr** [comment]
Reopening as we solved one part, but most of the logs are still not prefixed.
