### ISSUE TITLE
error: package ID specification `polkadot-collator` did not match any packages

### ISSUE THREAD

**Issue by Jackwumingjie** [paritytech/cumulus#1931]
How to solve the issue as the picture 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/39093109/205032514-a90f5249-6f06-4656-8e1e-0dd98b26df85.png">

**Comment by bkontur** [comment]
polkadot-collator -> polkadot-parachain

try one of those (depends on your checkouted version)

```
cargo build --release --locked -p polkadot-parachain@0.9.320
```

```
cargo build --release --locked -p polkadot-parachain-bin
```

**Comment by bkontur** [comment]
@Jackwumingjie 
what is your setup `cargo -V -vvv` ?

**Comment by Jackwumingjie** [comment]
> cargo -V -vvv

<img width="641" alt="image" src="https://user-images.githubusercontent.com/39093109/205043725-e0341122-af8b-4709-9f4c-8332515f700b.png">

**Comment by bkontur** [comment]
@Jackwumingjie 
can you, please, try nightly version? 
```
cargo +nightly build --release --locked -p polkadot-parachain@0.9.320
or
cargo +nightly build --release --locked -p polkadot-parachain-bin
```

**Comment by Jackwumingjie** [comment]
> cargo +nightly build --release --locked -p polkadot-parachain-bin

<img width="983" alt="image" src="https://user-images.githubusercontent.com/39093109/205051214-3a6bd705-b608-403c-a1f0-380ae05a53a8.png">
@bkontur

**Comment by bkontur** [comment]
@Jackwumingjie 
try this:
```
rustup -V
rustup install nightly-2022-10-21
rustup default nightly
rustup -V
cargo -V -vvv
```

**Comment by bkontur** [comment]
@Jackwumingjie did it work for you?

**Comment by Jackwumingjie** [comment]
> 

I use the rust1.64.0 to build the node successfully.
@bkontur

**Comment by bkontur** [comment]
@Jackwumingjie 
closing, if no other issues
