### ISSUE TITLE
statemint block date/time when timestamp.set is missing

### ISSUE THREAD

**Issue by hub-il** [paritytech/cumulus#2011]
It looks like for some blocks [example here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemint.api.onfinality.io%2Fpublic-ws#/explorer/query/1675) the `timestamp.set` extrinsic is not present.  In these instances is it possible to know from the blockchain data/api the date and time the block was finalized?  If so, how?  At some point do all blocks have the `timestamp.set` extrinsic?

**Comment by bkchr** [comment]
> At some point do all blocks have the `timestamp.set` extrinsic?

Yes: https://substrate.stackexchange.com/a/5894/73

> In these instances is it possible to know from the blockchain data/api the date and time the block was finalized?

You never know when a block was finalized. If you need a rough time when the block was build, you can use the `relayParentNumber` in the `setValidationData`.
