### ISSUE TITLE
Current version of rococo-branch is incompatible with current version of cumulus

### ISSUE THREAD

**Issue by Veniamin** [paritytech/cumulus#215]
I am getting this error while trying to build new substrate with cumulus:

fn build<Spawner>(
    |              ^^^^^^^ found 2 type parameters, expected 4
...
433 |         polkadot_network: impl CollatorNetwork + SyncOracle + Clone + 'static,
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `impl Trait` introduces an implicit type parameter

 Can be reproduced by cloning https://github.com/substrate-developer-hub/substrate-parachain-template repo and building without cargo.lock file from repo.

**Comment by bkchr** [comment]
Will be fixed by: https://github.com/paritytech/cumulus/pull/201

**Comment by cecton** [comment]
Should be fixed now.
