### ISSUE TITLE
Get parachain ID from relaychain

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#221]
Currently to deploy a parachain, we will need to know the parachain ID upfront and have it included in the genesis state.

This can be error-prone and requires generate genesis state after a parachain win a slot. We cannot get everything ready before a crowdsale starts.

Relaychain should be able to send some message to the parachain to tell what's its parachain id so there is one less way to configure it incorrectly.

**Comment by gavofyork** [comment]
> This can be error-prone and requires generate genesis state after a parachain win a slot

No longer true. The parachain ID is pre-reserved ahead of time and has nothing to do with slot leases any more. That should alleviate this issue.

**Comment by gavofyork** [comment]
> Relaychain should be able to send some message to the parachain to tell what's its parachain id so there is one less way to configure it incorrectly.

I doubt any of cumulus could work to deliver any such message unless its parachain ID is already known.

**Comment by xlc** [comment]
Right. So we will know parachain ID prior genesis block so we can just hardcode the value.

Still a nice to have but not a priority at all.

**Comment by gavofyork** [comment]
I really don't see how it's even logically possible. How could cumulus even connect with validators if it doesn't already know its parachain ID? what if two otherwise equal parachains begin at the same time? how are the collator nodes to know which is which?

**Comment by xlc** [comment]
Make sense. We should be able to deploy two identical parachain on same slot and without hardcode the parachain ID upfront it will be hard to distinguish things.
