### ISSUE TITLE
Parachain nodes hang intermittently after relay chain re-org

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#225]
# Overview

The Moonbeam team is unable to run a parachain with more than one parachain node (collators or otherwise) for any appreciable amount of time because the parachain nodes will stop importing and syncing blocks. The problem was first reported in #219 and this issue is my (ongoing) attempt to find the underlying cause and make it reproducible.

# Miscellaneous Findings

* The hangs happen much **more frequently when grandpa is not running** on the relay chain.
* Although I can easily reproduce hangs, I have not been able to reproduce the exact crash reported in #219.
* The hangs always happen **immediately after a relay chain re-org**, but not every relay re-org causes a hang.
* There is always **at least one collator that does not get stuck** (which allows us to run a single-collator parachain without issues).

# Captured logs

I've captured complete logs for three different runs of a local relay-para network, and I'm **happy to collect more** as desired to hunt this bug down. Each of these gists contains a `0description.md` file that explains the setup for that particular run.

* [First run](https://gist.github.com/JoshOrndorff/fb8230fd059449395730814098d60051) - Dang, the `0description.md` file is empty :facepalm:
* [Second run](https://gist.github.com/JoshOrndorff/57842a1da7ea464a235afaa5499a721e)
* [Third run](https://gist.github.com/JoshOrndorff/9dc554f7435c1c57aed65635dc1ccb1d)- Using parachain template

# General Reproduction Steps

This issue can be reproduced in any relay-para network running a multi-node moonbeam parachain. These steps are a good starting point for creating that. The captured runs above show a few variations.

## Relay chain

```bash
# Build Polkadot from the tip of the `rococo-branch`. For most of my testing I was using `9d2324b`.
git checkout rococo-branch
cargo build --release

# Generate a raw rococo-local chain spec
polkadot build-spec --chain rococo-local --raw --disable-default-bootnode > rococo-local.json

# Start Alice and Bob -- remember, the issue happens more with grandpa disabled
polkadot --chain rococo-local.json --tmp --ws-port 9944 --port 30333 --rpc-port 9933 --alice --no-grandpa
polkadot --chain rococo-local.json --tmp --ws-port 9945 --port 30334 --rpc-port 9934 --bob --no-grandpa
```
## Parachain

I did most of the testing in the logs captured above with `a812449` but it is still happening with moonbeam master.

```bash
# Build the moonbeam parachain node.
git clone https://github.com/PureStake/moonbeam.git
cd moonbeam
cargo build --release

# Start a collator(s) (Start more collators or parachain full nodes accordingly; at least two paranodes are required)
moonbase-alphanet --port 31052 --rpc-port 31053 --ws-port 31054 --validator  --tmp --chain build/alphanet/moonbase-alphanet-specs-plain.json -- --port 31042 --rpc-port 31043 --ws-port 31044 --chain rococo-local.json

# Register the Parachain
polkadot-js-api \
    --ws "ws://localhost:9944" \
    --sudo \
    --seed "//Alice" \
    tx.registrar.registerPara \
        1000 \
        "{\"scheduling\":\"Always\"}" \
        @"$PARACHAIN_WASM" \
        "$(cat $PARACHAIN_GENESIS)"
```

**Comment by JoshOrndorff** [comment]
I've explored the latest cumulus master that uses Parachains V1 in hopes that this issue was solved in the meantime. The issue doesn't appear as described here anymore, but a similar issue that prevents a multi-collator setup does exist and I've described it in https://github.com/paritytech/cumulus/issues/241

**Comment by bkchr** [comment]
Should we still keep this open until synching between multiple parachain nodes works again?

**Comment by JoshOrndorff** [comment]
I prefer to keep it open since we don't know whether it is solved yet. But I don't feel that strongly. If we solve #241 and this issue comes back we can always re-open it.

**Comment by bkchr** [comment]
No fine by me to keep it open. When you come back to report the status :P

**Comment by JoshOrndorff** [comment]
This appears to be fixed on the latest cumulus master, so I'll close this. If it re-appears after more thorough testing, I'll write it up again based on the latest code.

**Comment by dt665m** [comment]
Hey guys, I'm seeing this behavior still on branch polkadot-v0.9.4 running two local rococo 0.9.4 relay nodes and a single collator.  My test setup is a 3 container docker-compose with 2 relay nodes and 1 parachain node, using sudo to register the parachain as normal.  

After a bit of time, this happens:
```
2021-06-30 15:37:42.164  INFO tokio-runtime-worker afg: [Relaychain] 👴 Imported justification for block #81 that triggers command Changing authorities, signaling voter.    
2021-06-30 15:37:42.174  INFO tokio-runtime-worker sc_network::protocol: [Relaychain] 💔 Invalid justification provided by 12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN for #0x5780…50ad    
```

and not much longer it (0x5780...) finalizes:
```
 2021-06-30 15:37:44.164  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (1 peers), best: #84 (0x05a4…a5b8), finalized #81 (0x5780…50ad), ⬇ 1.2kiB/s ⬆ 0.3kiB/s    
```

However, the cumulus client gets stuck in a block import loop along with this:
```
2021-06-30 15:38:12.069  WARN tokio-runtime-worker parachain::collator-protocol: [Relaychain] Collation wasn't advertised to any validator. candidate_hash=0x1e3ee4d40fedf7042a1f3c01afdeb969ab68e7643bec1c92de5e53e046b21404 pov_hash=0xcb481a059e24ed64ccd443f013bf93c7b8f938c84e1822f4556d2154b8b16411
```

The only way to make progress is to restart the parachain node.  @bkchr any ideas what the best way to debug this is?

**Comment by NukeManDan** [comment]
Updating to at least 0.9.5 should resolve `[Relaychain] 💔 Invalid justification provided ...` errors like this. 
Please update to 0.9.7 as it is the latest available (at time of writting) https://github.com/paritytech/cumulus/tree/polkadot-v0.9.7

**Comment by dt665m** [comment]
> Updating to at least 0.9.5 should resolve `[Relaychain] 💔 Invalid justification provided ...` errors like this.
> Please update to 0.9.7 as it is the latest available (at time of writting) https://github.com/paritytech/cumulus/tree/polkadot-v0.9.7

did the trick, thanks!
