### ISSUE TITLE
Token dealer should support different accounts on relay chain and parachains

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#226]
In general parachains will not have the same account Id type as the Relay chain. When including the token dealer pallet in such runtimes, it incorrectly determines that the relay chain has the same AccountId type.

This can be avoided by introducing an additional associated type into the token dealer's configuration trait. Maybe something like this would be enough.

```rust
pub trait Trait: frame_system::Trait {
	/// The sender of upward messages.
	type UpwardMessageSender: UpwardMessageSender<Self::UpwardMessage>;

	/// The upward message type used by the Parachain runtime.
	type UpwardMessage: codec::Codec + BalancesMessage<Self::RelayAccountId, BalanceOf<Self>>;

	/// The AccountId type used by the relay chain.
	type RelayAccountId: codec::Codec; //TODO Are there other bounds I need here?

	// --snip--
}
```

**Comment by bkchr** [comment]
This was never a crate that was thought of being used by others, it was just for demonstration purposes.

And it will be gone with: https://github.com/paritytech/cumulus/pull/207
