### ISSUE TITLE
[DOC] Unable to register a parachain

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/cumulus#23]
I'm trying to register a parachain following the part 'Running a collator'. However, when i try to register a parachain, point 6, i'm not able to do it since the instructions does not corrispond to the current web UI version (i think the documentation is not updated)

**Comment by damianoazzolini** [comment]
I've made some progress and i've found the section (registerPara(id,info,code,initial_head_data)) where i can register a parachain. However, i always get this error on the cumulus node:
DispatchError
23
0
RequireRootOrigin
Any idea why?

**Comment by bkchr** [comment]
Yeah, the js-apps are currently incompatible. Sorry! I'm working on something for Cumulus and if that is ready I will make sure again that the repository is up-to-date again.
