### ISSUE TITLE
Despite using 'relay-chain-rpc-urls' node is still kind of starting process for relaynode

### ISSUE THREAD

**Issue by tugytur** [paritytech/cumulus#2307]
Despite using `--relay-chain-rpc-urls=` the `polkadot-parachain` is still starting part of the relay chain node process.

version: `polkadot-parachain_v0.9.380 0.9.380-fe24f39507f`

All Arguments:
```
ExecStart=/usr/local/bin/polkadot-parachain \
        --name="rpcsme-001" \
        --public-addr=/ip4/X.X.X.X/tcp/30342 \
        --listen-addr=/ip4/X.X.X.X/tcp/30342 \
        --chain=statemine \
        --pruning=archive \
        --database=paritydb \
        --prometheus-port=9615 \
        --rpc-port 9933 \
        --ws-port 9944 \
        --no-telemetry \
        --no-hardware-benchmarks \
        --no-mdns \
        --no-private-ip \
        --max-runtime-instances=1 \
        --in-peers=5 \
        --out-peers=5 \
        --max-parallel-downloads=2 \
        --runtime-cache-size=1 \
        --execution=wasm \
        --wasm-execution=compiled \
        --rpc-methods=safe \
        --rpc-cors=all \
        --relay-chain-rpc-urls="ws://X.X.X.X:9944" \
        --base-path=/var/blockchain
```

With only this, the process is still listening on the default relaychain sync port:

```
tcp LISTEN  0    1024   0.0.0.0:30334      0.0.0.0:*    users:(("polkadot-parach",pid=17919,fd=367)) uid:996 ino:1193195 sk:d cgroup:/system.slice/blockchain.service <->
tcp LISTEN  0    1024   X.X.X.X:30342      0.0.0.0:*   users:(("polkadot-parach",pid=17919,fd=393)) uid:996 ino:1193197 sk:e cgroup:/system.slice/blockchain.service <->
tcp LISTEN  0    1024   [::]:30334         [::]:*   users:(("polkadot-parach",pid=17919,fd=365)) uid:996 ino:1193193 sk:f cgroup:/system.slice/blockchain.service v6only:1 <->
```

`mDNS` discovery is also enabled for the relay chain part.

It's also gets broadcasted to the network that here should be a Relaychain node, which doesn't exist.
```
Discovered new external address for our node: /ip4/X.X.X.X/tcp/30334/ws/p2p/12D3KooWEcdKx2yYrMxwMgUNXoU2My5HCCA9KgsAJifvyXVoR4hD
```

This leads to a lot of unnecessary traffic, in our case we have multiple  system-chain nodes behind NAT.

![image](https://user-images.githubusercontent.com/33746108/224383367-f950cc0c-b262-4f21-b852-8f212689d2e5.png)

**Comment by bkchr** [comment]
For collators we still need the networking, as we send out collations using the relay chain network. However, for normal full nodes we don't need to run any networking. Now that syncing was removed from `sc-network`, we should maybe be able to run the Polkadot protocols using the parachain networking instance. But that will also require Kademlia support for different genesis hashes, which we recently removed :grimacing: 

CC @skunert

**Comment by skunert** [comment]
This is not entirely true. We start the minimal node with some subsystems also for full nodes. It is needed for availability-recovery subsystem and pov-recovery. 
As @bkchr said we could look into merging the networking, but its future work.

**Comment by bkchr** [comment]
Ahh availability and pov recovery! But yeah, it should really be possible to run the stuff on the parachain networking instance.
