### ISSUE TITLE
Not charging for proof weight

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#2322]
https://github.com/paritytech/cumulus/blob/66887505e6c5ef89ce9f88fc4ec368eb858b1b92/parachains/runtimes/assets/statemint/src/constants.rs#L64

https://github.com/paritytech/cumulus/blob/66887505e6c5ef89ce9f88fc4ec368eb858b1b92/parachains/runtimes/assets/statemint/src/xcm_config.rs#L292-L293

**Comment by joepetrowski** [comment]
Do you mean proof size?

**Comment by xlc** [comment]
Yes. Proof size in weight.

**Comment by joepetrowski** [comment]
AFAIK the migration to weights v2 is not complete, @ggwpez can you comment on the plan to address this?

**Comment by ggwpez** [comment]
Ah right - did not realize that this would take effect without editing Cumulus, since we use the builtin template here.  
I will open an MR to do a trivial charging implementation.

**Comment by bkontur** [comment]
@ggwpez 
do you mean this template, which is still using `from_ref_time` https://github.com/paritytech/cumulus/blob/master/templates/xcm-bench-template.hbs#L49 ?
