### ISSUE TITLE
fix error message for reserved transfer into Statemint

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#2399]
https://github.com/paritytech/cumulus/blob/066db6b95f6f83d38893d5151946866bb401b4f5/parachains/integration-tests/statemint/xcm/1_dmp.yml#L221

Right now the error to reserve transfer DOT to Statemint is `WeightNotComputable` which is misleading. I am not sure how the [source error `UntrustedReserveLocation`](https://github.com/paritytech/polkadot/blob/bebd1a788ecccfa1a6adc61004e4f700988f40d4/xcm/xcm-executor/src/lib.rs#L491) is translated to `WeightNotComputable` but it needs a fix.

**Comment by joepetrowski** [comment]
You are looking at the wrong integration tests. Those are [being removed](https://github.com/paritytech/cumulus/pull/2265) from Cumulus and being maintained in their own repo. You can see that has the [message you expect](https://github.com/paritytech/parachains-integration-tests/blob/e4f9e47/examples/statemint/xcm/1_dmp.yml#L231).
