### ISSUE TITLE
Collator node thrown incorrect warnings on startup

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#24]
When starting the collator node, it reliably prints errors like

```
Unable to bind server to 127.0.0.1:9955. Trying random port.
Not a valid bootnode address: /ip4/127.0.0.1/tcp/30333/QmbQMG8VWKumRyXg47UixQiosUMP2nWRsmWRojqDqJTG9t
```

These messages do not correspond to actual underlying errors. UIs still connect to the websocket port correctly, and the collator still peers with the bootnode at the supposedly invalid address. Possibly related to #19

**Comment by bkchr** [comment]
As written in #34 we should provide some sensible defaults for the relay chain node.

**Comment by cecton** [comment]
This error still exist:
```
Error on libp2p listener ListenerId(1): Address already in use (os error 98)
```

**Comment by zhangtianai** [comment]
```
2020-09-04 22:43:43 📪 Libp2p listener () closed: Address already in use (os error 48)
2020-09-04 22:43:43 📪 Libp2p listener () closed: Address already in use (os error 48)
```
