### ISSUE TITLE
Multiple Paranodes: only  one collator syncs the parachain

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#241]
When running a parachain with multiple nodes, only a single collator is able to sync the parachain. All collators and parachain full nodes sync the relay chain and peer together. This issue can be reproduced using Polkadot `cfde0767` and Cumulus `f92e419` (latest master at time of writing).

To help debug, I've collected the **[complete logs](https://gist.github.com/JoshOrndorff/0295b9e4a43b4a71e43d190bb97a0e63)** of a network with two validators, two collators, and a single non-collating parachain full node. The test network from which these logs were collected is described below. It does not use any custom code or repository; Just Polkadot and Cumulus.

## Launch the Relay Chain

```bash
# Compile Polkadot with the real overseer feature
git checkout cfde0767
cargo build --release --features=real-overseer
./target/release/polkadot --version

# Generate a raw chain spec
./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode --raw > rococo-local-cfde-real-overseer.json

# Alice
./target/release/polkadot --chain rococo-local-cfde-real-overseer.json --alice --tmp --discover-local

# Bob (In a separate terminal)
./target/release/polkadot --chain rococo-local-cfde-real-overseer.json --bob --tmp --discover-local --port 30334
```

## Launch the Parachain

```bash
# Compile
git checkout f92e419
cargo build --release
./target/release/rococo-collator --version

# Export genesis state
./target/release/rococo-collator export-genesis-state --parachain-id 200 > genesis-state

# Export genesis wasm
./target/release/rococo-collator export-genesis-wasm > genesis-wasm

# Collator1
./target/release/rococo-collator --collator --discover-local --tmp --parachain-id 200 --port 40335 --ws-port 9946 -- --execution wasm --chain ../polkadot/rococo-local-cfde-real-overseer.json --port 30335 --discover-local

# Collator2
./target/release/rococo-collator --collator --discover-local --tmp --parachain-id 200 --port 40336 --ws-port 9947 -- --execution wasm --chain ../polkadot/rococo-local-cfde-real-overseer.json --port 30336 --discover-local

# Parachain Full Node 1
./target/release/rococo-collator --discover-local --tmp --parachain-id 200 --port 40337 --ws-port 9948 -- --execution wasm --chain ../polkadot/rococo-local-cfde-real-overseer.json --port 30337 --discover-local
```

## Register the parachain
![image](https://user-images.githubusercontent.com/2915325/99548884-1be13580-2987-11eb-9a8b-20be658d34f9.png)

You can use [these types](https://github.com/KILTprotocol/kilt-parachain#152-polkadot-apps-extrinsics-error) in Apps so that the UI can decode the inBlock event.

## Observed Results

After registration, one of the collators (for me it seems to be the first one I start; haven't tested that part rigorously yet) will start authoring building a proper parachain and getting candidates included in the relay chain. The second collator and full node do not import any of the parachain blocks despite being peered with the working collator. The second collator does not author any blocks.

## Expected Results

After registration, both collators should start authoring blocks, and all parachain nodes should sync the parachain.

## Other possibly relevant observations
* Right after the registration transaction, All three parachain nodes report `[0xb6c49e5e587a5d7c616bb3f802f20b17dbdeeb95c37fec33d2b05bd240eb1fed] Extrinsic invalid` They report similar messages intermittently.

* The two parachain nodes that don't end up syncing the parachain regularly warn `AdvertiseCollation message is not expected on the collator side of the protocol` as reported in #239

**Comment by bkchr** [comment]
Very likely a duplicate of https://github.com/paritytech/cumulus/issues/229

**Comment by bkchr** [comment]
Please try with latest master

**Comment by JoshOrndorff** [comment]
Yes, this is fixed on latest master. Thanks @bkchr
