### ISSUE TITLE
Bridgehub lost peers, network appears down

### ISSUE THREAD

**Issue by senseless** [paritytech/cumulus#2450]
Hello,

It appears around 09:30 AM est 04/13 that block production has stopped on the bridgehub kusama chain. We've lost all peers on our nodes and are unable to see any data from the Parity operated bridgehub kusama rpc node.

Thanks

**Comment by ggwpez** [comment]
Devops reports that is is resolved. Can you confirm?  
Currently the node topology is too centralized…

**Comment by senseless** [comment]
> Devops reports that is is resolved. Can you confirm? Currently the node topology is too centralized…

Looks good now, thanks
