### ISSUE TITLE
Ensure outgoing XCMP respects unincluded segment

### ISSUE THREAD

**Issue by rphmeier** [paritytech/cumulus#2471]
@rphmeier 
```rust
/// A means of figuring out what outbound XCMP messages should be being sent.
pub trait XcmpMessageSource {
	/// Take a single XCMP message from the queue for the given `dest`, if one exists.
	fn take_outbound_messages(maximum_channels: usize) -> Vec<(ParaId, Vec<u8>)>;
}
```
I believe this trait not only should account for max messages taken from the storage, but also for segment limitations if we want to make this panic correct.
Probably primitives for segment should be extracted into common crate to be accessible from both pallets.

_Originally posted by @slumber in https://github.com/paritytech/cumulus/pull/2438#discussion_r1172857195_

**Comment by rphmeier** [comment]
Ok, UMP is fully addressed as-of https://github.com/paritytech/cumulus/pull/2501 . 

HRMP will require some tweaks to the `ChannelInfo` implementation in parachain-system. We need to compute _and_ store the remaining bandwidth for all channels during the inherent processing, and then use that to compute `max_size_now` correctly in the `ChannelInfo` implementation.

Investigating this also raised another issue, which is weight calculation. We need to calculate the weight of `on_finalize` in `on_initialize`, but the code executed in `on_finalize` depends on the values read out of the host config/storage proof in the `set_validation_data` inherent. See this comment for an explanation of what was done _before_ asynchronous backing: https://github.com/paritytech/cumulus/blob/58926285a219b61fd3865ec4eeebdf87b9b66566/pallets/parachain-system/src/lib.rs#L309-L326

We may need to adapt some similar strategy of "predicting" the amount of bandwidth we can use in `on_initialize` before we get the inherent data, and then using that as a maximum in `on_finalize`, although it's really inconvenient and stupid. It makes me think we need to come up with ways for the relay chain storage proof to be processed during `on_initialize` instead.

**Comment by xlc** [comment]
or use `on_post_inherent` to specify the weight https://github.com/paritytech/substrate/issues/9210

**Comment by bkchr** [comment]
> It makes me think we need to come up with ways for the relay chain storage proof to be processed during `on_initialize` instead. cc @bkchr @skunert @ggwpez any ideas?

This would be: https://github.com/paritytech/cumulus/issues/320

However, I don't think that we need this there. In general I would assume that the host configuration is changed in a way to allow "more". Reducing something is probably never gonna happen. Nevertheless, we can use the "old" host configuration to calculate the weight. We then just need to ensure to that `min(old_config.hrmp_max_message_num_per_candidate, new_config.hrmp_max_message_num_per_candidate)`. Then we are staying the weight we set in `on_initialize` and also honor the potential config updates.

**Comment by ggwpez** [comment]
Looks like the implementation of `XcmpMessageSource` in the `XcmpQueue` does respect the relay and receiver suspension logic.  
So in theory that `expect` should be fine, but we obviously need a test to ensure that the implementation is correct.

About the HostConfig/weight thing:  
Why is this being set in *every* block? The HostConfig only changes on Epoch changes, right? So most of the time your weight/bandwidth calculations should be correct when using the current config.    
Proper solution would probably be the `on_post_inherent` mentioned above…

**Comment by rphmeier** [comment]
It may be that only the number of channels we can send messages on impacts the weight, so that logic would remain correct. Still, we need to determine the maximum sizes at every block and then load that maximum repeatedly during the `ChannelInfo` implementation.

It would be cleaner for the `XcmpQueue` pallet to take an `&impl ChannelInfo` as an argument, so we could make it stateful and not have to load from storage on every request.

**Comment by rphmeier** [comment]
Turned out the simplest way to do this was to update the `RelevantMessagingState` in storage in `on_finalize`.

**Comment by slumber** [comment]
Closed by https://github.com/paritytech/cumulus/pull/2948
