### ISSUE TITLE
Cannot query the runtime API version: Api called for an unknown Block error in substrate-parachain-template

### ISSUE THREAD

**Issue by okalenyk** [paritytech/cumulus#2474]
An error occurs while trying to launch substrate-parachain-template based on polkadot/cumulus v0.9.37:

`Cannot query the runtime API version: Api called for an unknown Block: State already discarded for 0xb5ca6f77cde65f43b7dc8e2f551b6ff36327126392d08a99409531df0e7c0e1c`

The guide from [Substrate tutorial](https://docs.substrate.io/tutorials/build-a-parachain/acquire-a-testnet-slot/) is used to launch the parachain collator node.

There is similar question on Substrate Stack Exchange: https://substrate.stackexchange.com/questions/7038/start-parachain-collator-node-encounter-relay-chain-block-sync-problem

P.S. The parachain template works fine with polkadot/cumulus v0.9.32 with the similar chain spec.

**Comment by brunopgalvao** [comment]
Is this reproducible?

**Comment by okalenyk** [comment]
> Is this reproducible?

Yes. I've also just checked the polkadot-v0.9.38 and getting the same error there. Rolling back to v0.9.32 works just fine and starts syncing blocks.

**Comment by okalenyk** [comment]
> What Polkadot branch are you using? Is the sync stopping?

I'm using [autoupdate_polkadot-v0.9.37_2023-02-07_11-12-12](https://github.com/substrate-developer-hub/substrate-parachain-template/blob/autoupdate_polkadot-v0.9.37_2023-02-07_11-12-12/README.md) branch for `substrate-parachain-template`. Still a small tweak required to fix `" branch"` typo in Cargo files(seems like the auto-update script issue) to build correctly.

Seems like the sync is working but I didn't wait until it syncs up to the current rococo state so I'm not sure what happens then.

Btw, How much time is usually required to sync with rococo current state from scratch(it depends on bps speed for sure), but just curious. Is there a way to have an up-to date genesis that can be attached to the process to make sure you're synced in reasonable time?

**Comment by bkchr** [comment]
> Btw, How much time is usually required to sync with rococo current state from scratch(it depends on bps speed for sure), but just curious. Is there a way to have an up-to date genesis that can be attached to the process to make sure you're synced in reasonable time?

You can use `-- --sync warp` to warp sync the relay chain node in your parachain node.

These initial errors you mentioned should be fixed by using master.

**Comment by okalenyk** [comment]
> 

@bkchr, Thanks for reply. Seems like in the `polkadot-v0.9.41` the error was fixed. I'm not sure whether using master branch is a good idea for production builds so wanted to stick with some release version. 

Thanks for the clue regarding the warp sync. However, how do I know when sync is completed? It is showing me 

`2023-04-26 12:36:15 [Relaychain] ⏩ Warping, Downloading finality proofs, 15.97 Mib (7 peers), best: #0 (0x6408…063e), finalized #0 (0x6408…063e), ⬇ 2.1MiB/s ⬆ 2.0kiB/s`

all the time after node start.

I'm using the following command to run the parachain:

```
./target/release/parachain-template-node --collator \
  --chain raw-parachain-chainspec.json \
  --base-path /tmp/parachain/pubs-demo \
  --port 50333 \
  --ws-port 8855 \
  -- \
  --execution wasm \
  --chain rococo \
  --port 50343 \
  --ws-port 9988 \
  --sync warp
```

and in the chain spec I'm using `rococo` as the `relay_chain` and `Live` as the `chainType`.

**Comment by bkchr** [comment]
Yeah, Rococo is not working. We have done forced set changes of the authority set and warp sync doesn't like this.

**Comment by bkchr** [comment]
Closing this issue, as it should be solved.
