### ISSUE TITLE
OOM Westmint

### ISSUE THREAD

**Issue by Maharacha** [paritytech/cumulus#2494]
Version:  0.9.400
Chain: Westmint
Parameters: `--chain westmint --pruning archive --ws-external --ws-port 9966 --ws-max-connections 1000 --rpc-external --rpc-port 9933 --rpc-cors all --rpc-methods Safe --prometheus-external`

From resync of both Relay and Para DBs, this is the memory consumtion, currently having 64GB available memory.
![image](https://user-images.githubusercontent.com/5499769/235088550-4d3fe3ea-ce1c-4181-b4dc-fb51066320b1.png)

Log from start to first OOM:
[westmint_oom.log](https://github.com/paritytech/cumulus/files/11351340/westmint_oom.log)

**Comment by bkchr** [comment]
Did you compile the node yourself? What OS version are you using?

**Comment by bkchr** [comment]
Ty! Yeah I think the caching issue is the reason you are running out of memory!

**Comment by skunert** [comment]
Interesting :thinking: 


> Ty! Yeah I think the caching issue is the reason you are running out of memory!

At first glance, it does not sound like a caching issue but notification hoarding somewhere as you said in your first answer. The cache has a fixed maximum size, after all.

**Comment by Maharacha** [comment]
I enabled `-ldebug` on both relay and para if that helps. This is after a restart. It did not OOM so far but is stuck on a block.
https://drive.google.com/file/d/12mmUhBwxPn-QGdzSvFQN2aOG7jA-ILtN/view?usp=sharing
![image](https://user-images.githubusercontent.com/5499769/235134556-0c800208-667b-429a-9a5c-9f278f0d75fb.png)

**Comment by skunert** [comment]
I have the strong suspicion that this is related to https://github.com/paritytech/cumulus/issues/2495, I will run some more experiments. Also have some ideas on how to fix.

**Comment by Maharacha** [comment]
It is in sync and has been working well for a few days now. Constantly on ~11G memory usage. But it was a roller coaster to get there :smile:
