### ISSUE TITLE
Parachains registered at IDs other than 0 do not collate

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#25]
The example parachain node has a [hardcoded ID of 100](https://github.com/paritytech/cumulus/blob/master/test/parachain/src/main.rs#L32). When I follow the instructions to register the parachian, I use id 100 as instructed, and the registration extrinsic completes successfully. However, the collator **does not begin collating**. One hint from the relay chain node logs is `Local parachain duty is Some(LocalDuty { validation: Parachain(Id(0)) })`. I expected that value to be 100, not 0.

**Second Attempt**
Kill all parachain and relay chain nodes, and purge all chains. Start the relay chain again. Start the Collator again, this time try to register at id 0 despite the hard-coded id 100 in the collator code.
Same behavior as before. Now, the collator actually starts producing blocks despite the mismatch between hard-coded id and registered id.

**Third Attempt**
Modify the collator node to hard-code id 0, and recompile. Kill all nodes and purge all chains. Re-start the relay chain. Re-start the collator. Register at id 0. As in the second attempt, the collator now begins producing blocks as expected.

**Comment by JoshOrndorff** [comment]
Also just noticed that the non-hacked collator itself reports `ID(0)` upon startup.

```
Cumulus Test Parachain Collator
2019-11-29 12:19:27   version 0.1.0-x86_64-linux-gnu
2019-11-29 12:19:27   by Parity Technologies <admin@parity.io>, 2019
2019-11-29 12:19:27 Chain specification: Local Testnet
2019-11-29 12:19:27 Node name: agreeable-tomatoes-0019
2019-11-29 12:19:27 Roles: FULL
2019-11-29 12:19:27 Parachain id: Id(0)
```

**Comment by bkchr** [comment]
Works for me. Probably was related to not being up-to-date.
