### ISSUE TITLE
Relay chain stopped on inclusion error

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#256]
**Description**

I've launch 3 validators of polkadot (rococo_local_testnet chainspec) with single parachain, after 1641 block the relay chain block production stoped with error:

```
Dec 03 14:56:55 validator-03 polkadot[211931]: 2020-12-03 14:56:55  💤 Idle (4 peers), best: #1641 (0xce3c…6919), finalized #1639 (0x719b…d797), ⬇️ 0.8kiB/s ⬆️ 1.1kiB/s
Dec 03 14:57:00 validator-03 polkadot[211931]: 2020-12-03 14:57:00  🙌 Starting consensus session on top of parent 0xce3c31d262c85891b0f4445fc95be74661d48aedbd5c6be116dfdc1a49d76919
Dec 03 14:57:00 validator-03 polkadot[211931]: 2020-12-03 14:57:00  panicked at 'inclusion inherent data failed to decode: <wasm:stripped>', /root/polkadot/runtime/parachains/src/inclusion_inherent.rs:137:14
Dec 03 14:57:00 validator-03 polkadot[211931]: 2020-12-03 14:57:00  Encountered consensus error: ClientImport("Blockchain(Execution(Wasmi(Trap(Trap { kind: Unreachable }))))")
```

It looks critical, how can we fix it?

**Comment by bkchr** [comment]
To make sure, the same node binary was running for all these blocks? 

And did all relay chain nodes had this same error?

**Comment by akru** [comment]
@bkchr Yes, the binary was the same, and error spawn on all these nodes on these blocks.

**Comment by bkchr** [comment]
Did you had done anything special before?

The parachain was running before?

**Comment by akru** [comment]
So, the parachain was launched, I’ve apply new parachain using sudo wrapper, launch collator, after some time block production stoped. I’ll try to make it reproducible.

**Comment by bkchr** [comment]
Is the old network still running?

**Comment by akru** [comment]
Unfortunately, no

**Comment by bkchr** [comment]
Next time it would be nice to get the dbs :)

**Comment by akru** [comment]
Sure, I’ll try to repeat it, so, I’ll let you known next time.
