### ISSUE TITLE
Aura Consensus Hook should enforce the relay-parent slot is equal to the Aura slot

### ISSUE THREAD

**Issue by rphmeier** [paritytech/cumulus#2588]
https://github.com/paritytech/cumulus/pull/2551 introduced a `ConsensusHook` for Aura based on https://github.com/paritytech/cumulus/pull/2501 .

We require for Aura that the slot for parachains is set based on the slot of the relay-parent, as it's the only reliable indication of time we have access to within parachain runtimes. These checks are currently done through the `parachain_system::CheckInherents` trait that is evaluated during `validate_block`. Moving this check to the consensus hook would make it run during all block executions - both during `validate_block` and vanilla `execute_block` as used by parachain nodes. It is also a refactoring to make the logic more clear.

**Comment by slumber** [comment]
#2658
