### ISSUE TITLE
Subcommand to purge embedded relay chain

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#259]
Because parachain node include embedded relay chain nodes, they also have a relay chain block database. It will be useful to be able to purge that relay chain just as we can purge the parachain.

Maybe something like
```
./parachain-node purge-relay --base-path /collator1
```

**Comment by bkchr** [comment]
You only want to merge the relay chain db and not the one from the parachain?

**Comment by JoshOrndorff** [comment]
Well, I want the ability to:
1. purge just the parachain
1. purge both the parachain and relay chain

I don't need a way to purge just the relay chain at the moment if you have other ideas.

**Comment by bkchr** [comment]
Currently we only support 2. :D

**Comment by bkchr** [comment]
@cecton We should probably replace the default Substrate purge cmd with a cumulus specific one. This should be exposed by a new crate `cumulus-cli`.

**Comment by cecton** [comment]
> Currently we only support 2. :D

Actually I think we just had option 1 because it deleted only the "db" directory. In my PR I added the option to purge the relay chain.

Maybe we should have 3 options?

1. Purge all the things :broom: \o
2. Purge the para chain database
3. Purge the relay chain database

**Comment by bkchr** [comment]
> > Currently we only support 2. :D
> 
> Actually I think we just had option 1 because it deleted only the "db" directory. In my PR I added the option to purge the relay chain.
> 
> Maybe we should have 3 options?
> 
>     1. Purge all the things broom \o
> 
>     2. Purge the para chain database
> 
>     3. Purge the relay chain database

Yes that sounds right and I would like to see this as an extra new command. So everything could be combined into one sub-command:
```
purge-chain
```

Would delete all

```
purge-chain --parachain
```

Only the parachain

```
purg-chain --relay-chain
```

Only the relay chain.

I think this means you could do this by taking the substrate purge-chain as base and just extend it.

**Comment by cecton** [comment]
@bkchr check this out https://github.com/paritytech/cumulus/pull/306#issuecomment-765343376
