### ISSUE TITLE
Rename Statemint to Asset Hub

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/cumulus#2591]
Discussed in https://forum.polkadot.network/t/the-naming-of-things-viz-statemint/2328

- Rename folders under `parachains/runtimes/assets/{statemint, statemine, westmint}` to `asset-hub-{polkadot, kusama, westend}`
- Casing should be:
  - `asset-hub-polkadot`
  - `AssetHubPolkadot`
  - "Asset Hub Polkadot"
- Ensure node CLI works with `asset-hub-x`, but stays compatible with `statemint`

**Comment by gilescope** [comment]
We might need to fixup the export process to https://github.com/polkadot-fellows/runtimes once we land this.

**Comment by joepetrowski** [comment]
What do you mean by the export process?

It's already "asset hub" there ;)
https://github.com/polkadot-fellows/runtimes/tree/main/system-parachains/runtimes/asset-hubs

**Comment by gilescope** [comment]
Agreed, but something must be syncing it to there - if it’s a script rather
than a human it will need tweaking.

**Comment by PierreBesson** [comment]
As we want to keep backward compatibility, please don't change the chainspec `id` in [chainspec.json#L3](https://github.com/paritytech/cumulus/blob/master/parachains/chain-specs/statemine.json#L3) as this defines the database path on the disk (`./chains/statemine/db`). If it is changed, it would require all node operators to move files on their disk or else the node will start to resync it's database at a different path.
