### ISSUE TITLE
No such variant in enum MultiAddress

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#264]
**Description**

When parachain is registered, transactions sent via Polkadot Apps spawn an error:

```
1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress\
```

Looks like a type mismatch, do you have any ideas?

**Comment by bkchr** [comment]
This is the type mismatch for the parachain?

**Comment by akru** [comment]
Yes, for parachain only, using standard dotapps.io portal.

**Comment by bkchr** [comment]
Have you set the correct types?

**Comment by akru** [comment]
So, I'm not sure, do you have any suggestions?

**Comment by akru** [comment]
Just, it could be any type or something concrete? For example, type in Extrinsic codecs, etc.

**Comment by bkchr** [comment]
Sadly I don't have any suggestion.

**Comment by bkchr** [comment]
What was it @akru ?

**Comment by akru** [comment]
@bkchr I’m still in research, just close it because of relative affection to cumulus.
