### ISSUE TITLE
Asset-hub-kusama `pallet_assets` benchmark fails

### ISSUE THREAD

**Issue by ggwpez** [paritytech/cumulus#2727]
`pallet_assets` instance `ForeignAssetsInstance` fails its benchmark as shown in https://github.com/paritytech/cumulus/pull/2712 with [CI output](https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2971038).  
It can be locally reproduced by: `polkadot-parachain benchmark pallet --pallet pallet-assets --extrinsic="" --chain statemine-dev` after `cargo b --bin polkadot-parachain -r --features runtime-benchmarks`.  

It seems to be something with the `ForeignCreators` or its generics, since when i change [this](https://github.com/paritytech/cumulus/blob/38708a253920556d9db4471b2031c9fe6bb19ebf/parachains/runtimes/assets/asset-hub-kusama/src/lib.rs#L301) to root, then it works. I dont know how that works, but maybe we can just add root and it should work.

**Comment by bkontur** [comment]
@ggwpez 
this is obsolete: https://github.com/paritytech/command-bot-scripts/blob/main/commands/bench/lib/bench-all-cumulus.sh#L16-L74
and in cumulus script there is no need to name all pallets: 
https://github.com/paritytech/cumulus/blob/master/scripts/benchmarks-ci.sh#L16-L23

do you want me to prepare PR for https://github.com/paritytech/command-bot-scripts ?

**Comment by bkontur** [comment]
besides that, I building locally and going to investigate (should work as before)

**Comment by ggwpez** [comment]
>anyway, how was this job triggered? "statemine" is obsolete

That CI was triggered by the bench bot here: https://github.com/paritytech/cumulus/pull/2712#issuecomment-1587289970  
But the shell script also needs to be fixed, since in the release process it will be used to update the weights.  
You can debug it by using `--steps=2 --repeat=1` and building with `release` instead of `production` profile.

>do you want me to prepare PR for https://github.com/paritytech/command-bot-scripts ?

@mordamax the system parachain runtimes were renamed:  
- `statemint` -> `polkadot-asset-hub`
- `statemine` -> `kusama-asset-hub`
- `westmint` -> `westend-asset-hub`

**Comment by bkontur** [comment]
@ggwpez 
after some debugging,
I think I see where is the problem:
```
        create {
		let asset_id = default_asset_id::<T, I>();
		let origin = T::CreateOrigin::try_successful_origin(&asset_id.into())
			.map_err(|_| BenchmarkError::Weightless)?;
		let caller = T::CreateOrigin::ensure_origin(origin, &asset_id.into()).unwrap();
		let caller_lookup = T::Lookup::unlookup(caller.clone());
		T::Currency::make_free_balance_be(&caller, DepositBalanceOf::<T, I>::max_value());
	}: _(SystemOrigin::Signed(caller.clone()), asset_id.clone(), caller_lookup, 1u32.into())
	verify {
		assert_last_event::<T, I>(Event::Created { asset_id: asset_id.into(), creator: caller.clone(), owner: caller }.into());
	}
```

`ForeignCreators` works as expected, there is no problem, `try_successful_origin` return `pallet_xcm::Origin::Xcm()`,
and then `caller.clone()` is prepared ok as `OriginCaller::PolkadotXcm(Origin::Xcm(MultiLocation { parents: 1, interior: X1(Parachain(0)) })`

but the problem is, that it is wrapped with `SystemOrigin::Signed(caller.clone())`,
so when extrinsic is called it is type `OriginCaller::system(RawOrigin::Signed(`,
but the `ForeignCreators` expects `EnsureXcm::<Everything>::try_origin(` -> `OriginCaller::PolkadotXcm`, that is why `BadOrigin`


so the possiblem solution could be to change pallet_assets benchmarks to something like:
`SystemOrigin::Signed(caller.clone())` -> `_<T::RuntimeOrigin>(origin, `


I will try that locally tomorrow

**Comment by mordamax** [comment]
@ggwpez @bkontur the [scripts/benchmarks-ci.sh#L16-L23](https://github.com/paritytech/cumulus/blob/master/scripts/benchmarks-ci.sh#L16-L23) will be deprecated soon and this should be bot to run benches, so if something needs to be updated in command-bot-scripts, please update there, if it's obsolete

If you need any help, please reach me out or https://matrix.to/#/#command-bot:parity.io

**Comment by bkontur** [comment]
@ggwpez 
I have a fix https://github.com/paritytech/substrate/pull/14384
