### ISSUE TITLE
Question: Why two `StartCollatorParams` structs?

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#275]
I'm beginning to study the cumulus codebase to understand its inner workings. I noticed there are two very similar (but not identical) structs both called `StartCollatorParams`. Why is that?

First: https://github.com/paritytech/cumulus/blob/09b27cec90276348cc292a7b4180d90255b1b52c/service/src/lib.rs#L38-L53

Second: https://github.com/paritytech/cumulus/blob/09b27cec90276348cc292a7b4180d90255b1b52c/collator/src/lib.rs#L524-L539

**Comment by bkchr** [comment]
I don't understand this question? These are two different structs for two different functions?

The second one will be constructed by the first one.

**Comment by JoshOrndorff** [comment]
Okay, I get it. I was mostly wanting to make sure that both of them were there on purpose. I wondered at first if one was old dead code. Now I understand that they are both needed.

Is there a name for this pattern where you make a struct that has all the params for a function rather than passing individual parameters?

**Comment by bkchr** [comment]
> Is there a name for this pattern where you make a struct that has all the params for a function rather than passing individual parameters?

Probably, but I don't know it xD
