### ISSUE TITLE
Fix benchmarks `set_code` for `frame_system` pallet for all SP runtimes

### ISSUE THREAD

**Issue by bkontur** [paritytech/cumulus#2765]
here was added benchmark for `set_code` https://github.com/paritytech/substrate/pull/13373
but it does not work with Cumulus runtimes which uses:

```
type OnSetCode = cumulus_pallet_parachain_system::ParachainSetCode<Self>;
```
because it ends here, where some data are expected
https://github.com/paritytech/cumulus/blob/master/pallets/parachain-system/src/lib.rs#L986-L1008

so the fix should be to add some `T::BenchmarkHelper::prepare_data()` to the `set_code` benchmark [here](https://github.com/paritytech/substrate/blob/master/frame/system/benchmarking/src/lib.rs#L51-L56)

something like:
```
        set_code {
		let runtime_blob = include_bytes!("../res/kitchensink_runtime.compact.compressed.wasm").to_vec();
                T::BenchmarkHelper::prepare_data();
	}: _(RawOrigin::Root, runtime_blob)
	verify {
		System::<T>::assert_last_event(frame_system::Event::<T>::CodeUpdated.into());
	}
```

and then configure `BenchmarkHelper` in every runtime (or close to ParachainSetCode)

Example of failed job: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3035163
```
./target/production/polkadot-parachain benchmark pallet --chain=asset-hub-kusama-dev --execution=wasm --wasm-execution=compiled --pallet=frame_system --no-storage-info --no-median-slopes --no-min-squares '--extrinsic=*' --steps=50 --repeat=20 --json --header=./file_header.txt --output=./parachains/runtimes/assets/asset-hub-kusama/src/weights/
Error: Input("Benchmark frame_system::set_code failed: ValidationDataNotAvailable")
```

**Comment by bkontur** [comment]
> @bkontur will you work on this? Otherwise we could maybe for now work around by making `ParachainSetCode` be a no-op when `runtime-benchmarks` is enabled.

@bkchr do you mean something like this:
```
	/// The action to take on a Runtime Upgrade
	#[cfg(not(feature = "runtime-benchmarks"))]
	type OnSetCode = cumulus_pallet_parachain_system::ParachainSetCode<Self>;
	#[cfg(feature = "runtime-benchmarks")]
	type OnSetCode = ();
```

or 

```
impl<T: Config> frame_system::SetCode<T> for ParachainSetCode<T> {
	#[cfg(not(feature = "runtime-benchmarks"))]
	fn set_code(code: Vec<u8>) -> DispatchResult {
		Pallet::<T>::schedule_code_upgrade(code)
		Ok(())
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn set_code(code: Vec<u8>) -> DispatchResult {
		Ok(())
	}
}
```

for `()` I see it does at least `<Pallet<T>>::update_code_in_storage(&code)?;`

**Comment by bkchr** [comment]
Option 2, but this being just some intermediate solution and the real one being what you have proposed in the issue description.

**Comment by bkontur** [comment]
> Option 2, but this being just some intermediate solution and the real one being what you have proposed in the issue description.

yes, here is tmp solution: https://github.com/paritytech/cumulus/pull/2766
and I will start on real proposed one, it will just require polkadot and cumulus companions
