### ISSUE TITLE
What types to use with Polkadot API

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#28]
The [Polkadot JS API](https://github.com/polkadot-js/api/) supports interacting with the standard Substrate node out of the box, and with custom Substrate-based nodes by supplying type information about any types that have been customized ([docs](https://polkadot.js.org/api/start/types.extend.html)).

When I connect the API to the cumulus test parachain (eg using [apps](https://polkadot.js.org/apps/)) and submit an extrinsic, the API reports an error.

```
submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: Invalid transaction version: Client(Execution(ApiError("Could
```

What custom types need to be supplied to interact with the cumulus node?

**Comment by bkchr** [comment]
I don't know, but this is more a `polkadot-js` issue and not Cumulus related.
