### ISSUE TITLE
The rococo-collator get stuck at importing block #1

### ISSUE THREAD

**Issue by JNhua** [paritytech/cumulus#286]
I tested it on different Cumulus versions and found that after one version (5dfd0756efbd5be85937c2f530cfeaa7108b6dec), the `rococo-collator` on Cumulus failed to block properly. Here are my results:
Cumulus Version | Polkadot Version | Result
-- | -- | --
9f0085c097c3c48086faa58efc15915a768f1ea9 | 09c43bb8f29c1930b29c0a0910798b531c1effce | √
9f0085c097c3c48086faa58efc15915a768f1ea9 | c59408004db39c25f078e3e1961e640159b1bdda | √
5dfd0756efbd5be85937c2f530cfeaa7108b6dec | c59408004db39c25f078e3e1961e640159b1bdda | ×
5dfd0756efbd5be85937c2f530cfeaa7108b6dec | 09c43bb8f29c1930b29c0a0910798b531c1effce | ×
9f0085c097c3c48086faa58efc15915a768f1ea9 | 9115d4278084ffee89badc47faea8b0a2cce5f29 | ×
464e54affd89eeddaf14fa6820be56dd83f18093 | 9115d4278084ffee89badc47faea8b0a2cce5f29 | ×
48558a2bf666eba6be5b3a3b0d9ce9459bc4a714 | 0022f1f7bfd0799c8a45a8a3749ce4e8fc556bed | ×

**Comment by bkchr** [comment]
I don't know what I should do with this issue? 

We have a test that always ensures that the collator is working, so I think that actually something on your setup is wrong.

**Comment by JNhua** [comment]
Today, I test it again, and found some strange phenomenon. I'm sure that my setup is correct.

# Test Environment

The test network's version as follows:

* cumulus version: 7277f7a

* polkadot version: a3e1113

The execution results are weird. Sometimes, the `rococo-collator` can import block normally. And in other cases, the `rococo-collator` gets stuck at `[parachain] import block #1`. 

I can't figure out what the problem is, but I will  describe my operation and execution environment as best as I can.

# Test Result

Serial num. | Machine running rococo-collator | Machine running rococo_local | Run cmd of rococo-collator | Result
-- | -- | -- | -- | --
1 | PC_A | PC_A | ./target/release/rococo-collator --tmp --collator --discover-local --parachain-id=200 -- --chain rococo_local.json  --execution=wasm | R1
2 | PC_A | PC_B | ./target/release/rococo-collator --tmp --collator  --discover-local --parachain-id=200  -- --chain rococo_local.json  --execution=wasm --bootnodes=/ip4/xxx/ | R3( Most likely to succeed )
3 | PC_A | PC_B | ./target/release/rococo-collator --tmp --collator  --discover-local --parachain-id=200  -- --chain rococo_local.json  --execution=wasm | R2
4 | PC_A | PC_B | ./target/release/rococo-collator --tmp --collator  --discover-local --parachain-id=200  -- --chain rococo_local.json --bootnodes=/ip4/xxx/ | R2

## Note

1. `PC_A` and `PC_B` are different machines on the same inner network. 
2. For the results, the larger the number following "R", the greater the likelihood of normal execution in this case. For example, "R3" means that in this case, the number of successes is the highest.
3. Another person told me that in case 1 ( PC_A & PC_A ), rebooting the network would make the `rococo-collator` work. But it does not work for me.
4. I can make sure the other operations are consistent, only the test conditions listed in the table have changed.

In addition, all the tests I did yesterday were on the same machine (case 1: PC_A & PC_A). I test the version 9f0085c of cumulus again, and in any case, the `rococo-collator` is normal.

# My Guess

So it looks like after version 9f0085c of cumulus, the test net's environmental requirements have changed. I think it's more likely that the requirements for the network have changed. I tracked the change between the two commits ( 9f0085c => 5dfd075 ) , and found that `Substrate` went from version `1b840aa` to version `c9d9365`, one of these commits(`dbe2031`) changed the network-related code. Hopefully that will help you figure out what the problem is.

**Comment by bkchr** [comment]
>     1. `PC_A` and `PC_B` are different machines on the same inner network.

Do you mean these are docker containers on a docker "network"? Or are these real machines? 

If that is docker, could you provide some docker-compose script to reproduce this?

**Comment by JNhua** [comment]
Real machines.

**Comment by bkchr** [comment]
Could you please try to replicate this with docker?

**Comment by JNhua** [comment]
Ok, I wil try it tomorrow.

**Comment by bkchr** [comment]
Ty!

**Comment by JNhua** [comment]
# Test For Docker

My test results with Docker are consistent with the test results on the real machines. The bridge mode is adopted in Docker, but the nodes in Docker can connect to the local area network of the host through P2P. I suspect that if the test network was fully deployed in a pure network, the success rate would be higher, because I noticed another phenomenon.

> Pure Network：At least on this LAN, only one Rococo local test network is running.

# New Findings

## Setup

In the LAN, run different Rococo local test networks on machine A and machine B, calling them test networks A and B.

## Results

In two test network environments, the `rococo-collator` has a large probability of not normal. However, after the test net B is shut down, the test net A is restarted, and after running for a period of time, the `rococo-collator` on the test net A can block normally.

## Conclusion

The running of test network B appears to affect `rococo-collator-a` on test network A, although it is not observed from the logs that `rococo-collator-a` is connected to test network B.

## Repair Operation

When the network environment of machine A has been polluted by test network B, we need to reset the network environment of test network A at the same time as shutting down test network B, and then restart test network A.

# Contact

I'm working for Patract Labs, and the parachain I registered is called Patract Jupiter, it's `para_id` is 1. My ID on Element is `@jenner:matrix.org`.

**Comment by bkchr** [comment]
So it works with docker?

**Comment by JNhua** [comment]
In my test environment, it does not work with docker. The results should be related to the network environment, not docker or real machines.

**Comment by bkchr** [comment]
Can you than please provide some docker compose so that we can reproduce this?
