### ISSUE TITLE
What inherent checking does the `Verifier` actually do?

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#287]
My question is about this code

https://github.com/paritytech/cumulus/blob/464e54affd89eeddaf14fa6820be56dd83f18093/consensus/src/import_queue.rs#L61-L82
The `Verifier` requires inherent data providers. When importing a block it seems to reconstruct the inherent data and confirm that it matches the block? Is that right?

Even if my explanation is right, I'm still confused. The rococo collator inserts a timestamp, but the timestamp inherent data provider is not even part of what is passed to the Verifier. We're running into a similar confusion about our author inherent that includes the address of the block author.

So I guess my questions are:
1. Can you give an example of an inherent that would make sense to check in the `Verifier`?
2. Can we remove that requirement for the Verifier to take inherent data providers?

**Comment by bkchr** [comment]
The runtime decides if an inherent should be checked. You can just skip checking your author inherent. Why isn't that passed as digest to the runtime?

In general, I need to rework the inherent handling in the next time and make it a little bit easier to use (hopefully).

**Comment by JoshOrndorff** [comment]
Okay, I understand. Previously I was confused about how the `ProvideInherent` trait worked. I've made https://github.com/paritytech/substrate/pull/7941 to try to clear it up.

> Why isn't that passed as digest to the runtime?

You mean a PreRuntime digest like in Aura or Babe? We will probably do that when cumulus supports it. I might take a look in that direction next.
