### ISSUE TITLE
Consensus hook should be feature-flagged

### ISSUE THREAD

**Issue by rphmeier** [paritytech/cumulus#2905]
The new `ParachainSystem::ConsensusHook` type parameter should be feature-flagged. The actual logic of the consensus hook doesn't need to be (as it's backwards compatible), but adding the type to the trait itself is a breaking change. If the feature flag is disabled, the logic should run with `ExpectParentIncluded` (and later, `RequireParentIncluded`)

**Comment by BradleyOlson64** [comment]
Closed by https://github.com/paritytech/cumulus/pull/2911
