### ISSUE TITLE
Parachain cannot produce block

### ISSUE THREAD

**Issue by chenzongxiong** [paritytech/cumulus#292]
I set up relay chain (dev) on my own local machine, and connect my own parachain with relay chain. However, I found that the parachain **cannot** produce new blocks

![image](https://user-images.githubusercontent.com/8354165/104727842-54f31780-5736-11eb-8982-4f29f1cf4d47.png)

I turn on the debug log of parachain and found the following logs
![image](https://user-images.githubusercontent.com/8354165/104728754-b10a6b80-5737-11eb-8125-ac626d2893da.png)

![image](https://user-images.githubusercontent.com/8354165/104728884-db5c2900-5737-11eb-8b6e-f648b552cc38.png)

The command to start parachain is 
```
alice=12D3KooWNP5jdUCjeJpZTifTAy6az1F6pnzKxCdK5WQsiGZE85d8
bob=12D3KooWF3Rz4hBs2jes5zur9CN52HjB8ndhTLDaTutc8L5Dwn6L

./target/release/rococo-collator \
    --tmp \
    --ws-port 9988 \
    --parachain-id 1984 \
    --collator \
    --  \
    --chain rococo-local-cfde-real-overseer.json \
    --name cumulus \
    --execution wasm \
    --port 30337 \
    --bootnodes /ip4/192.168.1.104/tcp/30333/p2p/$alice \
    --bootnodes /ip4/192.168.1.104/tcp/30334/p2p/$bob
```

And I found that the parent hash of parachain is 0x0000000000000000
![image](https://user-images.githubusercontent.com/8354165/104727874-5cb2bc00-5736-11eb-9291-7cf9f261cd4e.png)

I run the following command to generate chain spec (see https://github.com/paritytech/cumulus/tree/master).
```
./target/release/polkadot build-spec \
    --chain rococo-local \
    --disable-default-bootnode --raw > rococo-local-cfde-real-overseer.json
```

![image](https://user-images.githubusercontent.com/8354165/104727905-6805e780-5736-11eb-83c8-2aa92cf8cd5d.png)

The commands to start relay chain are:

```
./target/release/polkadot \
    --chain rococo-local-cfde-real-overseer.json \
    --tmp \
    --ws-port 9944 \
    --port 30333 \
    --alice
```
```
./target/release/polkadot \
    --chain rococo-local-cfde-real-overseer.json \
    --tmp \
    --ws-port 9955 \
    --port 30334 \
    --bob
```

This relay chain is compiled on **tag v0.8.27 (polkadot repo), not branch rococo-v1**. 
One more problem, I also received the following logs in my own parachain

![image](https://user-images.githubusercontent.com/8354165/104727925-705e2280-5736-11eb-9536-415032575048.png)

**Comment by bkchr** [comment]
> This relay chain is compiled on **tag v0.8.27 (polkadot repo), not branch rococo-v1**.

This is wrong, everything must use this branch. Also the relay chain.

**Comment by chenzongxiong** [comment]
I switched to branch **rococo-v1**, and still encountered the problems.

**Comment by bkchr** [comment]
Did you compile with the `--feature=real-overseer`?

**Comment by chenzongxiong** [comment]
> Did you compile with the `--feature=real-overseer`?

Yes. I followed the commands in README.md

**Comment by bkchr** [comment]
Could you try to run all nodes with `--discover-local`?

**Comment by chenzongxiong** [comment]
works now. thanks
