### ISSUE TITLE
We need some ROC tokens for testing

### ISSUE THREAD

**Issue by chenzongxiong** [paritytech/cumulus#298]
We need some ROC tokens to test with rococo parachain. We have already set up rococo validator and tested the functionalities of parachain locally. The next step is that we want to integrate our parachain with rococo testnet.
Our team is Litentry.
Our address is: 5C54GWZdTf9PdZ7YQgY1TXV6wacm8disFQQevR3NPe6P69Tf

**Comment by bkchr** [comment]
Please do not open issues for this.
