### ISSUE TITLE
How can I connect substrate chain to a parathread using cumulus library?

### ISSUE THREAD

**Issue by true-eye** [paritytech/cumulus#321]
I can see & read that any blockchain developed on Substrate can be turned into a parachain or parathread using Cumulus library.
How is it different for parachain & parathread to use Cumulus library?

Thanks in advance

**Comment by bkchr** [comment]
Parathreads are currently not supported. So, you can not build a parathread yet with Cumulus.

**Comment by true-eye** [comment]
@bkchr Thanks for your reply. 

If that is true, then that should be described in the substrate or cumulus doc, I think. (Or maybe I missed reading it) :)

Thanks again

**Comment by bkchr** [comment]
We did not mention anywhere that you can build a parathread at the moment :D

**Comment by true-eye** [comment]
https://wiki.polkadot.network/docs/en/build-build-with-polkadot#how-to-set-up-your-parachain

```
Substrate comes with its own networking layer built-in but unfortunately only supports solo chains (that is, chains that do not connect to the Relay Chain). However, there is the Cumulus extension that includes a collator node and allows for your Substrate-built logic to be compatible with Polkadot as either a parachain or parathread.
```

I just saw the last word `parathread` in the above section. But couldn't find it in any other places. So I thought it's strange. But now, it's clear.

It's not YET now.

**Comment by bkchr** [comment]
So I can close this?

**Comment by true-eye** [comment]
Sure. I can also close. 👍
