### ISSUE TITLE
Paranodes occasionally fail to import a block and don't try again

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/cumulus#335]
A parachain node will occasionally fail to import a parachain block and consequently not update its best block. When this happens the node does not try again to request the failed-import block from a peer even though it is accepted into the relay chain.

This issue happens fairly often (every 10 - 100 blocks) but it is not always obvious. For example in a single collator network, there is no other collator which could fail to import a block, so you won't see it. But in a multi-collator network you will.

The good news is that the node gets back on track once it imports the next parachain block after the one it failed to import. However, if the failed node is a collator, and the network is waiting for it to author, this represents a liveness stall.

Although the issue happens often, it is much easier to notice that it happened and diagnose it if it causes a network stall. To help with that I've opened PR #334. This introduces the minimal necessary author assignment logic necessary to make this bug cause a network stall.

**Comment by bkchr** [comment]
> However, if the failed node is a collator, and the network is waiting for it to author, this represents a liveness stall.

This is your main problem. You need a way to advance to the next author if one doesn't build a block.

What does it mean it fails to import a block? Is there an error somewhere? Or it just doesn't import the block?

**Comment by JoshOrndorff** [comment]
> You need a way to advance to the next author

I totally agree. We've already implemented this by including the relay chain block height as part of our author selection. But I opened #334 with this less robust scheme because this is how I found it most useful for reproducing the import error.

> What does it mean it fails to import a block? Is there an error somewhere? Or it just doesn't import the block?

No error. It just never prints the log saying it imported the block, and never updates its best block (even though its peers do).

**Comment by bkchr** [comment]
Could you run the node with `sync=trace` until this happens and give me the log? :D

**Comment by crystalin** [comment]
@bkchr 
I was able to have the same effect, but I'm not sure if it is the same issue (only few blocks got delayed here (2 or 3), while we observed sometime a delay of many blocks (like 5-10)).

The block height that got delayed was `53568..53570`
[moonbeam_slow_import.log](https://github.com/paritytech/cumulus/files/6047012/moonbeam_slow_import.log)

**Comment by bkchr** [comment]
@crystalin which Substrate version are you using?

**Comment by crystalin** [comment]
@bkchr 
https://github.com/paritytech/substrate#965950969f3fca2d9e225e4988afbc0a6b851a56
https://github.com/paritytech/polkadot#71a528e822af63b96bdb03efac9b4927fb11a25e
https://github.com/paritytech/cumulus#6438d328b8ac09f43d19df65a2cf8e31a524d78f

**Comment by crystalin** [comment]
Here are the same logs going further (including 53571)

[moonbeam_slow_02-06_02-12.log](https://github.com/paritytech/cumulus/files/6062820/moonbeam_slow_02-06_02-12.log)

**Comment by bkchr** [comment]
Ty

**Comment by crystalin** [comment]
Is there any update on that issue ?

**Comment by bkchr** [comment]
No

**Comment by crystalin** [comment]
@bkchr ok I've found the issue.
When a node is not **directly** connected to the collator producing the block, it doesn't import it.

I've done the test where one node had only 1 peer (a collator). When that collator produced the block, the node got up to date with the latest best block. When another collator produced the block, the node didn't import it
