### ISSUE TITLE
cumulus workshop error

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/cumulus#336]
hi, I tried the cumulus workshop, when I build the collator template something error.
![image](https://user-images.githubusercontent.com/49427668/108532462-d67c2d80-7312-11eb-832b-937682b34751.png)

**Comment by master-davidlee** [comment]
https://substrate.dev/cumulus-workshop/#/en/1-prep/1-compiling?id=building-the-collator-template

**Comment by bkchr** [comment]
Please report in the workshop repo and not here. TY
