### ISSUE TITLE
Some questions in README.md

### ISSUE THREAD

**Issue by lxex** [paritytech/cumulus#337]
1. what mean about `parachain_id_u32_type_range`, could you give me more details?
2. why there're two `--port` in launch parachain command?

thanks.

**Comment by bkchr** [comment]
1. The id has to be an `u32`.
2. The collator is starting two nodes. So you can supply arguments for both of them

**Comment by lxex** [comment]
@bkchr Is there id set to `200`?

**Comment by bkchr** [comment]
What?
