### ISSUE TITLE
Configurable send origin in XCM handler

### ISSUE THREAD

**Issue by shaunxw** [paritytech/cumulus#339]
XCM handler module has dispatchable calls to send messages, but the origin must be root. https://github.com/paritytech/cumulus/blob/d8126cdc13c4c370fa1c360421843796c8411ca9/pallets/xcm-handler/src/lib.rs#L77-L78

It will be helpful to make the origin configurable, so that it can work with `pallet-collective`. For instance, config the send origin as `EnsureRootOrHalfCouncil`.

**Comment by bkchr** [comment]
As the name suggests, these are `sudo` related dispatchables for testing purposes not as a general way to send these messages.

**Comment by shaunxw** [comment]
Parachains needs to send upward message to init/accept HRMP channel requests. Before [this issue](https://github.com/paritytech/substrate/issues/8158) solved, there is no way to add helper dispatchable calls to do these tasks. However it seems the issue cannot be solved in short term. Could you suggest a way if these testing sudo calls removed in the future?

**Comment by shaunxw** [comment]
Maybe we can add a more specific dispatchable call, which only sends upward `Xcm::Transact` message, to help parachains managing HRMP channels (or other future calls which checks [`ensure_parachain`](https://github.com/paritytech/polkadot/blob/c66049ddda26c9609d1a2cf23c0975a1f9677712/runtime/parachains/src/origin.rs#L33) origin in relay chain). Like this:

```rust
fn send_upward_xcm_transact(origin, call: Vec<u8>) {
    T::SendOrigin::ensure_origin(origin)?;
    let msg = Xcm::Transact {
        origin_type: OriginKind::Native,
        call: call,
    };
    // send upward msg...
}
```

**Comment by bkchr** [comment]
Best is to ask @pepyakin on what he thinks about this.

**Comment by pepyakin** [comment]
I distanced a bit from XCM lately and not that well versed in the specifics of the pallet-collective, so I think @shawntabrizi is the man here.

However, I can note that this particular use case could be addressed using an intermediate pallet, which could accept calls from, e.g pallet-collective and manually prepare and send a message. Gross but works.

**Comment by shawntabrizi** [comment]
I think having a configurable origin is a fine change and doesn't really change the pallet. Probably you would want to remove the word `sudo` though

As for creating a root call, you can do so in Democracy with `do_enact_proposal`:

https://github.com/paritytech/substrate/blob/master/frame/democracy/src/lib.rs#L1540

Which can be executed by an collective as an `ExternalMajorityOrigin`. This is how Runtime Upgrades happen...

**Comment by shaunxw** [comment]
> I think having a configurable origin is a fine change and doesn't really change the pallet. Probably you would want to remove the word `sudo` though

I'm happy to open a PR to do this. Will make these send xcm dispatchable calls use configurable origin and remove word `sudo`.
