### ISSUE TITLE
Pass CLI arguments to parachain/relay chain node

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#34]
When running the collator, I want to pass CLI arguments that are related to the parachain and to the relay chain. As both are substrate projects, we need to make it possible to pass the same arguments twice to the same binary.

We want the following syntax:

`collator --name parachain -- --name relaychain`

The first arguments before the `--` are the parachain parameters and everything after `--` is a relay chain parameter.

`--help` should make it clear how we expect parameters to be passed.

Maybe we could also include some reasonable defaults for ports, so that they don't clash: https://github.com/paritytech/cumulus/issues/24

Like putting the relay chain ports at `default + 1` (if they are not overwritten by a cli arg)

**Comment by cecton** [comment]
> Maybe we could also include some reasonable defaults for ports, so that they don't clash: #24

This feature couldn't be implemented without the refactoring in https://github.com/paritytech/substrate/pull/4692 

I close this ticket and #24 will remain to fix the defaults for the ports.
