### ISSUE TITLE
Problem when adding `cumulus-primitives-core` to codebase

### ISSUE THREAD

**Issue by johnwhitton** [paritytech/cumulus#349]
We are building an evm compatible parachain and having problems when adding in `cumulus-primitives-core` 
We have raised issue https://github.com/sunriseprotocol/sunrise/issues/20 in our codebase

**The Steps to reproduce are also below**

**Problem**
When adding `cumulus-primitives-core`  receive the error
```
   Compiling sp-io v3.0.0 (https://github.com/paritytech/substrate?branch=rococo-v1#debec916)
  error[E0152]: found duplicate lang item `panic_impl`
      --> /Users/john/.cargo/git/checkouts/substrate-7e08433d4c370a21/debec91/primitives/io/src/lib.rs:1372:1
       |
  1372 | pub fn panic(info: &core::panic::PanicInfo) -> ! {
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: the lang item is first defined in crate `std` (which `funty` depends on)
       = note: first definition in `std` loaded from /Users/john/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-4e755af785aa469c.rlib
       = note: second definition in the local crate (`sp_io`)

  error[E0152]: found duplicate lang item `oom`
      --> /Users/john/.cargo/git/checkouts/substrate-7e08433d4c370a21/debec91/primitives/io/src/lib.rs:1383:1
       |
  1383 | pub fn oom(_: core::alloc::Layout) -> ! {
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: the lang item is first defined in crate `std` (which `funty` depends on)
       = note: first definition in `std` loaded from /Users/john/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-4e755af785aa469c.rlib
       = note: second definition in the local crate (`sp_io`)

  error: aborting due to 2 previous errors

  For more information about this error, try `rustc --explain E0152`.
  error: could not compile `sp-io`

  To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Step to Reproduce**
This is reproduce on branch [build_issue](https://github.com/sunriseprotocol/sunrise/tree/build_issue) at commit [5ebe362](https://github.com/sunriseprotocol/sunrise/commit/5ebe36214c715e981c8a701ab8953be3fee28bf2)

```
git clone https://github.com/sunriseprotocol/sunrise.git
cd sunrise
git checkout build_issue
cargo build --release
```

**Debugging Approach**
By commenting out individual pallets and dependencies in `runtime/dawn/Cargo.toml` we can add in dependencies until we break. Currently we break when adding in `cumulus-primitives-core`
1. [Cargo.toml](https://github.com/sunriseprotocol/sunrise/blob/build_issue/Cargo.toml) has been modified to only compile the dawn runtime.
2. [runtime/dawn/Cargo.toml](https://github.com/sunriseprotocol/sunrise/blob/build_issue/runtime/dawn/Cargo.toml) has been modifed to comment out all local code. 
3. [runtime/src/lib.rg](https://github.com/sunriseprotocol/sunrise/blob/build_issue/runtime/dawn/src/lib.rs#L1) has been modified to deliberately generate an error message. This is to highlight whether the issue is in compling the dependencies or sunrise code.

**Additional Information**
1. [Cargo.toml](https://github.com/sunriseprotocol/sunrise/blob/build_issue/Cargo.toml#L10) uses `resolver = "2"`
2. [Cargo.toml](https://github.com/sunriseprotocol/sunrise/blob/build_issue/Cargo.toml#L78) uses  `[patch.crates-io]` to leverage the AcalaNetwork evm `evm = { git = "https://github.com/AcalaNetwork/evm.git", branch = "sw/bump-dependencies" }`
3. Dependencies were updated by running `cargo update && cargo update -p schnorrkel:0.9.2 --precise 0.9.1 && cargo update -p funty --precise 1.1.0`
4. [Ethereum override in Cargo.toml](https://github.com/sunriseprotocol/sunrise/blob/build_issue/Cargo.toml#L83) is not pulling in the  ethereum version 6.0  `ethereum = { git = "https://github.com/rust-blockchain/ethereum.git" }` Instead this was manually added into [Cargo.lock](https://github.com/sunriseprotocol/sunrise/blob/build_issue/Cargo.lock#L755)
```
[[package]]
name = "ethereum"
version = "0.6.0"
source = "git+https://github.com/rust-blockchain/ethereum.git#c5813a82e9760cbb15db9677de7716bd33cd8d6a"
dependencies = [
 "ethereum-types",
 "hash-db",
 "hash256-std-hasher",
 "rlp",
 "rlp-derive",
 "sha3 0.9.1",
 "triehash",
]
```
5. Visual Studio is used when editing codebase which may be updating dependencies in Cargo.lock

**Comment by bkchr** [comment]
```
       = note: the lang item is first defined in crate `std` (which `funty` depends on)
       = note: first definition in `std` loaded from /Users/john/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-4e755af785aa469c.rlib
       = note: second definition in the local crate (`sp_io`)
```

The compiler is telling you exactly what the problem is. You are pulling the `funty` dependency into the `no_std` build, which has `std` enabled. So, we are clashing with `std`.

You have 2 solutions:
1. Make `funty` optional or disable `std`.
2. Use the proper solution for your problem and remove `funty` and run `cargo update -p funty --precise 1.1.0`.

**Comment by johnwhitton** [comment]
Thanks @bkchr problem was [this line](https://github.com/sunriseprotocol/sunrise/blob/build_issue/runtime/dawn/Cargo.toml#L21)
which needed to be removed or commented
`funty = { version = "=1.1.0" }`
Apologies for the inconvenience.
