### ISSUE TITLE
Switch to Rust async

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#35]
Code like this: https://github.com/paritytech/cumulus/blob/master/collator/src/lib.rs#L114-L268

Should be converted to proper rust async to make it look better and hopefully to make it better maintainable. 

(The code should be scanned for other opportunities)

**Comment by bkchr** [comment]
@expenses are you maybe interested in this?

**Comment by expenses** [comment]
Yep, I'll try and make some time for this.

**Comment by bkchr** [comment]
Ty!
