### ISSUE TITLE
Rococo V1 branch points to different commits

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#353]
**Motivation**

Substrate & Polkadot commits from `Cargo.lock` in cumulus `rococo-v1` branch didn't points to real polkadot & substrate `rococo-v1` branch:

https://github.com/paritytech/cumulus/blob/rococo-v1/Cargo.lock#L1948 locked on `beff566b53ea1eeb4e54edc9416211141195004f`

But https://github.com/paritytech/substrate/commits/rococo-v1 points to https://github.com/paritytech/substrate/commit/debec916998233a287fb9e5a099c08d5e4a23db2

**Comment by bkchr** [comment]
Does it not compile?

**Comment by akru** [comment]
It has troubles that were tried to solve by the `rococo-v1` branch everywhere: when you have your parachain project and run `cargo update` everything should be compatible, in fact, it's broken. The cumulus on `rococo-v1` isn't compiling and working with Substrate/Polkadot on `rococo-v1`.

**Comment by akru** [comment]
@bkchr unfortunately, no

**Comment by bkchr** [comment]
Hmmm... Okay.

**Comment by bkchr** [comment]
Working again ;)

**Comment by akru** [comment]
Amazing, thank you very much @bkchr
