### ISSUE TITLE
could you change the style of the dependency???

### ISSUE THREAD

**Issue by transxask** [paritytech/cumulus#356]
your project use dependency for example:
`sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }`
but the template_node_runtime and orml use stable version：
`sp-std  = { default-features = false, version = '3.0.0' }`.

it cause the substrate version conflict.

**Comment by bkchr** [comment]
We currently don't depend on any released version of Substrate and that also still takes some time. So, for now, we can not change this.
