### ISSUE TITLE
`--collator` does not imply `--validator`

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#368]
Both should be doing the same, but `--collator` is not enabling the same features as `--validator`.

Maybe we should just drop `--collator` all together.

**Comment by JoshOrndorff** [comment]
I vote to keep it. We use it at Moonbeam. Of course we could still have it there even if you don't have it here I suppose. I can take a look at this next week.

**Comment by bkchr** [comment]
The `--collator` flag is not provided by Cumulus in a "reusable" way. Meaning that you need to copy the code anyway and could keep it or do whatever you want :D
