### ISSUE TITLE
Bring back `can_set_code`

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#374]
`can_set_code` is used in `schedule_upgrade` in `parachain-system`. It was removed because the current implementation is too slow for parachains.

**Comment by JoshOrndorff** [comment]
Since this is closed, it means we can "upgrade" to a lower spec version or different spec name and the upgrade should still go through right?

**Comment by bkchr** [comment]
No

**Comment by JoshOrndorff** [comment]
Oh actually, now that the normal upgrade path is with `system::set_code` we are already using the normal checks from https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L1537-L1557

Are those the ones that were too heavy?

**Comment by bkchr** [comment]
Before we instantiated the WASM and called into it. Now, we just can fetch the version from a WASM section. This is much faster and better.
