### ISSUE TITLE
Make `CollatorKey` a session key

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#376]
The collator key is currently always randomly generated on startup of a collator, but it should actually be a session key of the parachains.

This means:
1. Make it possible to use the collator key as session key in a parachain runtime.
2. Provide functionality to pass the collator key to Polkadot
3. Adapt Polkadot to make passing the collator key easier, this could for example be a function that gets data passed that needs to be signed. On the Cumulus side we will provide this function to Polkadot.

**Comment by JoshOrndorff** [comment]
Design Question: In what way does Polkadot use the collator key?

**Comment by bkchr** [comment]
Mainly to distinguish collators. In the future there could also be something like a market for collator to validator connections.

**Comment by bkchr** [comment]
Okay, this is not true anymore. For now we will actually hide this key to the outside, making it randomly generated on each start. Later, for parathreads we will need to revisit this.

**Comment by bkchr** [comment]
https://github.com/paritytech/cumulus/pull/459
