### ISSUE TITLE
Analysis of the compile error around `clang-sys` on Master

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/cumulus#402]
`clang-sys` is failing during compilation in Cumulus Master. (error at end of this post) @bkchr 

The following is the analysis of the dependency tree for `clang-sys` found in the `Cargo.lock` file. 

It is intended for discussion as there are several other teams implicated in this analysis - admittedly I could be barking up the wrong tree (pun intended).

# Analysis of Cargo.lock

```rust
name = "clang-sys"
version = "0.29.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

Installed as a dependency on 

```rust
name = "bindgen"
version = "0.54.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

Installed as a dependency on 

```rust
name = "librocksdb-sys"
version = "6.11.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

Installed as a dependency on 

```rust
name = "rocksdb"
version = "0.15.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

Installed as a dependency on latest version of 

```rust
name = "kvdb-rocksdb"
version = "0.11.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

Installed as a dependency on 

```rust
name = "polkadot-service"
version = "0.8.30"
source = "git+https://github.com/paritytech/polkadot?branch=master#96dc1f7ab613944f733fb8658dc8b0da18e2b8ea"
```

And  latest version of
```rust
name = "sc-client-db" 
version = "0.9.0"
source = "git+https://github.com/paritytech/substrate?branch=master#3dc169d526c12687944ffcd3d3c3b0adf4332db3"
```
There are a number of issues in this dependency tree:

## 1. rocksdb
Note that `rocksdb` is on version `0.15.0` the latest version, however it depends on `librocksdb-sys version 6.17.3` and not `6.11.4` as stated in the `Cargo.lock` file. A cursory check of the github repo confirms this, by navigating from `crates.io`.

https://crates.io/crates/rocksdb

---> https://github.com/rust-rocksdb/rust-rocksdb

and further 

---> https://github.com/rust-rocksdb/rust-rocksdb/blob/0b700fe70da8ee30483fde79f44df549f8fe11ec/Cargo.toml#L31

In fact it looks like `rocksdb` team has forked `librocksdb-sys` because it lives in the same repo (i.e. not referencing `crates.io`) and has clearly moved on in versioning.

This implies that the version of `librocksdb-sys` is pulled from `crates.io` and not aligned with the version required for `rocksdb`.

## 2. bindgen
`librocksdb-sys version 6.17.3` in `rocksdb` is dependent on version `0.57.0`of `bindgen` not version `0.54.0` that appears in our `Cargo.lock` file. 

This may be due to the issue above where `6.11.4` is being built into `Cargo.lock`.

---> https://github.com/rust-rocksdb/rust-rocksdb/blob/0b700fe70da8ee30483fde79f44df549f8fe11ec/librocksdb-sys/Cargo.toml#L32

The latest version of `bindgen` is `0.58.1`.

## 3. clang-sys

This is the line in `bindgen` that includes `clang-sys`

---> https://github.com/rust-lang/rust-bindgen/blob/696455d1c15e682b2b89f81f409315ea4964aef3/Cargo.toml#L52

It appears that `bindgen` is specifying version `1` and the correct features env variable (at least for `buster`!) but for some reason our `Cargo.lock` is only pulling version `0.29.3`.

The current version of clang-sys is `1.2.0`.

## Conclusion
I am not really sure why this error is not seen elsewhere i.e. in Substrate which compiles without issues. I have not compared the lock files yet though.

## Compile error message:
```shell
error: aborting due to 579 previous errors

For more information about this error, try `rustc --explain E0642`.
error: could not compile `clang-sys`

Caused by:
  process didn't exit successfully: `rustc 
  --crate-name clang_sys /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/lib.rs 
  --error-format=json 
  --json=diagnostic-rendered-ansi,artifacts 
  --crate-type lib 
  --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 
  --cfg 'feature="clang_6_0"' 
  --cfg 'feature="gte_clang_3_6"' 
  --cfg 'feature="gte_clang_3_7"' 
  --cfg 'feature="gte_clang_3_8"' 
  --cfg 'feature="gte_clang_3_9"' 
  --cfg 'feature="gte_clang_4_0"' 
  --cfg 'feature="gte_clang_5_0"' 
  --cfg 'feature="gte_clang_6_0"' 
  --cfg 'feature="libloading"' 
  --cfg 'feature="runtime"' -C metadata=78368e62347a7342 -C extra-filename=-78368e62347a7342 
  --out-dir /home/chris/cumulus/target/debug/deps -L dependency=/home/chris/cumulus/target/debug/deps 
  --extern glob=/home/chris/cumulus/target/debug/deps/libglob-bebc8faa8687c1c0.rmeta 
  --extern libc=/home/chris/cumulus/target/debug/deps/liblibc-35885dede9c488a9.rmeta 
  --extern libloading=/home/chris/cumulus/target/debug/deps/liblibloading-0b96d57a3f46a0a1.rmeta 
  --cap-lints allow -L native=/home/chris/cumulus/target/debug/build/libloading-a67a40f1cd8ab31e/out` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bkchr** [comment]
This is a rustc bug. Downgrade your nightly.

**Comment by chrisdcosta** [comment]
@bkchr what date for the nightly?

**Comment by bkchr** [comment]
Use the nightly from 1.03
