### ISSUE TITLE
error[E0046]: not all trait items implemented, missing: `is_inherent`

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/cumulus#409]
Getting

```
error[E0046]: not all trait items implemented, missing: `is_inherent`
   --> /home/ayush/.cargo/git/checkouts/cumulus-59522f43471fa161/6ed9632/pallets/parachain-system/src/lib.rs:765:1
    |
765 | impl<T: Config> ProvideInherent for Module<T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `is_inherent` in implementation
    |
    = help: implement the missing item: `fn is_inherent(_: &<Self as ProvideInherent>::Call) -> bool { todo!() }`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
```

I am getting this in `rococo-v1` branch.

cumulus-pallet-parachain-system= { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1', default-features = false }

**Comment by ayushmishra2005** [comment]
Can someone help me on this?

**Comment by thiolliere** [comment]
you mean the branch rococo-v1 is not compiling anymore ? or did you upgrade substrate locally ?

Anyway the fix should be:
```diff
diff --git a/pallets/parachain-system/src/lib.rs b/pallets/parachain-system/src/lib.rs
index 80c3735..c0d1c80 100644
--- a/pallets/parachain-system/src/lib.rs
+++ b/pallets/parachain-system/src/lib.rs
@@ -777,6 +777,10 @@ impl<T: Config> ProvideInherent for Module<T> {
 
                Some(Call::set_validation_data(data))
        }
+
+       fn is_inherent(call: &Self::Call) -> bool {
+               matches!(call, Call::set_validation_data(_))
+       }
 }
 
 decl_event! {
```

**Comment by ayushmishra2005** [comment]
> you mean the branch rococo-v1 is not compiling anymore ? or did you upgrade substrate locally ?
> 
> Anyway the fix should be:
> 
> ```diff
> diff --git a/pallets/parachain-system/src/lib.rs b/pallets/parachain-system/src/lib.rs
> index 80c3735..c0d1c80 100644
> --- a/pallets/parachain-system/src/lib.rs
> +++ b/pallets/parachain-system/src/lib.rs
> @@ -777,6 +777,10 @@ impl<T: Config> ProvideInherent for Module<T> {
>  
>                 Some(Call::set_validation_data(data))
>         }
> +
> +       fn is_inherent(call: &Self::Call) -> bool {
> +               matches!(call, Call::set_validation_data(_))
> +       }
>  }
>  
>  decl_event! {
> ```
@thiolliere 
I did `cargo update`. After that I started getting this error.

**Comment by c410-f3r** [comment]
Among other things, `client/consensus/relay-chain` also needs an update on `rococo-v1`

**Comment by bkchr** [comment]
We just need to update the rococo-v1 branch. Master already has these changes.

**Comment by ayushmishra2005** [comment]
> We just need to update the rococo-v1 branch. Master already has these changes.

@bkchr What does it mean? Do I need to do anything from my side?

**Comment by bkchr** [comment]
Branch updated
