### ISSUE TITLE
Clean up the parachain-system's ensures

### ISSUE THREAD

**Issue by pepyakin** [paritytech/cumulus#410]
Switch from `ensure` to `panic`s in the parachain-system pallet's `set_validation_data` inherent.

**Comment by JoshOrndorff** [comment]
Can you say more about why this is good? I wondered about the same thing when writing our author inherent. How does this mesh with the "runtime must never panic" rule?

**Comment by bkchr** [comment]
This does not mesh with the "runtime should never panic" rule. An inherent is created by the block producer and if that inputs invalid data it is fine to panic. For normal transactions you should not panic, because this would mean someone can spam you and does not need to pay for it.

**Comment by pepyakin** [comment]
In short, `ensure` should be reserved for bailing on precondition violations under the classic "check-then-side-effects" approach. In the aforementioned place, I used `ensure` after performing side-effecting operations. The alternative was to use `panic!`. While those are more or less equivalent, I thought that `ensure` + errors would be less controversial than panic, but apparently it's the other way around. So I was asked to change that. 

IMO, I also do like more `panic!` because it is simpler and it is what has to be used on the "mandatory" path. The mandatory path is e.g. "on_finalize". Therefore the code will be more coherent.

"runtime must never panic" rule is not absolute. Take the timestamp module for example: we bluntly panic there. This is similar to a mandatory inherent case. We are allowed to panic in such places to make the block producer to do some behavior and make the block invalid unless the behavior satisfies some constraints. (Oh, and Basti beat me to it)

**Comment by shawntabrizi** [comment]
What is the context about it being more controversial?
