### ISSUE TITLE
Default `ParaId` to 1000? Consider config constant instead of in-line definition

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/cumulus#433]
https://github.com/paritytech/cumulus/blob/d01bc247cbbe2a060efea127595bff3d3211ffc1/rococo-parachains/pallets/parachain-info/src/lib.rs#L64

IIUC, all non-system parachains should start at 1000 and will be incremented from there, and now are assigned a value by the relay chain:  https://github.com/paritytech/polkadot/pull/2988

**Comment by bkchr** [comment]
This is no pallet that should be copied.
