### ISSUE TITLE
Allow parachain to build without building all the polkadot runtimes

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#446]
There are 4 runtimes in polkadot, plus the parachain runtime, double it by making both native & wasm build. This is literally killing our life.

It is also killing linker as well. 32 Gb machine constantly getting out of memory when building tests for Acala.

**Comment by shaunxw** [comment]
It kills linker so many times that I even made [a poem](https://twitter.com/shaunofakl/status/1395327066078289923) for this.

**Comment by JoshOrndorff** [comment]
Was this closed intentionally?

**Comment by bkchr** [comment]
Yes, this was done here https://github.com/paritytech/polkadot/pull/3189
