### ISSUE TITLE
Tests, tests, we need tests

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#48]
Yeah, we need tests. We already have "some" unit tests, but we need more. The biggest problem currently is that we lack test primitives. 

It would also be nice to have real integration tests that probably spawn some docker containers that test setting up a parachain and making sure that the collator is working properly. A first implementation could just query the `heads` and make sure that it changes in the relay-chain.

**Comment by bkchr** [comment]
The current test situation is really complicated in Cumulus. We have the folder `tests` that contains some runtime that augments the `substrate-test-runtime` and we use this runtime to test the basic functionality of validating blocks. Than we also got some integration tests by @cecton that use the `rococo-collator`. 

This should be merged together. So, this means the following:

1. Create a proper test runtime (don't use the `substrate-test-runtime`!) that we will be using for the integration tests and the unit tests.
2. Create a test collator that is able to use the `test-runtime` from Polkadot.
3. Everything should live in `tests`.
4. Make sure the STF function of the `test-runtime` is similar flexible as the one from `substrate-test-runtime`.

**Comment by cecton** [comment]
I volunteer myself

**Comment by cecton** [comment]
> It would also be nice to have real integration tests that probably spawn some docker containers that test setting up a parachain and making sure that the collator is working properly. A first implementation could just query the `heads` and make sure that it changes in the relay-chain.

Would that be much different than the (almost real) integration that we have already? The only difference seems to be networking layer. (Maybe I'm mistaking). What do you have in mind?

**Comment by bkchr** [comment]
I don't think we need the docker stuff for now. Was just some idea in january xD
