### ISSUE TITLE
What to do with Unknown Tokens?

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#506]
It's possible that Statemint will receive tokens via XCM that it won't know what to do with.
We should have a conscious strategy on how we want to deal with this.
Most promising is to use [ORML's unknown-tokens pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/unknown-tokens).

**Comment by xlc** [comment]
https://github.com/paritytech/polkadot/issues/2702 is required to handle dust account correctly
