### ISSUE TITLE
Expose relaychain block number

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#512]
Parachain block time is relatively unstable (due to collator production issues) and there is plan to change it from 12s to 6s.
This makes a lot of block number based timing logic hard (e.g. vesting schedule). It will be easier if we can just use relaycahin block number and we can assume it is 6s.

This should allow parachain to access a relatively stable block time, and not requiring us to migrate logic to use timestamp instead (which have its own set if edge cases to handle).

**Comment by JoshOrndorff** [comment]
It is already included in the parachain inherent.  Moonbeam also uses it for our creating schedule for the exact same reason.

https://github.com/PureStake/crowdloan-rewards/blob/16c0e661e5b0f001d6a14c5ba242ab4a271a1912/src/lib.rs#L247
