### ISSUE TITLE
polkadot-v0.9.7 branch?

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/cumulus#513]
Will there be one? there is a https://github.com/paritytech/substrate/tree/polkadot-v0.9.7 -- looking to get the same version in my collator builds for all repos 🙏🏼 

Perhaps this isn't needed, so long as a relatively timely release of polkadot 0.9.8 is on the way that includes [this patch](https://github.com/paritytech/polkadot/commit/b66483bc368812237469e1ff83dfea590fe8050f) for rococo testing.

**Comment by bkchr** [comment]
There wasn't any substantial changes (especially no Substrate bump), so we will not create a branch for it
