### ISSUE TITLE
Implement BlockNumberProvider for cumulus-pallet-parachain-system

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#514]
This will allow other pallets to easily get relaychain block number

**Comment by bkchr** [comment]
That sounds like a bad idea. Why should the parachain-system return the relay chain block number?

**Comment by xlc** [comment]
I mean something like this https://github.com/AcalaNetwork/Acala/blob/f84222b27176e445e36a885b157a9bdb38ec1f96/runtime/common/src/lib.rs#L165-L175

**Comment by bkchr** [comment]
Yeah, that looks much better :P
