### ISSUE TITLE
Docker image for Statemint

### ISSUE THREAD

**Issue by mpetrunic** [paritytech/cumulus#543]
Is there somewhere docker image that runs local testnet/devnet with statemint parachain?
If not are there somewhere some easy to follow instructions to run this setup so I can try to create docker image?

**Comment by bkchr** [comment]
CC @s3krit maybe?

**Comment by TriplEight** [comment]
There's no specific Dockerfile for this, not for packaging the bin, nor any compose file for running a parachain locally.

It should be as easy as just using the same plain [Dockerfile for Polkadot](https://github.com/paritytech/polkadot/blob/master/scripts/docker/Dockerfile).
Run it with
```
docker build
        --tag "statemint:local"
        --file Dockerfile .
```
in the same dir with a compiled binary.
To compile a binary you can use `docker run -it paritytech/ci-linux:production`, then run `git clone <this repo> .` and `cargo build --release` inside.

**Comment by mpetrunic** [comment]
Hey, tnx for quick answers. I am mostly curious how to automate parachain registering inside Dockerfile, all tutorials I found was pointing to do that in UI

**Comment by NukeManDan** [comment]
We added a how-to on `polkadot launch` to the workshop recently you might find useful @mpetrunic , and I opened up [an issue](https://github.com/substrate-developer-hub/cumulus-workshop/issues/92) on the workshop to include docker options for generic testnets, that could be modified for use.

**Comment by BenWhiteJam** [comment]
Maybe the https://github.com/open-web3-stack/parachain-launch by @xlc might be something to look into as well?

**Comment by ayushmishra2005** [comment]
> There's no specific Dockerfile for this, not for packaging the bin, nor any compose file for running a parachain locally.
> 
> It should be as easy as just using the same plain [Dockerfile for Polkadot](https://github.com/paritytech/polkadot/blob/master/scripts/docker/Dockerfile). Run it with
> 
> ```
> docker build
>         --tag "statemint:local"
>         --file Dockerfile .
> ```
> 
> in the same dir with a compiled binary. To compile a binary you can use `docker run -it paritytech/ci-linux:production`, then run `git clone <this repo> .` and `cargo build --release` inside.

@TriplEight I was trying to create docker image of statemine but not getting success. Here are the steps, which I am following: (I am using Mac M1)


```
docker run -it paritytech/ci-linux:production
git clone https://github.com/paritytech/cumulus
git checkout polkadot-v0.9.9
cargo build --release
```

After hitting `cargo build --release`, I am getting 
```

root@725c8307b55e:/builds/cumulus# cargo build --release
    Updating git repository `https://github.com/paritytech/substrate`
Killed Fetch [========>                ]  36.95%, 3.29MiB/s   

```

Please let me know if I am missing any step

**Comment by TriplEight** [comment]
@ayushmishra2005 answered your question in https://github.com/paritytech/cumulus/pull/740.
Most probably, you won't be able to compile the binary on M1 locally, it's a different arch. However, it should be possible within the container as described in PR.
