### ISSUE TITLE
Assets->Balances dropdown clipped

### ISSUE THREAD

**Issue by alice-und-bob** [paritytech/cumulus#554]
The visible area of the dropdown is clipped to the area of the table. The dropdown has a higher height. This clips the content and makes the last items of the list inaccessible.

![image](https://user-images.githubusercontent.com/87834086/127271007-96b56e76-6a06-4607-a5dd-421e8dd05e6c.png)

**Comment by bkchr** [comment]
This is not polkadot-js or whatever UI you are using there.
Please open it in the correct repo.
