### ISSUE TITLE
--name flag is not working for the embedded relay node

### ISSUE THREAD

**Issue by purestakeoskar** [paritytech/cumulus#556]
Parachain nodes are supposed to pass any cli flags that are supplied after a -- to the embedded relay chain node. However, it seems that the --name parameter does not affect the embedded relay chain node. --name works fine for the parachain node itself, and many flags work fine for the embedded relay, but the combination does not work together.

Example command to reproduce this issue: `moonbeam --chain moonriver --name test-node-parachain -- --name test-node-embedded-relay`

To see this, we can go to any node that this node is connected to and look at its relay peers. If we do that we will see that the name sent over the peer is something randomly generated and not what we sent in as a CLI flag, for example this one: `agreeable-step-8709`.

**Comment by purestakeoskar** [comment]
One additional way of seeing this issue is to go to Kusamas telemetry page: https://telemetry.polkadot.io/#list/Kusama
All parachain nodes are showing up with the auto generated name.
![image](https://user-images.githubusercontent.com/45081138/128358011-388ea3e9-b3dd-4aea-bac9-8d5a262a797f.png)

It looks like all parachain nodes are prefixed with the same icon, so it should be pretty easy to find.
![image](https://user-images.githubusercontent.com/45081138/128358071-d2e0afd3-8510-4ad8-8706-09c7220785b4.png)

**Comment by PierreBesson** [comment]
I confirm this issue, passing `--name node-name` after the `--` should correctly set the node name on the relay chain side which would show up in telemetry.
