### ISSUE TITLE
Parachain Runtime Upgrade Halt

### ISSUE THREAD

**Issue by dt665m** [paritytech/cumulus#587]
Cumulus/Polkadot Version: v0.9.8

Repro Steps:
- Start rococo-local with alice, bob, charlie and dave
- sudoScheduleParaInitialize
- build a new runtime with srtool
- on parachain, sudo(tx.parachainSystem.authorizeUpgrade) using srtool's compact wasm hash
- on parachain, sudo(tx.parachainSystem.enactAuthorizedUpgrade)

Result: 
The parachain gets stuck being scheduled repeatedly unto further blocks, with event: ```parachainSystem.ValidationFunctionApplied```. Meanwhile, the relay is warning  ```tokio-runtime-worker parachain::availability-distribution: Some network error occurred when fetching erasure chunk origin=Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (iQVBY1dB...)) err=Network(ConnectionClosed).``` The relaychain will drop peers when this warning occurs and the parachain just stops making progress, with the schedule pushing back indefinitely.

Any idea what this might be? Some guidance would be appreciated.

**Comment by bkchr** [comment]
Do you run all nodes on the same machine? Please try again master. 

For other people this is working and I tested runtime upgrade yesterday.

**Comment by GopherJ** [comment]
Just tested it worked for me

**Comment by dt665m** [comment]
will report back with master.  Thanks guys

**Comment by dt665m** [comment]
@bkchr I upgraded everything to master and I'm seeing the exact same thing.  I'm starting to think it is the way that I have the relay network launched that might be causing the connectivity issue.  I'm not using the launch utility.  I have manually setup startup scripts for all 4 validators that look something like this
```
alice:
		target/release/polkadot \
		--tmp \
		--chain ./target/rococo-custom.json \
		--name relay0 \
                 --node-key 0000000000000000000000000000000000000000000000000000000000000000 \
		--alice \
		--validator \
		--rpc-port 19933 \
		--ws-port 19944 \
		--port 10444 \
		--unsafe-rpc-external \
		--unsafe-ws-external \
		--rpc-methods=Unsafe \
		--rpc-cors all

bob:
		@target/release/carbon \
		--tmp \
		--chain ./target/rococo-custom.json \
		--name relay1 \
                 --node-key 1111111111111111111111111111111111111111111111111111111111111111 \
		--bob \
		--validator \
		--rpc-port 29933 \
		--ws-port 29944 \
		--port 20444 \
		--unsafe-rpc-external \
		--unsafe-ws-external \
		--rpc-methods=Unsafe \
		--bootnodes /dns4/localhost/tcp/10444/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN

charlie...
dave...
```

After an upgrade is initiated on the parachain, the relay network just keeps having strange connectivity issues trying to get erasure coding chunks.  I don't know if this is also a clue but the current master has an overseer worker that also just keeps reporting this:

```
 WARN tokio-runtime-worker parachain::gossip-support: Low connectivity - authority lookup failed for too many validators. connected=3 target=4
```

I assume this is harmless since alice, bob, charlie and dave will only connect to 3 each (minus themselves).

**Comment by dt665m** [comment]
Sorry for the late update on this.  I tracked the issue down to this configuration [line](https://github.com/paritytech/polkadot/blob/master/node/network/protocol/src/request_response/mod.rs#L136), which leads me to believe that maybe our runtime is too large.  If I lower the denominator a bit, then the relay node's libp2p protocol extensions will service the the chunks requests/response properly.

It was a bit difficult to track this down because the symptom was just dropped libp2p connections due to hitting these configuration limits. 

Is there documentation somewhere about these limits and what the implications are?

**Comment by bkchr** [comment]
@dt665m how big is your runtime?

**Comment by bkchr** [comment]
@eskimor this sound like a bug? Aka we should have filtered this out much earlier instead of failing on some later stage?

**Comment by dt665m** [comment]
@bkchr way too big apparently.  There must be something wrong, the compact version is clocking in at 20mb and change.

**Comment by eskimor** [comment]
Yeah, there should be some error logged. The warning about low connectivity should be fixed with [this](https://github.com/paritytech/polkadot/pull/3855).

I think I know what is going on. There is no other error, because well we are within [limits](https://github.com/paritytech/polkadot/blob/143a30874f618c9f3c1e8eca09a526e432382572/primitives/src/v1/mod.rs#L237), buuuut we an assumption [here](https://github.com/paritytech/polkadot/blob/8fab1d8f3039ce79215f2f1adefa769260d9228c/node/network/protocol/src/request_response/mod.rs#L136) that chunks are at least 10 times smaller than the original payload. Which does not hold for small test networks.

Not sure what to do about this. I would not like to increase that limit and we also don't know at compile time how big the network is going to be, ... so :thinking:  We would need to adjust limits at runtime, which sounds troublesome.

**Comment by bkchr** [comment]
This should be fixed now with latest polkadot master.
