### ISSUE TITLE
Exported method ParachainHost_availability_cores is not found

### ISSUE THREAD

**Issue by GopherJ** [paritytech/cumulus#594]
I experienced the following error while running a fullnode for our parachain slot auction. The script can be found at:
https://github.com/parallel-finance/parallel/blob/master/scripts/fullnode.sh

The error details are:

![image](https://user-images.githubusercontent.com/33961674/131350369-14ed59f7-c42f-4491-9995-f2459841ed88.png)

I cannot reproduce this error using rococo/westend, it just happens with kusama

**Comment by GopherJ** [comment]
hi @bkchr sorry to ping you, can I get some quick info from you on this? Shall I worry about this problem?

it happens while launching collators, but the collator can sync blocks correctly, I stopped all our collators for now to just make sure that there aren't any bad things:)

**Comment by stechu** [comment]
@bkchr  I can confirm we get the same error.

**Comment by al3mart** [comment]
Do the nodes stall or continue syncing? If they continue syncing then just ignore it; it's a simple matter of the parachains code trying to fetch state from ancient blocks which don't contain parachains logic in their runtime. What makes total sense for it to inly happen in Kusama.

**Comment by stechu** [comment]
The nodes continues syncing.
@al3mart  Thanks! Honestly this should be fixed (or at least put as a known issue).

**Comment by bkchr** [comment]
If this happens while syncing, you can just ignore it. Kusama didn't had the parachain feature from genesis, so some functions are not available.
