### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#595]
We will want to add tests to ensure that Statemint/e work as expected.
Example tests:
+ asset creation and minting
+ transfers
+ XCM transfers

### Ideas
- [ ] use XCM Emulator for testing XCM integration
- [x] polkadot-js based interaction with the chain
- [ ] manual testing of e.g. Rockmine

**Comment by NachoPal** [comment]
I'll start with "polkadot-js based interaction with the chain"

**Comment by apopiak** [comment]
## Integration Tests
Basic skeleton for integration tests (not comprehensive).
### Statemint Extrinsics
Test that functionality local to the chain works.
#### Fungible Assets
Test that basic asset operations work.
+ `Assets::create`
+ `Assets::set_metadata`
+ `Assets::mint`
+ `Assets::transfer`

Note: We can probably collapse steps into `batch_all` calls to reduce test times)

#### Asset Tx Payment
Test that we can pay transactions in assets.
+ `Assets::force_create` with `is_sufficient = true`
+ `Assets::mint`
+ `Assets::transfer`, using the newly created asset for tx payment

#### Non-Fungible Assets
Test that we can do basic operations on non-fungible tokens.
+ `Uniques::create`
+ `Uniques::mint`
+ `Uniques::transfer`

### XCM Tests
#### Teleport
Test that teleports between Statemint and relay chain work.
##### Statemint to Relay
+ `PolkadotXcm::limited_teleport_assets` on Statemint
##### Relay to Statemint
+ `PalletXcm::limited_teleport_assets` on the relay

**Comment by NachoPal** [comment]
I created a new repository where all test can be found: https://github.com/NachoPal/parachains-integration-tests

How I see it is to create a CI job that can be triggered manually with three inputs:
- Parachain release binary
- Relaychain release binary
- URL to `parachains-integration-tests` release branch to use to run the tests

The job will do the following:
1. Deploy a Parachain<>Relaychain infra  with the `config.json` file found in `parachains-integration-tests` branch and the provided Parachain and Relaychain binaries.
2. Once the Parachain is producing blocks -> `yarn test`

**Comment by apopiak** [comment]
### Integration Tests for Statemint Release
+ [ ] permissionless asset creation turned off
+ [ ] test force_create instead

**Comment by apopiak** [comment]
Tested teleport Statemint -> Polkadot and ran into https://github.com/paritytech/polkadot/issues/4462
