### ISSUE TITLE
I encountered a bug when the offchain_worker of the parachain started:

### ISSUE THREAD

**Issue by kami1983** [paritytech/cumulus#597]
Thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/mac/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.10.0/src/runtime/context.rs:18

panic at esponse = pending.try_wait(deadline), What is the reason and how to solve it? code fork from paritytech/cumulus master branch.

![image](https://user-images.githubusercontent.com/8407663/131953921-cf8714d2-7e59-4e94-9036-e6177d4cd9c0.png)

My code:

![image](https://user-images.githubusercontent.com/8407663/131954075-83dbe491-a279-4fa5-8506-2983f8ad357c.png)

tokio-runtime-worker cumulus-collator: [Parachain] Starting collation. relay_parent=0x9b860c10735da6c664f0a16829bb8554e81adc25b7a3861182627516306fdb29 at=0x61305e123363d0d1bcda9c19fbe163d78949d82ef30df80b5f9b9d897e054a1a

====================

Version: 0.1.0-3b5572a-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   7: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   8: core::option::expect_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
   9: std::thread::local::LocalKey<T>::with
  10: tokio::io::poll_evented::PollEvented<E>::new
  11: tokio::net::tcp::stream::TcpStream::new
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  18: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  19: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
  20: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
  24: <sc_offchain::api::http::HttpWorker as core::future::future::Future>::poll
  25: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  28: tokio::runtime::task::core::Core<T,S>::poll
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  30: tokio::runtime::task::raw::poll
  31: std::thread::local::LocalKey<T>::with
  32: tokio::runtime::thread_pool::worker::Context::run_task
  33: tokio::runtime::thread_pool::worker::Context::run
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
  35: tokio::runtime::thread_pool::worker::run
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  37: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  38: tokio::runtime::task::harness::Harness<T,S>::poll
  39: tokio::runtime::blocking::pool::Inner::run
  40: tokio::runtime::context::enter
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
  42: core::ops::function::FnOnce::call_once{{vtable.shim}}
  43: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  44: __pthread_start

Thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/mac/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tokio-1.10.0/src/runtime/context.rs:18

This is a bug. Please report it at:

	https://github.com/paritytech/cumulus/issues/new

**Comment by bkchr** [comment]
Should be fixed now.
