### ISSUE TITLE
Compact proof decoding fails when using the child trie

### ISSUE THREAD

**Issue by yrong** [paritytech/cumulus#598]
```
2021-09-03 11:47:24 panicked at 'Compact proof decoding failure.', /home/bifrost/.cargo/git/checkouts/cumulus-59522f43471fa161/fd80849/pallets/parachain-system/src/validate_block/implementation.rs:80:19 
```

After upgrade to [v0.9.9](https://github.com/bifrost-finance/bifrost/blob/develop/Cargo.lock) we've encounted this error several times when sending multiple ump transacts to relaychain.  And workround is to [hack in cumulus](https://github.com/bifrost-finance/cumulus/commit/04262f9cb243ebca93f031ccfe858984d7012ec9) to disable compact

We can  reproduce the issue and provide more logs if required, would be appreciated if anybody can help to trace and diagnose the root cause

**Comment by bkchr** [comment]
Sounds like your runtime isn't using the 0.9.9 branch yet?

**Comment by yrong** [comment]
> Sounds like your runtime isn't using the 0.9.9 branch yet?

@bkchr https://github.com/bifrost-finance/bifrost/blob/4e407dec25877805973a6e15cd3712fec11ff2ba/Cargo.lock#L1948 don't think so, any other possibility?

**Comment by yrong** [comment]
@bkchr We find the cause. It will work after commenting [these codes]( 
https://github.com/bifrost-finance/bifrost/blob/8a48da270c8f7fb20ea0cf7fd48641d4f4c34fc3/pallets/salp/src/lib.rs#L595-L600)
```
fn put_contribution(
			index: TrieIndex,
			who: &AccountIdOf<T>,
			contributed: BalanceOf<T>,
			status: ContributionStatus<BalanceOf<T>>,
		) {
			who.using_encoded(|b| {
				child::put(&Self::id_from_index(index), b, &(contributed, status))
			});
		}
```

So is the usage of child storages allowed in parachain?

**Comment by bkchr** [comment]
@cheme it seems that using the child trie breaks the compact proof?

**Comment by cheme** [comment]
Looks like it.
@yrong , do you have by any change a failing encoded compact proof (I don't think their is trace displaying it but maybe when you did your work around you did extract it somehow).

**Comment by yrong** [comment]
@cheme not sure fully catch what you mean.  Maybe you can give some guidance about how to hack or produce detail logs which you think useful to debug.

Btw, child trie struct in our parachain side is just same as [crowdloan module](https://github.com/paritytech/polkadot/blob/f9f4754020611564aef4f235713ea744232f5425/runtime/common/src/crowdloan.rs#L710-L717), I think you can reproduce easily if more than one entry of child_info stored
```
pub fn put<T: Encode>(child_info: &ChildInfo, key: &[u8], value: &T) {
	match child_info.child_type() {
		ChildType::ParentKeyId => value.using_encoded(|slice| {
			sp_io::default_child_storage::set(child_info.storage_key(), key, slice)
		}),
	}
}
```

**Comment by cheme** [comment]
https://github.com/bifrost-finance/cumulus/commit/04262f9cb243ebca93f031ccfe858984d7012ec9#r56045962
I did found https://github.com/paritytech/substrate/pull/9715 that can explain the issue, but with a failing compact proof sample, it will be safer.

**Comment by bkchr** [comment]
@yrong could you test the pr mentioned above?

**Comment by yrong** [comment]
@cheme  verified and it works, thanks for the quick fix.  @bkchr I guess parity would publish a patch and upgrade relaychain right?  If so what is the next open window to upgrade kusama so we can arrange our release date accordingly.

**Comment by cheme** [comment]
Nice (actually the bug was my fault).
For this change the relay chain do not need upgrade, the decoding of the proof is done by the validation function of the cumulus parachain, so it requires an update of the parachain validation function.

**Comment by bkchr** [comment]
> @cheme verified and it works, thanks for the quick fix. @bkchr I guess parity would publish a patch and upgrade relaychain right? If so what is the next open window to upgrade kusama so we can arrange our release date accordingly.

We will include it in the 0.9.10 branch!
