### ISSUE TITLE
Rococo "wss://rococo-rpc.polkadot.io" is not accessible 

### ISSUE THREAD

**Issue by prasannayasan** [paritytech/cumulus#621]
I have been using rococo instance for few weeks, from today unable to access this, even the instance itself is not getting created. 

Sample snippet : 
``` 
const { ApiPromise, WsProvider } = require("@polkadot/api");
const wsProvider = new WsProvider('wss://rococo-rpc.polkadot.io');
module.exports.API = ApiPromise.create({ provider: wsProvider });

this.API.then(async (api) => {
    const chain = await api.rpc.system.chain();
    const lastHeader = await api.rpc.chain.getHeader();
    
     console.log(
      `Connected to ${chain.toHuman()} with genesis Hash: ${api.genesisHash.toHex()}, latest block #${
        lastHeader.number
      } has hash ${lastHeader.hash}`
    );
});
  
```
Getting following error while instance creation : 
```
 RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0e7906000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
```

Is there any issue from the rococo side ?

**Comment by prasannayasan** [comment]
Fetch the latest metadata with `api.rpc.state.getMetadata()` as shown in this [substrate doc](https://substrate.dev/docs/en/knowledgebase/runtime/metadata#javascript)

Even after doing that, API instance is not getting created, just getting the following error continuously.

```
API-WS: disconnected from wss://rococo-rpc.polkadot.io: 1006:: Connection dropped by remote peer
```

**Comment by rphmeier** [comment]
cc @PierreBesson

**Comment by prasannayasan** [comment]
I have updated all the polkadot dependencies used in the project. Even now when I try to create api instance its throwing error. 
It's unable to fetch the metadata [api.rpc.state.getMetadata()] as well. 
```
API-WS: disconnected from wss://rococo-rpc.polkadot.io: 1006:: Connection dropped by remote peer.
 RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0e9106000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: decodeU8a: failed at 0x0e9106000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
    at EventEmitter.value (/Users/prasanna.pandiyan@coinbase.com/coinbase-workspace/Polkadot_Project/kusama-rosetta-javascript-implementation/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
It works fine if I use "wss://kusama-rpc.polkadot.io" or "wss://polkadot-rpc.polkadot.io". but we need rococo for all testing.

**Comment by PierreBesson** [comment]
@prasannayasan I cannot reproduce your error, I think you need to make sure of bumping your dependencies and lockfile versions to the latest.
I have setup a [demo repo](https://github.com/PierreBesson/demo-rococo-connection) that you can try.

**Comment by bkchr** [comment]
> I have updated all the polkadot dependencies used in the project. Even now when I try to create api instance its throwing error.
> It's unable to fetch the metadata [api.rpc.state.getMetadata()] as well.
> 
> ```
> API-WS: disconnected from wss://rococo-rpc.polkadot.io: 1006:: Connection dropped by remote peer.
>  RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: decodeU8a: failed at 0x0e9106000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
> API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: decodeU8a: failed at 0x0e9106000c1c7370… on metadata:: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13
>     at EventEmitter.value (/Users/prasanna.pandiyan@coinbase.com/coinbase-workspace/Polkadot_Project/kusama-rosetta-javascript-implementation/node_modules/@polkadot/api/base/Init.cjs:88:25)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> It works fine if I use "wss://kusama-rpc.polkadot.io" or "wss://polkadot-rpc.polkadot.io". but we need rococo for all testing.

You are not using the latest polkadot-js version.
