### ISSUE TITLE
Statemine code: -32601, message: 'Method not found' 

### ISSUE THREAD

**Issue by Wangmmx** [paritytech/cumulus#628]
When I tried to get nonce from chain by `system_accountNextIndex`, it got the error:
`code: -32601, message: 'Method not found'`

This api is a common JSON-RPC api of polkadot, so is that a bug need fixed?

**Comment by bkchr** [comment]
The RPC is currently not exposed on the live network, but it will come with the next update. Aka, it already works on master.
