### ISSUE TITLE
[CI/CD] Add benchmarking CI job

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#631]
It would be great to have a manual job to execute runtime benchmarks we can start from gitlab that spits out a git patch of the adjusted weights we can apply afterwards.
Analogous to the benchmarking CI in the Polkadot repo.

**Comment by NachoPal** [comment]
Is it work in progress? I need to update the Benchmark section in #661 and I am not sure if this is going to be done soon or we keep the manual process for now.

**Comment by sea212** [comment]
Maybe https://github.com/zeitgeistpm/zeitgeist/blob/main/.github/workflows/benchmark.yml can become handy. 
Once "benchmark-required" label is set on a PR, the CI is triggered and pulls the branch. It benchmarks currently every pallet and the pallets are hard-coded, but this will be optimized in the future. A report is created and posted in the PR and the changes are committed, if no other changes have been added meanwhile. The CI indicates with a label that it's done and whether the benchmark was successful.
The following link references setting the label and the resulting actions from the benchmark (expand following comments): https://github.com/zeitgeistpm/zeitgeist/pull/207#event-4958808872
