### ISSUE TITLE
benchmark_metadata missing for polkadot-v0.9.10

### ISSUE THREAD

**Issue by NachoPal** [paritytech/cumulus#637]
Can not build with `--features runtime-benchmarks` for `polkadot-v0.9.10` because missing `benchmark_metadata`

Related to: #589

**Comment by bkchr** [comment]
You are probably waiting for this: https://github.com/paritytech/cumulus/releases/tag/untagged-19e479f28aee3a0eb1da

**Comment by bkchr** [comment]
`polkadot-v0.9.10` branch is the "cumulus release", not statemine/statemint

**Comment by NachoPal** [comment]
Yes, I know. I found that accidentally comparing benchmarks implementations between branches. I know I don't need that fixed for the Statemint release. Actually in `release-statemine-v4`, `benchmark_metadata` is not missing.

**Comment by bkchr** [comment]
So this is fixed?

**Comment by NachoPal** [comment]
It is not, giving a heads up. Not sure if there was some reason for not having it.

**Comment by bkchr** [comment]
You mean this error now: https://github.com/paritytech/cumulus/issues/588 ?

**Comment by NachoPal** [comment]
No, I meant the initial issue of this thread:

> Can not build with --features runtime-benchmarks for polkadot-v0.9.10 because missing benchmark_metadata

**Comment by bkchr** [comment]
Yeah the point being that this is a branch for parachain developers and should not be used for anything statemine related.
