### ISSUE TITLE
Exported method CollectCollationInfo_collect_collation_info is not found

### ISSUE THREAD

**Issue by jerryjren** [paritytech/cumulus#641]
Hi there,

I'm working get our project ready for parachain.

After parachain registration with local rococo local testnet, I got below error in the parachain console.

`2021-10-04 11:23:54 [Parachain] PoV size { header: 0.1787109375kb, extrinsics: 0.01171875kb, storage_proof: 1.8193359375kb }`
`2021-10-04 11:23:54 [Parachain] ✨ Imported #1 (0xf164…59f0)`
`2021-10-04 11:23:54 [Parachain] Failed to collect collation info. error=Application(Execution(Other("Exported method CollectCollationInfo_collect_collation_info is not found")))`
`2021-10-04 11:23:56 [Parachain] 💤 Idle (0 peers), best: #0 (0xa2fb…a45f), finalized #0 (0xa2fb…a45f), ⬇ 0 ⬆ 0`

Any idea what went wrong? Thanks you

regards
Jerry

**Comment by bkchr** [comment]
As commented on element. Your runtime & node weren't build from the same source. 

Make sure to rebuild everything and also don't use any old chain spec!
