### ISSUE TITLE
Move pallet-asset-tx-payment into Substrate

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#688]
There is nothing cumulus specific about pallet-asset-tx-payment so it makes sense to upstream it to the Substrate repo.
As it wraps and extends pallet-transaction-payment it makes sense for it to live there.

**Comment by georgesdib** [comment]
I have taken a stab at this in paritytech/substrate#10127
The corresponding cumulus PR is #712 but, correct me if I am wrong, I cannot merge that until the substrate PR is merged given the `Cargo.toml` dependencies.

**Comment by apopiak** [comment]
@georgesdib You will need to set the dependency of #712 to your substrate branch and communicate to the bot that it is the companion for  paritytech/substrate#10127
