### ISSUE TITLE
Keep some un-pinned parachain blocks

### ISSUE THREAD

**Issue by rphmeier** [paritytech/cumulus#7]
A "pinned" parachain block is one who's been referenced by a block in the relay chain. Blocks that have been freshly authored by collators are initially are unpinned, while they are circulated and gather attestations from validators. We don't want to keep an unbounded number of unpinned blocks, because it can be a DoS vector and complicates fork-choice.

However, assuming that collators are good and broadcast out the block data for unpinned blocks in a way which is easily obtainable by peers, it is more efficient for other full nodes to keep the unpinned block with the expectation that it likely will be pinned. This means that as soon as the block is pinned, a collator can build on top of it for the next block, rather than having to fetch it and then start building.

Every parachain block needs to reference some data from Polkadot (#5) including incoming messages and relay chain block hash.

There should be an import queue verifier which accepts new blocks if:
  - they are pinned
  - they are unpinned and the Polkadot block hash referenced is a leaf.

**Comment by rphmeier** [comment]
CC @bkchr 

The previous spec is actually vulnerable to equivocations.
What we want is to accept unpinned blocks iff
  - parent is pinned
  - we have a `Candidate(h)` message for `h = unpinned_block_header.hash()`

Then we will only import blocks which are being considered by validators.

**Comment by bkchr** [comment]
Furthermore we should only announce blocks that have a candidate message. Other collators should import blocks at the top only if they provide a candidate message and `relay_chain_head == candidate_msg.relay_parent`.

**Comment by bkchr** [comment]
This is finished now :)
