### ISSUE TITLE
Add version numbers to the runtime filenames artifacts

### ISSUE THREAD

**Issue by chevdor** [paritytech/cumulus#706]
This should be done as in Polkadot:
![image](https://user-images.githubusercontent.com/738724/139086972-8ff11407-1514-489b-ac3e-ea0be166206e.png)

Currently cumulus names them without the version number and that may lead to errors:
![image](https://user-images.githubusercontent.com/738724/139088975-a18e8c11-1d1e-47e5-8532-3acbe10b2cdb.png)

cc @lovelaced

**Comment by chevdor** [comment]
cc @lovelaced 
This was done manually in this repo until now. It has now been intregrated to the CI and the next (pre)-release will keep adding the version numbers as part of the filename as `statemine_runtime-v600.compact.compressed.wasm` for instance.

Please note that the best (as in "don't trust the number CI is adding") remains to look into the wasm itself.
This can be done easily using `subwasm`:
```
subwasm info statemine_runtime-v600.compact.compressed.wasm --json | jq .core_version
```

and will return:
```
"statemine-600 (statemine-0.tx4.au1)"
```

**Comment by lovelaced** [comment]
Thanks @chevdor !!
