### ISSUE TITLE
Common Good Parachain Template

### ISSUE THREAD

**Issue by HCastano** [paritytech/cumulus#714]
After a chat with @NukeManDan today we think that it would be nice to have the parachain template contain two runtimes. One for common good parachains, which defer their governance and token structure to the relay chain, and another for sovereign chains which use their own governance and tokens.

These two types of chains require different configuration parameters for things like XCM, so a single runtime isn't sufficient to capture the different nuances.

Chains like [Canvas](https://github.com/paritytech/canvas/) could then use the common good runtime as a reference for keeping in sync with the latest changes in Cumulus.

**Comment by bkchr** [comment]
I'm against adding another runtime. This adds just more compilation times. There is not that much difference between a common good parachain and a normal one. In the future the Canvas chain will probably need to evolve anyway and that means that the runtime will be much more different than the template.

**Comment by bkchr** [comment]
I would also argue that a XCM configuration should always require a really good "manual" review that shouldn't be done by a machine. I understand where you are coming from, however I would propose to add tests that ensure that XCM works as expected in Canvas. This way you will be able to ensure that the stuff always works as you expect it.

**Comment by cmichi** [comment]
@HCastano @NukeManDan What's the state of this issue? Should we close it?
