### ISSUE TITLE
build-spec subcommand is missing --parachain-id argument

### ISSUE THREAD

**Issue by GopherJ** [paritytech/cumulus#728]

**Comment by GopherJ** [comment]
this is causing `parachainInfo::parachain_id` to be different with `para id` in Extensions. build-spec subcommand should accept `--parachain-id` argument

**Comment by GopherJ** [comment]
Ref: https://github.com/paritytech/polkadot/issues/4232#issuecomment-963759041

**Comment by bkchr** [comment]
`parachain-id` was a mainly used for testing. So, we are going to remove this entirely to make this more explicit: https://github.com/paritytech/cumulus/pull/739
