### ISSUE TITLE
Thread panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by tgmichel** [paritytech/cumulus#73]
Following the README instructions for running the project leads to this issue with the collator node. Reproducible by manually following [Running a collator](https://github.com/paritytech/cumulus#running-a-collator) or by simply executing the built-in scripts referenced in [Running the collator automatically](https://github.com/paritytech/cumulus#running-the-collator-automatically).

`Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2`

A complete trace can be seen in [this gist](https://gist.github.com/tgmichel/1327193709654bcdfeee9ec8e31f4e0c).

**Comment by bkchr** [comment]
Master is working fine, so this is probably already fixed. Thank you anyway.
