### ISSUE TITLE
Statemine v6 Release (+ Westmint)

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#744]
# Release Checklist

This is the release checklist for Statemine v6 and the initial version of
Statemint :tada: (also v6 because of code parity with Statemine).
**All** following checks should be completed before publishing a
new release of the Statemine runtime. The current release candidate can be
checked out with `git checkout release-statemine-v6`.

### Runtime Releases

These checks should be performed on the codebase.

- [x] Verify [`spec_version`](#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public
    (non-private/test) networks.
- [x] Verify previously [completed migrations](#old-migrations-removed) are
    removed for any public (non-private/test) networks. @apopiak 
  - No migrations added in the last release that would need to be removed.
- [x] Verify pallet and [extrinsic ordering](#extrinsic-ordering) as well as `SignedExtension`s have stayed
    the same. Bump `transaction_version` if not. @NachoPal 
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for
    [proxy filters](#proxy-filtering). @apopiak  
  - No new extrinsics.
- [x] Verify [benchmarks](#benchmarks) have been updated for any modified
    runtime logic. @NachoPal 
  - [x] Verify the weights are up-to-date. @NachoPal 
- [x] Verify that the various pieces of XCM config are sane. @apopiak 

The following checks can be performed after we have forked off to the release-
candidate branch or started an additional release candidate branch (rc-2, rc-3, etc)

- [x] Verify [new migrations](#new-migrations) complete successfully, and the
    runtime state is correctly updated for any public (non-private/test)
    networks.
- [x] Verify [Polkadot JS API](#polkadot-js) are up to date with the latest
    runtime changes.
- [x] Push runtime upgrade to Westmint and verify network stability.

### All Releases

- [x] Check that the new polkadot-collator versions have [run on the network](#burn-in)
    without issue. @PierreBesson 
- [x] Check that a draft release has been created at
    https://github.com/paritytech/cumulus/releases with relevant [release
    notes](#release-notes) @chevdor 
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release @chevdor 

### Burn In

Ensure that Parity DevOps has run the new release on Westmint and Statemine collators for 12h prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code
- Wasm binaries of any runtimes

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://github.com/paritytech/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes separated into sections.

### Spec Version

A runtime upgrade must bump the spec number. This may follow a pattern with the
client release (e.g. runtime v12 corresponds to v0.8.12, even if the current
runtime is not v11).

### Old Migrations Removed

Previous `on_runtime_upgrade` functions from old upgrades should be removed.

### New Migrations

Ensure that any migrations that are required due to storage or logic changes
are included in the `on_runtime_upgrade` function of the appropriate pallets.

### Extrinsic Ordering & Storage

Offline signing libraries depend on a consistent ordering of call indices and
functions. Compare the metadata of the current and new runtimes and ensure that
the `module index, call index` tuples map to the same set of functions. It also checks if there have been any changes in `storage`. In case of a breaking change, increase `transaction_version`.

To verify the order has not changed, manually start the following [Github Action](https://github.com/paritytech/cumulus/actions/workflows/extrinsic-ordering-check-from-bin.yml). It takes around a minute to run and will produce the report as artifact you need to manually check.

To run it, in the _Run Workflow_ dropdown:
1. **Use workflow from**: to ignore, leave `master` as default
2. **The WebSocket url of the reference node**:
    - Statemine: `wss://kusama-statemine-rpc.paritytech.net`
    - Westmint: `wss://westmint-rpc.polkadot.io`
3. **A url to a Linux binary for the node containing the runtime to test**: Paste the URL of the latest release-candidate binary from the draft-release on Github. The binary has to previously be uploaded to S3 (Github url link to the binary is constantly changing)
    - https://releases.parity.io/cumulus/statemine-v6.0.0-rc1/polkadot-collator
4. **The name of the chain under test. Usually, you would pass a local chain**:
    - Statemine: `statemine-local`
    - Westmint: `westmint-local`
5. Click **Run workflow**

When the workflow is done, click on it and download the zip artifact, inside you'll find an `output.txt` file. The things to look for in the output are lines like:

- `[Identity] idx 28 -> 25 (calls 15)` - indicates the index for Identity has changed
- `[+] Society, Recovery` - indicates the new version includes 2 additional modules/pallets.
- If no indices have changed, every modules line should look something like `[Identity] idx 25 (calls 15)`

**Note**: Adding new functions to the runtime does not constitute a breaking change
as long as the indexes did not change.

**Note**: Extrinsic function signatures changes (adding/removing & ordering arguments) are not caught by the job, so those changes should be reviewed "manually"

### Proxy Filtering

The runtime contains proxy filters that map proxy types to allowable calls. If
the new runtime contains any new calls, verify that the proxy filters are up to
date to include them.

### Benchmarks

Until #631 is done, running the benchmarks is a manual process:
1. Connect to the bechmarking machine `149.202.69.202`
2. Make sure no one else is using the machine with `htop check`
3. Pull in the branch of Cumulus that has the version of Statemine you want to release
4. Recompile `cargo build --release --features runtime-benchmarks`
5. From the root directory run `nohup ./scripts/benchmarks.sh &` (it will take quite a few hours)
6. Checkout in your local machine to the branch of cumulus that has the version of Statemine you want to release
7. `scp` from the host to your local machine the weights for Statemine, Westmint and Statemint you'll find in:
   - `/polkadot-parachains/statemine/src/weights`
   - `/polkadot-parachains/westmint/src/weights`
   - `/polkadot-parachains/statemint/src/weights`
8. Commit the changes in your local and create a PR

### Polkadot JS

Ensure that a release of [Polkadot JS API](https://github.com/polkadot-js/api/) can interact with the new runtime (mostly related to RPCs with the new metadata).

**Comment by apopiak** [comment]
First RC is being prepared in https://github.com/paritytech/cumulus/pull/741

**Comment by apopiak** [comment]
We'll want to include https://github.com/paritytech/cumulus/pull/743

**Comment by chevdor** [comment]
Keeping track of the extrinc Ordering tests here:

## Statemine

```
## Deletions
👉12: [-] modules: RandomnessCollectiveFlip
👉15: [-] calls: setUpgradeBlock
👉25: [-] storage: pendingRelayChainBlockNumber, lastUpgrade

## Index changes
16: [setValidationData] idx: 1 -> 0 (args: 1)
18: [sudoSendUpwardMessage] idx: 2 -> 1 (args: 1)
20: [authorizeUpgrade] idx: 3 -> 2 (args: 1)
22: [enactAuthorizedUpgrade] idx: 4 -> 3 (args: 1)
```
source: https://github.com/paritytech/cumulus/runs/4179400913?check_suite_focus=true

## Statemint

```
## Deletions
 18: [-] calls: setUpgradeBlock
28: [-] storage: pendingRelayChainBlockNumber, lastUpgrade

## Index changes
 19: [setValidationData] idx: 1 -> 0 (args: 1)
21: [sudoSendUpwardMessage] idx: 2 -> 1 (args: 1)
23: [authorizeUpgrade] idx: 3 -> 2 (args: 1)
25: [enactAuthorizedUpgrade] idx: 4 -> 3 (args: 1)
```

source: https://github.com/paritytech/cumulus/runs/4180260451?check_suite_focus=true

## Westmint

```
## Deletions
 12: [-] modules: RandomnessCollectiveFlip
15: [-] calls: setUpgradeBlock
25: [-] storage: pendingRelayChainBlockNumber, lastUpgrade

## Index changes
 16: [setValidationData] idx: 1 -> 0 (args: 1)
18: [sudoSendUpwardMessage] idx: 2 -> 1 (args: 1)
20: [authorizeUpgrade] idx: 3 -> 2 (args: 1)
22: [enactAuthorizedUpgrade] idx: 4 -> 3 (args: 1)
27: [Sudo] idx: 5 -> 255 (calls: 4, storage: 2)
28: [Balances] idx: 6 -> 10 (calls: 6, storage: 6)
29: [Authorship] idx: 8 -> 20 (calls: 1, storage: 4)
30: [CollatorSelection] idx: 9 -> 21 (calls: 5, storage: 6)
31: [Session] idx: 10 -> 22 (calls: 2, storage: 8)
32: [Assets] idx: 14 -> 50 (calls: 23, storage: 5)
33: [Multisig] idx: 15 -> 41 (calls: 4, storage: 3)
34: [Proxy] idx: 16 -> 42 (calls: 10, storage: 3)
35: [PolkadotXcm] idx: 18 -> 31 (calls: 10, storage: 10)
36: [DmpQueue] idx: 20 -> 33 (calls: 1, storage: 5)
37: [Uniques] idx: 21 -> 51 (calls: 22, storage: 7)
```

source: https://github.com/paritytech/cumulus/runs/4180272299?check_suite_focus=true

**Comment by apopiak** [comment]
bumping transaction version: https://github.com/paritytech/cumulus/pull/748

**Comment by jacogr** [comment]
This should be skippable now (RPCs are slightly different, since they are not describing yet, but also not critical if not added) -

"Polkadot JS
Ensure that a release of Polkadot JS API contains any new types or
interfaces necessary to interact with the new runtime."

**Comment by apopiak** [comment]
genesis values WIP here: https://github.com/paritytech/cumulus/tree/apopiak/statemint-genesis-values

**Comment by apopiak** [comment]
Removed the "Initial Statemine Release" part as we split the Statemine and Statemint releases.

**Comment by apopiak** [comment]
Statemint released: https://github.com/paritytech/cumulus/releases/tag/statemine-v6.0.1
