### ISSUE TITLE
Statemine slow syncing issue

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/cumulus#769]
Hi, we are running some statemine nodes and our monitor found our statemine nodes syncs slower than usual today 
![image](https://user-images.githubusercontent.com/14008461/142581406-a9cc7ea6-c5db-4219-a54e-dddff102d20b.png)
I checked the parity official node, the block height is the same as our nodes. Seems like the statemine network having some slow block production issue.

Also, our nodes' finalized block number is far behind the best block, I am not sure whether this is related.

**Comment by bkchr** [comment]
Should be fixed now.

**Comment by AlexZhenWang** [comment]
Thank you @bkchr! May I ask the reason for this?

**Comment by bkchr** [comment]
There are some bugs in Substrate which stopped some of the collators and thus, only one was producing blocks.
