### ISSUE TITLE
Substrate requires that we provide a type for the light client

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#79]
With [this](https://github.com/paritytech/cumulus/pull/76) pr we start a full client, when a light client should be started. This is required to make the interface happy, as it wants a type for the light client. 
As we currently don't support light clients, we should return to panic when someone wants to start a light client.

**Comment by JoshOrndorff** [comment]
I had trouble simply panicing when I tried the same thing in recipes. https://github.com/substrate-developer-hub/recipes/blob/seun-manual-seal/nodes/manual-seal/src/service.rs#L114-L122

The snippet above compiles, but as the comment says it won't if you remove the last line. I think it is related to the `impl AbstractService` in the return type?

**Comment by bkchr** [comment]
Yes, the compiler is not able to determine the type.

**Comment by JoshOrndorff** [comment]
So is this issue just looking to bring in the same code I quoted? I could make that PR.

**Comment by bkchr** [comment]
No that is not the solution I want :D We need to fix this in Substrate^^ 

Your solution works, but this is a hack^^
