### ISSUE TITLE
Log XCMP Queue Errors?

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#800]
The XCMP queue implementation currently just ignores messages that error with anything that's not `WeightLimitReached`.
https://github.com/paritytech/cumulus/blob/8cc008b6a9f70345ec438c4f802c12bbaa05dbd7/pallets/xcmp-queue/src/lib.rs#L393-L395

We should probably log the errors so we can know when it happens?

**Comment by Doordashcon** [comment]
Hi @apopiak been going through the code

what is a valid incoming XCMP message data?

**Comment by apopiak** [comment]
> what is a valid incoming XCMP message data?

you mean as a test case?

**Comment by Doordashcon** [comment]
Yes pls

**Comment by apopiak** [comment]
I would recommend just constructing one in some test code and printing it?
From XCMP perspective an empty XCM should probably be valid? So sth like `Xcm(vec![]).encode()`?

**Comment by bkchr** [comment]
Done by https://github.com/paritytech/cumulus/pull/1147
