### ISSUE TITLE
Node out of sync

### ISSUE THREAD

**Issue by COLUD4** [paritytech/cumulus#816]
I according to this document (https://github.com/paritytech/cumulus) set up after the node synchronization block will stop stay at one block for a long time, after the restart, but soon will stay in a block.
![截屏2021-12-01 下午4 56 49 1](https://user-images.githubusercontent.com/21240219/144203246-43daea8a-c27e-410d-a640-c74e7871e92d.png)
![截屏2021-12-01 下午4 58 16](https://user-images.githubusercontent.com/21240219/144203314-4ce962ac-bb53-4b70-8244-2ab6a04f6248.png)

**Comment by bkchr** [comment]
Which parachain is that?

**Comment by COLUD4** [comment]
Is statemine. This is the start command(./polkadot-collator --chain statemine  --base-path /mnt2/ksmsmmain/node --unsafe-pruning --pruning 5000 --port 9001 --ws-port 25500 --rpc-external  --ws-external --ws-max-connections=20 --rpc-cors '*'  --rpc-port 9002)

**Comment by bkchr** [comment]
Please run with `-lsync=trace` and then share the logs.

**Comment by COLUD4** [comment]
![截屏2021-12-01 下午6 45 10](https://user-images.githubusercontent.com/21240219/144220628-ca642322-29ee-4eb3-bf80-57206780d938.png)

**Comment by bkchr** [comment]
No screenshots and if you are still syncing the relay chain, please wait.

**Comment by COLUD4** [comment]
Parachain finalized is 0.
![截屏2021-12-01 下午7 04 07](https://user-images.githubusercontent.com/21240219/144223685-fb89f31c-bc40-4c36-8e36-007e5719ba52.png)
？

**Comment by bkchr** [comment]
Wait for the relay chain to be synced.
