### ISSUE TITLE
Use Polkadot Constants instead of Hardcoding

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#860]
Now that https://github.com/paritytech/polkadot/pull/4456 is in, we could use the constants crates instead of hard coding the values e.g. [here](https://github.com/paritytech/cumulus/blob/ccf18114326287aedb6906b42c74ed4829c99022/polkadot-parachains/statemine/src/constants.rs#L19-L30).

**Comment by Doordashcon** [comment]
Hello @apopiak
The parachains to be updated are Statemine, Statemint & westmint, to use the crate polkadot-runtime-contants?

**Comment by shawntabrizi** [comment]
@Doordashcon 

Statemine -> Kusama

Statemint -> Polkadot

Westmint -> Westend

So we should use the constants for each of the respective networks.

**Comment by Doordashcon** [comment]
Understood, I'm on it

**Comment by Doordashcon** [comment]
The `EXISTENTIAL_DEPOSIT` values on the Cumulus project don't match Polkadot, should these remain hard coded?

**Comment by bkchr** [comment]
> The `EXISTENTIAL_DEPOSIT` values on the Cumulus project don't match Polkadot, should these remain hard coded?

The existential deposit of statemine/statemint should be something like kusama/polkadot existential deposit / 10. So, you should be able to use this formula.
