### ISSUE TITLE
Teleporting to Statemine is Oddly Expensive

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/cumulus#920]
Reported in https://github.com/polkadot-js/apps/issues/6742#issuecomment-1001986546 as a UI issue.

Fees on the sending side make sense - Kusama is 10x more expensive than Statemine. Fees on the receiving side, however, do not (0.004 on Statemine vs. 0.000106 on Kusama, a factor of almost 40x).

Either there is an error in the XCM weights/benchmarking on the Statemine side, or there is a logical explanation for it. But we need to figure out why there is a 40x difference and either fix it (if broken) or document it (if it's supposed to be that way).

Image pasted for convenience:

![image](https://user-images.githubusercontent.com/25483142/150172477-f4f5e24a-ae67-457e-bb81-7fa9c696330b.png)

![image](https://user-images.githubusercontent.com/25483142/150172505-cef7cac6-bf12-40e5-b8d0-0f5f4c243372.png)

**Comment by hbulgarini** [comment]
To check if this gh issue about benchmarking is related: https://github.com/paritytech/ci_cd/issues/260

**Comment by gilescope** [comment]
The cost is the weight for the downward message:
dmpQueue.ExecutedDownward
Downward message executed with the given outcome. XcmV2TraitsOutcome
{
  Complete: 4,000,000,000
}

**Comment by KiChjang** [comment]
One thing that we would want to definitely check is the exact version of the code (both for Kusama and Statemine) that it was running. Since this was a while back, the weight calculation logic may have been different from master.

**Comment by gilescope** [comment]
"since the destination is what determines the weight (and thereby the fees as well). " - The destination does not determine the fees applied at the source chain (kusama) for sending the message and that is where the high charge is. It is the enqueue of the message that incurs the high cost. As such its a benchmark on the kusama relay chain that will be needed to make the weights less conservative for this particular message type.

**Comment by joepetrowski** [comment]
> "since the destination is what determines the weight (and thereby the fees as well). " - The destination does not determine the fees applied at the source chain (kusama) for sending the message and that is where the high charge is. It is the enqueue of the message that incurs the high cost. As such its a benchmark on the kusama relay chain that will be needed to make the weights less conservative for this particular message type.

No, it's the other way around.

**Comment by NachoPal** [comment]
I think the big difference in fees might be coming from the `refund_surplus()`: https://github.com/paritytech/polkadot/blob/master/xcm/xcm-executor/src/lib.rs#L265 and the `WeightToFee` type the runtimes are using in `refund_weight()` for the fees calculation: https://github.com/paritytech/polkadot/blob/master/xcm/xcm-builder/src/weight.rs#L280

Kusama & Statemine have different `XcmConfig::Trader` configuration, where the type `WeightToFee` is defined. 

Whereas Kusama is using its own `WeightToFee` coming from its constants: https://github.com/paritytech/polkadot/blob/master/runtime/kusama/constants/src/lib.rs#L76-L89 , Statemine is using `IdentityFee` which is coming from `frame_support`: https://github.com/paritytech/substrate/blob/polkadot-v0.9.16/frame/support/src/weights.rs#L698-L714

Replacing `IdentityFee` by its own `WeightToFee` in the Trader: https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/statemine/src/xcm_config.rs#L165 might tell us if it is the source of the issue.

**Comment by KiChjang** [comment]
@NachoPal Good catch! `IdentityFee` is quite suspect in fact, paying 1 planck to 1 unit of weight doesn't seem to make a whole lot of sense, we should really change it to `WeightToFee`.

**Comment by gilescope** [comment]
This is fixed as of statemine v800 runtime release.
