### ISSUE TITLE
Refactor cumulus test service

### ISSUE THREAD

**Issue by zqhxuyuan** [paritytech/cumulus#932]
current cumulus test service only support [`Consensus::RelayChain`](https://github.com/paritytech/cumulus/blob/master/test/service/src/lib.rs#L278), and the test-service is rely on cumulus-test-runtime. if parachain want to use its own test-service, they have to use their own runtime. also the parachain may use other consensus like `aura`. so the refactor work I current thought of should at least fulfil following target, so that parachain can integrate cumulus-test-service easily:
- test-service not rely on test-runtime
- support Aura consensus

**Comment by bkchr** [comment]
> * support Aura consensus

This is tracked here: https://github.com/paritytech/cumulus/issues/430



> * test-service not rely on test-runtime

This is not really a goal of the test-service. This entire test suite is for cumulus internally, not really for external projects. If you need this, you can just copy it.
