### ISSUE TITLE
IncompleteDatabase runtime failure

### ISSUE THREAD

**Issue by akru** [paritytech/cumulus#95]
**Traceback**

```
2020-05-11 13:30:06 panicked at 'Calculates storage root: IncompleteDatabase(0x82faa27dd970cd50c955d0c97605fae0e5a3f505db0ed812955e8beb7842647d)', /home/akru/.cargo/git/checkouts/cumulus-59522f43471fa161/e810cf3/runtime/src/validate_block/implementation.rs:209:20
```

**Description**

This failure reached after two days of stable work as parachain in local testnet.

**Comment by akru** [comment]
This one looks repeatable, each time it happens on best `1,728` finalized `1,729` block.

What do you think @bkchr?

**Comment by bkchr** [comment]
@akru Ty for reporting this. This looks like we are missing something in the proof. I assume you triest latest master?

@cheme any knowledge about a potential bug in the proof recorder?

**Comment by akru** [comment]
@bkchr sure, it’s latest master: https://github.com/airalab/robonomics/blob/robonomics-parachain/bin/node/cli/Cargo.toml#L80

Thank you for your work!

**Comment by cheme** [comment]
#90 did register one less node on prefix iteration, so if this start happening after a cumulus upgrade it could be related (thinking of a proof produced with #90 updated but checked on a non updated validation function).

**Comment by akru** [comment]
@cheme unfortunately I didn’t test upgrade pallet yet because of build failure. It happens without upgrades.

**Comment by cheme** [comment]
It could be the other way around in fact: #90 fixing it.
Substrate base code uses same iter as #90 (producing a proof with one less element) and then validation function build from cumulus pre #90 would fail because it expect the additional node.
These iteration are mainly use by prefix deletion host function.

**Comment by bkchr** [comment]
> @cheme unfortunately I didn’t test upgrade pallet yet because of build failure. It happens without upgrades.

@cheme was speaking about an update of the Cumulus code itself and not using the upgrade pallet ;)

**Comment by akru** [comment]
Got it, but runtime uses validation function from https://github.com/paritytech/cumulus/commit/e810cf3b5ba4b6b1a2848bc57a6302146fc54d78 as you can see in trace back.

**Comment by cheme** [comment]
If runtime uses validation from 7 days ago but proof is produced from code including #90 from 4 days ago then we are probably in the first case I describe.
What I am not really sure is if the proof production with cumulus is using substrate host function or cumulus host function (in first case it would indicate cumulus host function in second case substrate host function).

**Comment by akru** [comment]
Ok, no problem, I’ll relaunch it Gran scratch for today’s master and come back with updates.

**Comment by akru** [comment]
Great, with latest master runtime it don’t fail on that place more, thank you @cheme @bkchr !
