### ISSUE TITLE
Could not find the header of the genesis block in the database

### ISSUE THREAD

**Issue by rakanalh** [paritytech/cumulus#962]
Using:
- Substrate / Polkadot / Cumulus: 0.9.16 branches

Issue: 
```
ERROR tokio-runtime-worker cumulus-collator: [Parachain] Could not find the header of the genesis block in the database! block_hash=0x7b3a00af0fb72acfbd357a1de8ceb33d1b819f7c3770048f6a12bbd045584044
```

The exported `para-2000-gensis` contains the following:
```
> ./target/release/parachain export-genesis-state --chain rococo-local > para-2000-genesis
> cat para-2000-genesis
0x000000000000000000000000000000000000000000000000000000000000000000efd65f9899b1180c6ea8b3cba72d336dd8e00e6bd7e37eda8c5da2eaa40808f703170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
```

Running the upgraded parachain node shows the correct header at the beginning:
```
INFO main parachain::command: Parachain id: Id(2000)
INFO main parachain::command: Parachain Account: 5Ec4AhPUwPeyTFyuhGuBbD224mY85LKLMSqSSo33JYWCazU4
INFO main parachain::command: Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000efd65f9899b1180c6ea8b3cba72d336dd8e00e6bd7e37eda8c5da2eaa40808f703170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
```

But when the parachain is onboarded, the node tries to start collating and block production but fails with the error above.

IIUC, the registered genesis state on the relaychain (rococo-local) has the content of `para-2000-genesis` from above and the parachain node uses that to validate against the locally generated genesis header hash after loading the spec internally. 

What could be the issue in this case?

**Comment by bkchr** [comment]
What chain do you use? 

Check that `state_version` in your runtime is set to `0`.

**Comment by rakanalh** [comment]
You're right. That fixed it. Thanks @bkchr
