### ISSUE TITLE
Rename `polkadot-collator` bin

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/cumulus#979]
Related to https://github.com/paritytech/cumulus/issues/928

A lot of people I've talked to recently are confused about what a collator is and often think they need to have a collator in order to run a node. Of course, it is the other way around. We should rename the binary such that being a `collator` is an option. I think `parachain-node` would be OK but happy with anything more general than "collator".

**Comment by NukeManDan** [comment]
I agree :point_up: I would suggest also moving the template to `parachain-node-template` so that cumulus is roughly homomorphic to Substrate with a `parachain-` prefix on the main binaries.

**Comment by joepetrowski** [comment]
I don't have an opinion on that but it's beyond the scope of this issue (naming of "Assets" in the releases vs. code structuring). I'll close this once CI starts calling the binary `parachain-node`, but feel free to log another issue about code/development templates.

**Comment by bkchr** [comment]
I would go for `polkadot-parachains`. What does `parachain-node` convey to you? Which parachain? All? 

In the far future I would actually like to see some kind of "Ueber" node that supports all parachains, at least for syncing them :)

**Comment by joepetrowski** [comment]
> What does parachain-node convey to you?

That it's a node for a parachain :)

> Which parachain? All?

I thought that with Wasm execution, yes.

**Comment by bkchr** [comment]
But even with Wasm execution, the node is not prepared to run every parachain. Statemine/Statemint for example need to go through this change from shell to the actual runtime and that requires some special code on the node side. Statemint is then using different crypto etc. There is a ton of stuff why this node will not be used for *all* parachains that easily.

**Comment by xlc** [comment]
I never know it suppose to work with other parachains? Or does it?

**Comment by bkchr** [comment]
No. It was never written in any way to work with other parachains. As I said, we could probably make that possible in the future, but that will not happen in the near future.

**Comment by joepetrowski** [comment]
> I would go for polkadot-parachains

OK, I'm good with this. Would drop the plural and just call it `polkadot-parachain` but won't put up too much of a fight :)

**Comment by bkchr** [comment]
I also don't care about dropping the plural. I'm also no native speaker, so I'm the last one that will say something about correct naming :D
