### ISSUE TITLE
Enable collation with external relay chain full node

### ISSUE THREAD

**Issue by skunert** [paritytech/cumulus#989]
As discussed in https://github.com/paritytech/cumulus/issues/545 we want to support running the collator relay chain node as its own process.
After https://github.com/paritytech/cumulus/pull/963 lands, we are in a position to run a parachain full node without running a relay chain full node internally. To run a proper parachain collator, we miss some of the subsystems usually running inside the full node. They do not offer an RPC interface, so I plan to start the relevant subsystems inside the collator.

## Relevant Subsystems
![CleanShot 2022-02-15 at 12 18 53](https://user-images.githubusercontent.com/5718005/154051817-9fb792b0-52e4-49a1-a52d-f085ec434a67.png)
After checking the code, I found that the following subsystems are involved:
- Availability Recovery
- Collation Generation
- Collator Protocol
- Network Bridge
- Runtime API
- Availability Store
- Chain API

The Availability store should be optional for now since the data we request from it will not be available inside the collator anyway and will then be requested from the Network Bridge.

## Implementation Plan
- Implement a custom `OverseerGen` that will replace unused Subsystem with dummies that drain channels
- Feed a client to the Runtime API subsystem that will use the RPC Client introduced in https://github.com/paritytech/cumulus/pull/963 to perform runtime calls

Related discussion in https://github.com/paritytech/polkadot/issues/4763

**Comment by bkchr** [comment]
CC @drahnr maybe you have some input on the `OverseerGen` stuff :)

**Comment by drahnr** [comment]
I think implementing `OverseerGen` for implementation of that is really all you need to do, besides assuring to `overseer_enable_ anyways`. Make sure to consume messages in the dummy subsystems or assert none are sent there. Ping me as needed.

**Comment by gregzaitsev** [comment]
Hi, Sebastian! Is there any way to contribute to this issue? Looks like collators are almost finished, is that right?

**Comment by skunert** [comment]
Hey @gregzaitsev, I have a branch where this works, some refactorings and polish needs to be done still.
So currently there is not much to contribute here, the feature will land soon.

**Comment by drahnr** [comment]
@skunert I assume you are aware, a few weeks ago a change landed that splits the network bridge into two, incoming and outgoing messages, so the initial diagram might need some adjustments :)
